### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by claudiosanches** [wpbrasil/odin#100]
Acho que rola agora adicionar uns widgets personalizados no Odin.
A mesma ideia que tem em temas premium, por exemplo: widget com abas, facebook e etc.

Gostaria de sugestão de vocês.
O que vocês usam de widget e as vezes precisam instalar plugins porcos para fazer? xD

**Comment by tofanelli** [comment]
galera... 

pergunta de marinheiro de 1a viagem... acabei de descobrir o odin e venho trabalhando um bocado com bootstrap...

como anda esta parte aqui?

uma coisa que eu acho que seria interessante era a criacao de uma parte estilo um codepen ou jsfiddle ou algo assim dentro do wordpress... ae poderiamos fazer o codigo todo ali do bootstrap e depois so adicionar o shortcode relativo a este codigo e pronto.... tudo rodando bacana =)


Valeuz =)

**Comment by ivanildodias** [comment]
Acho interessante alterar a parte que forma os widgets padrão do Wordpress para as formações padrão do Bootstrap.

Por exemplo:
Se colocarmos `class="nav"` no elemento `<ul>` da lista de categorias ele já fica com um visual bem mais "bootstrap".
No caso da lista de comentários, poderia ser `class="list-group"` no elemento `<ul>` e `class="list-group-item"` nos elemento `<li>` para ficar com a aparência dos list-groups.
Na Tag Cloud colocaria como `class="label label default"` talvez com um filtro para escolher o tipo de label que o usuário quer.

Estou desenvolvendo um tema com Bootstrap e estou testando essas adaptações. Coloquei cada widget dentro de um `class="panel panel default"` e adaptei os widgets padrão. Ficou bem assim:
![inteiro](https://cloud.githubusercontent.com/assets/10048508/8416219/9d32476e-1e7a-11e5-9c0b-60e3c8f978b9.jpg)

O que vocês acham?

**Comment by joao-parana** [comment]
oi @ivanildodias achei a ideia muito boa. Minha dúvida é como fazer isso no código do Wordpress de forma robusta, ou seja, o que acontece com os arquivos alterados quando você atualiza a versão do Worpress ? você teria de aplicar as alterações na nova versão, certo ? 

Desculpe se não entendi a abordagem, talvez eu tenha perdido algo na sua explicação.

Abs.

**Comment by ivanildodias** [comment]
@joao-parana, nesse meu exemplo eu fiz assim:

1. Criei um novo arquivo chamado `default-widgets.php`;
2. Copiei o código das classes padrão para ele;
3. Fiz as alterações, mas mantive o mesmo `classname` que é passado na função `__construct()` das classes padrão;
4. Usei a função `register_widget();` para registrá-las.

Assim, não alterei nada padrão do WordPress (mantendo a possibilidade de atualização sem problemas) e ainda consigo que os meus widgets personalizados sejam chamados em vez de chamarem os widgets padrão.

Acho que agora ficou melhor explicado. Não tenho certeza se essa é a melhor forma de fazer isso, mas também acho que é uma boa ideia.

**Comment by joao-parana** [comment]
oi ,

o código que você copiou foi de wp-includes/default-widgets.php, certo ?

Meu questionamento é sobre a seguinte situação. 

Imagine que o pessoal do Wordpress numa futura atualização de versão, digamos, da 4.2.2 para 4.2.3,  altere o código do construtor ou outra parte do código em wp-includes/default-widgets.php que afete radicalmente o comportamento. Neste caso teremos de fazer um **diff** da versão 4.2.2 de wp-includes/default-widgets.php original com a fornecida na 4.2.3, identificar as mudanças  e aplicar as diferenças no seu arquivo default-widgets.php. 

Me diga se meu raciocinio está correto.

Se for este o caso, acho que devemos usar outra abordagem para que o Tema Odin não fique tão acoplado a uma versão específica do Wordpress.

Como disse achei sua ideia ótima e acho que devemos procurar uma forma criativa de implementar evitando este acoplamento.

Abs.

A proposito, você tem esse tema que você desenvolveu à partir do Odin num fork deste projeto ? Seria util disponibilizar para avaliarmos melhor.

**Comment by ivanildodias** [comment]
@joao-parana... Como eu falei.. Não sei se essa é a melhor forma de fazer isso. Por isso lancei a ideia aqui para os nossos amigos experts do WPBrasil indicarem um caminho melhor.

Mas, a respeito de atualizações, acho que não teria problemas pois funcionaria como um widget personalizado que é chamado em vez do widget padrão, já que usa o mesmo `classname`. Só teria problema se o pessoal do WordPress mudar o `classname` na atualização.

Esse tema que eu estou desenvolvendo não é bem um fork do Odin modificado. Eu gosto de fazer as coisas por mim mesmo para aprender, então, estou coletando algumas ideias mais simples do Odin e aplicadando num framework próprio meu. Algumas coisas estou fazendo diferente, como por exemplo a paginação, dentre outras coisas. Mais a título de aprendizado, pois sou um iniciante dedicado. :D

Caso queira dar uma olhada, esse é o: https://github.com/id-design/is_simple_wp

**Comment by brunolimadevelopment** [comment]
pra quem utiliza o sublime text
https://github.com/SublimeUser/bestplugins
