### ISSUE TITLE
Classe para custom fields em taxonomias

### ISSUE THREAD

**Issue by claudiosmweb** [wpbrasil/odin#106]
Avaliar a necessidade e a possibilidade de criar classe gerar custom fields para taxonomias.

Ref: https://github.com/bainternet/Tax-Meta-Class

**Comment by adammacias** [comment]
- Adicionando Metabox para tela de edição de terms #318
- Documentação para class-term-meta #320
- https://github.com/wpbrasil/odin/wiki/Classe-Odin_Term_Meta
