### ISSUE TITLE
[CLASSE METABOX] Problema ao setar checkbox com atributo "checked" por padrão

### ISSUE THREAD

**Issue by fdaciuk** [wpbrasil/odin#124]
Ao setar o atributo `default` como `1` na criação do checkbox, ele sempre ficava marcado após salvar o post, ainda que desmarcasse, pois os valores da função checked() estavam invertidos.

Ajustado [nesse commit](https://github.com/wpbrasil/odin/commit/464ba13c6a2864ca405512c211c933dd9f559749).

**Comment by romuloctba** [comment]
+1

**Comment by fdaciuk** [comment]
Coloquei pra eu fazer mas acabei ficando sem tempo e nem mexi nisso.. se alguém quiser tentar :)

**Comment by romuloctba** [comment]
Pretendo tendar depois, nao vou prometer :P qual a solução q vc acha q achou?

**Comment by fdaciuk** [comment]
A do `hidden` no checkbox: https://github.com/wpbrasil/odin/issues/124#issuecomment-42114502

Pode ser que funcione xD
