### ISSUE TITLE
Metabox criado, mas como vincular apenas a uma página específica?

### ISSUE THREAD

**Issue by walterjaworski** [wpbrasil/odin#155]
Criei alguns metaboxes pra controlar textos da home, que serão utilizados somente nela.

A home é uma "página", logo, no código de criação do metabox coloquei " 'page' ", porém ele aparece em todas as páginas.

Gostaria de que estes metaboxes fossem exibidos apenas quando vou editar a página home, e não as outras. Tem como?

**Comment by amandavelino** [comment]
Eu poderia criar uma página de configuração, mas acho mais fácil criar metaboxes neste caso apenas pra home mesmo, valeu @fdaciuk ! :) Depois de 3 anos ainda é útil xD!
