### ISSUE TITLE
Colocar exemplo de Código na Página de Demos

### ISSUE THREAD

**Issue by deblynprado** [wpbrasil/odin#161]
Alterar as páginas com demo dos Shortcodes para ter também o exemplo de código de cada demo.

**Comment by pabloworks** [comment]
Pessoal os links da demo estão off

**Comment by rafaelfunchal** [comment]
Temos que editar a documentação, @pabloworks . O demo não existe mais.

**Comment by pabloworks** [comment]
@rafaelfunchal entendi, vlw.
