### ISSUE TITLE
Odin_Contact_Form e Flamingo

### ISSUE THREAD

**Issue by jonasrafael** [wpbrasil/odin#179]
Alguém por ventura já utilizou o Contact Form do Odin com Flamingo? Funciona?

"Flamingo is a WordPress plugin created to be a total CRM package. With this version, you can manage your contact list and messages submitted via contact form plugins. It has not yet matured, but we are enhancing it rapidly."

**Comment by claudiosmweb** [comment]
Teste e me diga se funciona.

**Comment by jonasrafael** [comment]
Esqueci de responder... Eu testei e não funcionou. Tive que usar o contact form mesmo.
