### ISSUE TITLE
Erro no nome das actions para metaboxes

### ISSUE THREAD

**Issue by leobaiano** [wpbrasil/odin#182]
Na documentação os nomes das 3 actions disponiveis na classe metaboxes estão incorretas, acredito que os nomes foram modificados em algum dos commits e não foi corrigido na documentação.

Na documentação atual temos:
- odin_metabox_table_before_SLUG
- odin_metabox_table_after_SLUG
- odin_metabox_field_SLUG

Porém na classe Odin_Metabox os filtros são aplicados com outros nomes e existem outros filtros não documentados. por exemplo, ao invés de odin_metabox_table_before_SLUG o correto seria odin_metabox_wrap_before_SLUG.

**Comment by joaovsilva** [comment]
@leobaiano Qual a situação da issue? Já foi resolvido?

**Comment by leobaiano** [comment]
Até onde sei a issue está parada. Comecei a editar a documentação, mas não está completa ainda, se tiver com tempo pode focar isso @joaovsilva
