### ISSUE TITLE
Odin Framework para desenvolvimento de plugins

### ISSUE THREAD

**Issue by leobaiano** [wpbrasil/odin#183]
Tive a ideia de utilizar o Odin como framework para desenvolver um plugin e percebi que ele atende bem a este proposito, então tive a ideia de criar uma versão do Odin para plugins.

Copiar o core para dentro do diretório do plugin não é tão efetivo e é necessário mudar os caminhos que utilizam a URL do tema ativo como base para arquivos CSS e JS. Por exemplo, eu precisei alterar a classe de metaboxes porque ela utilizava a função `get_template_directory_uri();` para carregar o CSS e JS. Outro problema que vejo é com relação a funções/ classes específicos de temas e não são necessários no desenvolvimento de plugins, também temos funções que são mais para plugins e por isso não fazem parte do Odin, mas são uteis em um framework para plugin.

Pensei em uma forma onde seja possível trabalhar apenas em cima de um código, mas inevitavelmente vamos carregar coisas desnecessárias, por conta disto acho que é melhor desenvolver algo novo, utilizando o que já tem pronto no Odin.

Trago essa sugestão para saber o que acham.

**Comment by lucasmiranda5** [comment]
Galera o framework para plugin vai sair? se sim posso ajudar

**Comment by rafaelfunchal** [comment]
Uma hora sai, calma.

Fique ligado nesse canal para ver os próximos capítulos :)

**Comment by matheusgimenez** [comment]
Eu ainda acho que deveria funcionar como o underscores por exemplo, na hora do download altera o nome das classes/funções, pra evitar sobrepor.

**Comment by claudiosmweb** [comment]
Talvez no futuro, tenho alguns planos para melhorar essas classes e assim deixar mais simples de usar utilizado, mas não vejo isso acontecendo agora e talvez deva ser movido o projeto para outro repo.
