### ISSUE TITLE
Site do Odin

### ISSUE THREAD

**Issue by claudiosanches** [wpbrasil/odin#184]
Galera, na moral mesmo, acho que seria mais vantagem voltar isso para o Github, não estamos usando para nada o site xD
Acho que vou deixar no WordPress mesmo só o demo e a homepage do Odin podia virar um HTML aqui.

O que vocês acham?
Alguém anima de fazer uma página nova usando o logo novo?

**Comment by fdaciuk** [comment]
Sei que já tá fechada essa treta, mas só pra avisar todo mundo: Odin entrou no [Beautiful Open](http://beautifulopen.com/)! :dancer: :dancer:

**Comment by rafaelfunchal** [comment]
\o/

**Comment by adammacias** [comment]
It is beautiful! :open_mouth: :rainbow:

**Comment by rodrigo73** [comment]
Show!
