### ISSUE TITLE
Classe Walker mais enxuta para projetos sem Bootstrap

### ISSUE THREAD

**Issue by brenoalvs** [wpbrasil/odin#195]
O Odin já tem um walker pra gerar o menu corretamente para o Bootstrap. Mas que tal criar um para gerar um HTML do menu mais enxuto do que o padrão do WordPress? Acho que seria muito útil para os projetos que não usam Bootstrap, e ficaria mais elegante sem aquele monte de classes que quase ninguém usa.

Ou então pensar em um walker simples, mas "configurável", podendo ter:
- Definição/alteração de classes e ids
- Definição/alteração das tags wrapper de cada elemento e subnível, para o caso de não ser uma lista.

Acho que daria uma liberdade maior pra quem é mais leigo, ter sua própria estrutura de HTML para o menu. O que acham?

**Comment by claudiosmweb** [comment]
Sem bootstrap é melhor não usar essa classe, ela só esta ai para suportar o Bootstrap.
