### ISSUE TITLE
Front end form com a classe Odin_Post_Form

### ISSUE THREAD

**Issue by nandomoreirame** [wpbrasil/odin#200]
Olá!
Preciso desenvolver um formulário para salvar um Custom Post Type direto do site, notei que existe uma classe que cria esse form mas não existe documentação para isso...

Eu consegui criar o form mas o meu problema é com as imagens... 

Eu preciso salvar 8 imagens em um Metabox de galeria que criei usando o Odin... 

Existe uma forma de salvar essas imagens usando essa classe Odin_Post_Form?

Grato.

**Comment by adammacias** [comment]
Fechando essa, deixar só a issue #94
