### ISSUE TITLE
[Odin_Post_Form] Relacionar campos checkbox do Odin com os do ACF

### ISSUE THREAD

**Issue by castroalves** [wpbrasil/odin#206]
Pessoal,

Criei um formulário com o Odin para publicar o conteúdo direto em um CPT, cujos campos foram criados com ACF.

Como faço para correlacionar os campos checkbox do Odin (frontend form) com os do ACF?

**Comment by claudiosmweb** [comment]
Não.

**Comment by claudiosmweb** [comment]
Na verdade já da, só salvar como custom field mesmo xD
