### ISSUE TITLE
Odin Breadcrumb Woocommerce Single Product

### ISSUE THREAD

**Issue by jonasrafael** [wpbrasil/odin#208]
Tô usando o Odin com o Woocommerce, na interna do produto ele teima em aparecer o link pra ?taxonomy=product_type&term=simple

![screen shot 2014-11-05 at 3 35 12 pm](https://cloud.githubusercontent.com/assets/1548002/4922488/6a7557a2-6512-11e4-91d1-c3b719316f47.png)

alguém?

**Comment by adammacias** [comment]
@jonasrafael testei aqui e aparentemente o destino do link das categorias estão tudo funcionando.

**assim:**

 `/?product_cat=simple`. 

Talvez o WooCommerce já deve ter corrigido o problema que você citou, por isso vou fechar a issue, caso ainda tenha esse problema, comente ;)

**Comment by AdsonCicilioti** [comment]
Comigo ocorre o mesmo que o @jonasrafael , usando o odin_breadcrumbs. Testei com o woocommerce_breadcrumb e a trilha ficou perfeita, exceto pela marcação html.

Vale deixar uma analise de como as duas funções se comportam.
1) Com **odin_breadcrumbs()** : 
`Home / Produtos / variable / Nome do Produto` onde: 
- `Home` cumpre seu papel
- `Produtos` é o nome do Post Type de itens do WooCommerce (ideal seria retornar o titulo da pagina com `wc_get_page_id( 'shop' )` ).
- `variable` é um dos termos da taxonomia **product_type** (simple, variable, grouped e external).
- `Nome do Produto`cumpre seu papel.

2) Com **woocommerce_breadcrumb()** : 
`Home / Loja / Categoria pai / Categoria filha / Nome do Produto` onde:
- `Home` cumpre seu papel
- `Loja` é o titulo da pagina com obtida com `get_the_title(wc_get_page_id( 'shop' ) )` .
- `Categoria Pai` retorna o termo da taxonomia **product_cat**
- `Categoria Filha` assim coma a categoria pai retorna o termo da taxonomia **product_cat**.
- `Nome do Produto` cumpre seu papel.

A marcação html do odin_breadcrumbs tá ok, porém, para aumentar o suporte ao WooCommerce teria que receber as melhorias necessárias para retornar as trilhas iguais a do woocommerce_breadcrumb.

Alguém se habilita?

Vou tentando aqui tomando como referência a class do Woo.

**Comment by AdsonCicilioti** [comment]
Será que vale a pena tentar arrumar isso @adammacias ?

**Comment by adammacias** [comment]
Entendi @AdsonCicilioti , eu havia entendido que era a função `woocommerce_breadcrumb()` que estivesse dando problema, nem cheguei a testar o `odin_breadcrumbs()`.

Vou reabrir o tópico e ver no que o pessoal pode ajudar. @wpbrasil/developers

**Comment by AdsonCicilioti** [comment]
Acho que to conseguindo arrumar aqui. Assim que pronto já posso mandar um PR @adammacias ? Como posso proceder?
