### ISSUE TITLE
Tags <h1> duplicadas

### ISSUE THREAD

**Issue by ruanbarbosa** [wpbrasil/odin#22]
Olá pessoal, enviei um commit com uma sugestão para o título do blog e sua descrição, pois as páginas estão com duas tags 'h1'. Já o motivo da retirada da tag 'h2' foi devido a ordem lógica (não ter nenhuma tag 'h1' antes).

**Comment by AdsonCicilioti** [comment]
2 anos se passaram e o Gustavo nada.. xD

Bom então vou ressuscitar o tópico pois o assunto é sério e rola até penalidade dos motores de busca, então vale a pena darmos mais atenção.
Nas Paginas de Arquivos e Categorias, o 1º H1 é título da pagina dentro de uma <section>, depois vem o loop com seus <articles> e seus respectivos H1's.

Não sou expert em SEO, mas por mais que existam formas válidas de se usar multiplos H1's, fico com a via de facilidade e velocidade para os motores de busca entenderem melhor nossas páginas e conteúdos.

Dei uma pesquisada e achei muito válida a definição do Yoast > https://yoast.com/blog-headings-structure/

Tem a questão da palavra chave principal também, se existirem várias vai dar um barulho no algarítimo de indexação dos SE's não acham?

Eu voto por mudar a condicional de títulos do arquivo content.php, deixando h1 se for single e h2 para os loops.

Bom é isso espero, que tenha colaborado. Abraço a todos! ;)

**Comment by AdsonCicilioti** [comment]
Vale ainda um adendo - um artigo sobre as formas corretas de utilizar multiplos H1's - http://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824

**Comment by deblynprado** [comment]
O Google não deveria punir a utilização de mais de 1 h1 a não ser que ele de fato esteja sendo utilizado de forma errada.

A especificação do HTML5 permite que tenhamos h1 dentro da Section, por exemplo. Inclusive o validador reclama se você colocar uma section sem algum **h** dentro

http://www.w3.org/TR/html5/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements

**Comment by AdsonCicilioti** [comment]
Entendi @deblynprado - Mas então, como eu disse não sou expert em SEO, e essa história de punição me deixou grilado em arriscar. Mas no caso das páginas que citei, elas estão estruturadas de forma correta? 
Em síntese a estrutura está assim:
```
<section>
 <h1>Titulo da Pagina</h1>

  // Inicio do Loop

 <article>
  <h1>Titulo do artigo</h1>
  // conteudo
 </article>
 <article>
  <h1>Titulo do artigo</h1>
  // conteudo
 </article>
 <article>
  <h1>Titulo do artigo</h1>
  // conteudo
 </article>

  // Fim do Loop

</section>

```

**Comment by deblynprado** [comment]
A estrutura a respeito do `h1` está correta sim @AdsonCicilioti, uma outra possibilidade seria utilizar

```
<article>
 <header>
  <h1>title here</h1>
 </header>
</article>
```

o que pode ser repensado aí é a utilização da `<section>` do lado de fora

http://www.w3.org/TR/html5/sections.html#the-article-element

**Comment by claudiosmweb** [comment]
@AdsonCicilioti você disse que não é especialista em SEO, mas fez varias acusações e especulações.
 
> Não sou expert em SEO, mas por mais que existam formas válidas de se usar multiplos H1's, fico com a via de facilidade e velocidade para os motores de busca entenderem melhor nossas páginas e conteúdos.

Como que isso que você "fica" com a "facilidade e velocidade", principalmente "velocidade"? xD
Como você pode afirmar que algo é mais rápido ou não? Você mesmo falou que não é expert... Ou como você fala de "facilidade" sem saber como acontece?

Alias, antes de começar a especular e acusar sobre algo, é bom ler a documentação oficial, como o @deblynprado esta lhe indicando!

Além do mais que tudo aqui é inspirado nos temas padrões do WordPress, que por sinal são indicados como referencias de SEO!
Sem contar o fato de que os temas padrões do WordPress são revisados pelo mundo inteiro, então se realmente tivesse algo errado, neles não seriam assim e muito menos aqui seria desta forma!
