### ISSUE TITLE
Adicionar add_theme_support() para HTML5

### ISSUE THREAD

**Issue by claudiosmweb** [wpbrasil/odin#226]
Ref: http://codex.wordpress.org/Semantic_Markup

**Comment by adammacias** [comment]
Boa @claudiosmweb ! esta feito, aproveitei e pensei que seria uma boa add suporte para o 'title-tag' tambem, fiz uma pull resquest, se acharem útil, só aceitar :)

**Comment by claudiosmweb** [comment]
Então com isso precismos atualizar por exemplo o form de busca para usar o input do tipo `search` quando ativado o suporte para HTML5.
Acredito que só falta essa atualização.

**Comment by fdaciuk** [comment]
Booa! :+1:

**Comment by adammacias** [comment]
Forms de busca ok! =)

**Comment by claudiosmweb** [comment]
Ótimo :D
