### ISSUE TITLE
Adicionar 'the_post_navigation()' e 'the_archive_description()'

### ISSUE THREAD

**Issue by adammacias** [wpbrasil/odin#230]
O que vocês acham de implementarmos as funções ```the_post_navigation()``` e ```the_archive_description()```? Já estão usando no tema **twentyfifteen**, foram criadas na versão WP 4.1.

Referencias:
- https://developer.wordpress.org/reference/functions/the_archive_title/
- https://developer.wordpress.org/reference/functions/the_archive_description/
- https://themes.svn.wordpress.org/twentyfifteen/1.0/archive.php

**Comment by claudiosmweb** [comment]
Por mim ótimo, bem melhor assim e menos string de tradução xD
