### ISSUE TITLE
bug em paginação de arquivos: datas, categoria, tags e autor

### ISSUE THREAD

**Issue by adammacias** [wpbrasil/odin#232]
Pessoal, quando **Links Permanentes** está no formato **padrão** a paginação deixa de funcionar nos arquivos de `datas, categoria, tags e autor`.

**Comment by claudiosmweb** [comment]
Na verdade o formato pode ser ocultado, o WordPress já gera isso.

**Comment by claudiosmweb** [comment]
Para esses dois da para seguir o exemplo do WooCommerce que vai funcionar para tudo https://github.com/woothemes/woocommerce/blob/master/templates/loop/pagination.php#L23-L24
