### ISSUE TITLE
Menu dropdown em níveis

### ISSUE THREAD

**Issue by netoliveira** [wpbrasil/odin#235]
Olá!

Existe alguma configuração para exibir o menu em vários níveis?

Pesquisei um plugin em jQuery para a criação de menu em níveis e com dropdown no hover, testei e funcionou legal.

Vcs pretendem criar essa opção de mais níveis no menu? Uma solução seria adicionar esse plugin ao tema.

**Comment by claudiosmweb** [comment]
Só usar o menu do normal do WordPress.
Se for usar com os estilos do Bootstrap vai rolar apenas com 1 sub nível.
Bootstrap por padrão não aceita mais.
