### ISSUE TITLE
Incluir opção no tema para alterar/ definir valores para as template tags

### ISSUE THREAD

**Issue by leobaiano** [wpbrasil/odin#236]
As funções do arquivo `incs/template-tags.php` estão retornando valores diretamente e isso pode atrapalhar um pouco, por exemplo, se eu quiser utilizar a estrutura do Odin como base e precisar alterar a largura da área de conteúdo e da sidebar tenho que modificar direto na função, talvez fosse interessante incluir isso nas opções do tema.

**Comment by allysonsouza** [comment]
Você fala de criar uma página de opções no painel @leobaiano? Ou algum tipo de configuração em arquivo/script?

**Comment by leobaiano** [comment]
No arquivo `template-tags.php` temos:

`
function odin_classes_page_sidebar_aside() {
	return 'widget-area col-md-4 hidden-xs';
}
`

No arquivo `sidebar.php`:

`
<div id="secondary" class="<?php echo odin_classes_page_sidebar_aside(); ?>" role="complementary">
`

Eu quero a sidebar com 3 colunas, para isso ou apago o echo na div ou modifico a função no template-tags.php. Se a função recebesse o valor da quantidade de colunas isso não aconteceria, tipo:

`
function odin_classes_page_sidebar_aside( $cols = 4 ) {
	return 'widget-area col-md-' . $cols . ' hidden-xs';
}
`
Na verdade é algo tão simples que queria ver a opinião de outras pessoas.

**Comment by allysonsouza** [comment]
Agora entendi!

+1

**Comment by adammacias** [comment]
Podemos enviar como parâmetro **$classes** ao invés de **$cols**, por que vai que o cara queira deixar o uma coluna com 4 colunas em *small-screen* e 5 em *large-screen*. Daí só fazer uma validação caso o **$classes** for nula, aplica o tamanho da coluna padrão do **Odin**.
De resto concordo plenamente com você @leobaiano precisamos mudar isso! :+1:

**Comment by adammacias** [comment]
@leobaiano verifica por favor se está tudo ok :smile:

**Comment by claudiosmweb** [comment]
Agora que vi pra que foi a alteração do template tags.
Sinceramente a ideia é você alterar essas classes na mão no Odin e dentro de um tema filho você pode sobrescrever essas funções.
Exatamente por isso ela são "Pluggable Functions".

**Comment by adammacias** [comment]
Concordo com o pensamento em relação ao "Pluggable Functions", até porque, dá o mesmo trabalho fazer:

`<div id="sidebar" class="<?php echo odin_classes_page_sidebar_aside( $cols = 4 ); ?>">`

ou isso:

`<div id="sidebar" class="<?php echo odin_classes_page_sidebar_aside(); ?> col-md-4">`

Acho que podemos fechar essa.
