### ISSUE TITLE
Erro na função odin_thumbnail()

### ISSUE THREAD

**Issue by rodrigo-brito** [wpbrasil/odin#237]
Em casos onde a miniatura é menor que os valores de corte passados, a função retorna uma imagem com url vazia. Preciso passar alguma parâmetro a mais ou fazer algum condicional em caso de miniaturas menores que o corte?

![thumb](https://cloud.githubusercontent.com/assets/7620947/6004566/dccc015c-aaea-11e4-9007-dc92e1a8f888.jpg)
.

**Comment by fdaciuk** [comment]
Se não me engano, já foi arrumado esse problema. Você está com a versão mais recente do Odin?

**Comment by rodrigo73** [comment]
Atualizei o código do core/helpers.php e também a classe core/classes/class-thumbnail-resizer.php
Não consegui encontrar outra dependência do odin_thumbnail, e o problema continua me alfinetando haha. Vlw pela ajuda, vou continuar tentando aqui.

**Comment by rodrigo73** [comment]
Fiz uma alteração temporária e por enquanto, resolve bem o problema, acredito que seja o Aqua Resizer... vou fazer alguns testes com ele separado e ver se realmente é ele.
![desk](https://cloud.githubusercontent.com/assets/7620947/6012140/79e2cb8e-ab2b-11e4-9ea3-4e2f3470855c.jpg)

**Comment by rodrigo73** [comment]
Descobri o problema, baixei do repositório original do Aqua Resizer a classe para corte, dei uma olhada e vi que o process tinha dois parâmetros a mais. O último deles é o de upscale, ele vai forçar a ampliação mas pelo menos não quebra o layout por tamanhos de imagens muito pequenas que não são retornadas.

Ela tem esse mesmo problema de corte quando as imagens são menores que o tamanho indicado. Apenas com o upscale que a classe conseguiu fazer o redimensionamento em uma ampliação forçada.

![classe original](https://cloud.githubusercontent.com/assets/7620947/6022984/012e749a-aba8-11e4-90ea-859ca0878bb0.jpg)

Dei uma olhada no Odin e a classe que faz o processo de corte não recebe esses parâmentros, acredito que seria legal o Aqua Resizer permitir o retorno da imagem original em caso onde o upscale está desativado e o corte é maior que a base. Mas seria interessante ter esses parâmetros a mais no Odin també, já ajudaria bastante em alguns casos. Posso submeter essa sugestão no código? Gostaria de começar a ajudar o Odin, sou iniciante em web mas acho que posso tentar ajudar em algo.

![odin corte](https://cloud.githubusercontent.com/assets/7620947/6023113/00a193b2-aba9-11e4-9c70-64c2a75e98e1.jpg)

**Comment by fdaciuk** [comment]
Massa @rodrigo73! Vi isso em um projeto e apliquei somente nele.. achei que tinha enviado pro Odin =/
Mas pode mandar PR sim, não precisa nem pedir :D

**Comment by rodrigo73** [comment]
Não sei se está certo, segui as orientações e enviei la. Vlw pela ajuda pessoal. 
Problema aqui foi resolvido, abraços!

**Comment by felipescalice** [comment]
Eu iria fazer a msm pergunta, pois tive o msm problema recentemente e agradeço pela ajuda!

**Comment by adammacias** [comment]
Documentação atualizada [Redimensionando a imagem destacada (thumbnail)](https://github.com/wpbrasil/odin/wiki/Redimensionando-a-imagem-destacada-(thumbnail))
