### ISSUE TITLE
Verificar possibilidade de incluir o SmoothScroll.js

### ISSUE THREAD

**Issue by valeriosouza** [wpbrasil/odin#239]
Seria interessante usar o SmoothScroll.js pra aliviar a rolagem do tema em navegadores como o chrome.

**Comment by rafaelfunchal** [comment]
Isso para todo o site ou somente em one page sites?

**Comment by valeriosouza** [comment]
Acho que pra tudo, ou deixar um jeito da pessoa escolher ativar ou não

**Comment by fdaciuk** [comment]
Acho que tem isso pra alguns scripts, não? Pra selecionar qual vc quer ativar.. daria pra fazer o mesmo :)
Boa @valeriosouza :dancer:

**Comment by claudiosmweb** [comment]
Sinceramente acho que realmente devemos evitar libs JS, como já fizemos removendo outras.
