### ISSUE TITLE
Uso do odin_pagination() com get_posts

### ISSUE THREAD

**Issue by rodrigo73** [wpbrasil/odin#240]
Bom dia pessoal, estou tentando utilizar a função que faz as paginações do odin, o meu tema possui um CPT de fotos e gostaria que ele fosse incluso na listagem da categoria, criei um get_posts mas não faço ideia se a paginação funciona nesse caso. Vi que um dos parâmetros da função é uma $query, mas vi também que a função pega algumas variáveis globais do loop. 

Não achei nada na wiki, abaixo segue a maneira que chamei a função. Alguém sabe se é possível?

![odin pag](https://cloud.githubusercontent.com/assets/7620947/6127528/2ce079ba-b113-11e4-9b1c-0409739eb1d8.jpg)

**Comment by rodrigo73** [comment]
Troquei o get posts por um filtro no pre_get_posts e estou usando o loop principal, mas posteriormente terei que usar em um local com vários loops, ainda seria de grande ajuda se a paginação funcionasse.

**Comment by leobaiano** [comment]
Já tentou trocar a `get_posts();` pela `WP_Query();`?

**Comment by claudiosmweb** [comment]
Troca para WP_Query() assim pode passar a query certa.
get_posts() é para trabalhar com dados, como arrays ou objetos e não para exibir conteúdo.

**Comment by rodrigo73** [comment]
Obrigado pessoal, o filtro que inseri para alterar o "post_type" da listagem de categorias resolveu bem,  posteriormente eu irei precisar de algo parecido em um shortcode, estou trabalhando com algumas galerias. não sei ao certo, mas o  WP_Query()  não altera as variáveis globais do loop? poderia ter algum problema com o uso dele dentro de outro loop?
