### ISSUE TITLE
Remover "if IE" do header

### ISSUE THREAD

**Issue by adammacias** [wpbrasil/odin#243]
Pessoal, o que acham de remover o código abaixo do `header`?
```html
<!--[if IE 7]>
<html class="no-js ie ie7 lt-ie9 lt-ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="no-js ie ie8 lt-ie9" <?php language_attributes(); ?>>
<![endif]-->
<!--[if !(IE 7) | !(IE 8) ]><!-->
<html class="no-js" <?php language_attributes(); ?>>
<!--<![endif]-->
```
e deixar apenas:
```html
<html class="no-js" <?php language_attributes(); ?>>
```
Afinal de contas, acredito que assim como eu, a maioria de vocês, se não todos, não usa com frequência essas classes para IE8 muito menos para IE7. Mesmo se for usar, é mais comodo uma pessoa inserir este código do que vinte precisar remover-lo. Nem o thema **Twenty_Fifteen** está usando mais isso. :yum: 

> Less is More

**Comment by fdaciuk** [comment]
:+1: 
Boa! Acho que não precisa mais disso também :)

**Comment by adammacias** [comment]
PR feito! =) Também removi `<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />`. 

Antes fiz uma pesquisa  para saber se outros temas, como **Twenty_Fifteen** e **_s**, estão usando esse hack também e não estão! Acredito que seja pelo mesmo motivo, IE 7, 8 está morrendo de vez! :dancers:
