### ISSUE TITLE
Alguém usa o Koala para compilar SASS aqui ? 

### ISSUE THREAD

**Issue by valdirljr** [wpbrasil/odin#245]
Olá.

Alguém usa Koala para compilar aqui? Sempre que tento configurar não funciona. Cheguei a abrir uma issue no repo deles mas nada feito. 
Sempre dá erro  do compass
- - - - - - - - - - - - 
D:\wamp\www\agencia14.com.br\wp-content\themes\agencia14news\assets\sass\style.scss
Error: File to import not found or unreadable: compass/css3.
       Load path: D:/wamp/www/agencia14.com.br/wp-content/themes/agencia14news/assets/sass
        on line 6 of D:/wamp/www/agencia14.com.br/wp-content/themes/agencia14news/assets/sass/_config.scss
        from line 7 of D:\wamp\www\agencia14.com.br\wp-content\themes\agencia14news\assets\sass\style.scss
  Use --trace for backtrace.
- - - - - - - - - - - -

**Comment by rafaelfunchal** [comment]
Você já tem o Compass devidamente instalado?

**Comment by adammacias** [comment]
@valdirljr conseguiu com a dica do @rafaehlers?

**Comment by claudiosmweb** [comment]
Precisa instalar o compass com esse Koala.

**Comment by valdirljr** [comment]
Galera, instalei o Compass e tudo mais, tentei com varios compiladores, nada ia. Daí copiei a pasta do compass para dentro do projeto e foi de boa. 
Preciso migrar para linux logo. Facilitará minha vida. 
Obrigado pela força!
