### ISSUE TITLE
Usar posts relacionados com Odin

### ISSUE THREAD

**Issue by luhciano** [wpbrasil/odin#246]
Pessoal, estou achando sensacional o Odin, porem me deparei com um problema.
Preciso deixa o tamanho dos posts relacionados dentro do single com tamanho padrão fixo. 

Alguém saberia como mudar? sei que na no arquivo helper.php tem lá o functions com nome de  odin_related_posts .. só que não entendi como mudar o tamanho! 

Helpe pliss!!

**Comment by leobaiano** [comment]
@luhciano o que você quer dizer com "tamanho padrão fixo"? Você quer definir um tamanho fixo para a DIV onde os posts relacionados aparecem? Se for isso veja que a DIV tem um ID chamado related-post e você pode alterar o CSS dela.

**Comment by luhciano** [comment]
não testei fixa o tamanho da div. irei testa-lo! Obrigado pelo o Help!

**Comment by leobaiano** [comment]
@luhciano posso fechar a issue?

**Comment by luhciano** [comment]
sim!
