### ISSUE TITLE
Adicionar CATEGORIA em um módulo

### ISSUE THREAD

**Issue by AlyssonIdeagi** [wpbrasil/odin#247]
Pessoal criei um Módulo de Cursos com o ODIN e estou querendo adicionar nele as CATEGORIAS igual a categoria de um post de notícias do wordpress exemplo! :p 

Código abaixo:

<?php 
function odin_cursos_cpt() {
    $cursos = new Odin_Post_Type('Cursos','cursos');
    $cursos->set_labels(
        array('menu_name' => __( 'Cursos', 'odin' ))
        );

    $cursos->set_arguments(
        array(
            'supports' => array( 'title', 'editor' ),
            'register_meta_box_cb'   => 'cursos_metabox'
            )
        );
}

add_action( 'init', 'odin_cursos_cpt', 1 );

function cursos_metabox() {
    $cursos = new Odin_Metabox(
        'cursos', // Slug/ID of the Metabox (Required)
        'Campos Extras', // Metabox name (Required)
        'cursos', // Slug of Post Type (Optional)
        'normal', // Context (options: normal, advanced, or side) (Optional)
        'high', // Priority (options: high, core, default or low) (Optional)
        );

    $cursos->set_fields(
        array(
            // Textarea Field.
            array(
                'id'          => 'resumo', // Required
                'label'       => __( 'Resumo', 'odin' ), // Required
                'type'        => 'textarea', // Required
                'attributes'  => array( // Optional (html input elements)
                    'placeholder' => __( 'Resumo' )
                    ),
                // 'default'  => 'Default text', // Optional
                'description' => __( 'Escreva um resumo para a chamada', 'odin' ) // Optional
                ),

            // Image field.
            array(
                'id'          => 'destaque', // Required
                'label'       => __( 'Imagem', 'odin' ), // Required
                'type'        => 'image', // Required
                // 'default'     => '', // Optional (image attachment id)
                'description' => __( 'Escolha uma imagem destaque', 'odin' ), // Optional
                ),
            )
);
}
add_action( 'init', 'cursos_metabox', 1 );
?>

Agradeço a ajuda desde já. Abraços

**Comment by leobaiano** [comment]
@AlyssonIdeagi  o que você quer é criar uma taxonomia, da uma olhada na documentação: https://github.com/wpbrasil/odin/wiki/Classe-Odin_Taxonomy

**Comment by AlyssonIdeagi** [comment]
seria isso @leobaiano ?

http://pastebin.com/i4TnLcNy

Só faltou ler de baixo pra cima essa documentação e não consegui entender =/ 
Sabe o menu que tem:
- Listar
- Adicionar
Eu queria que aparecesse o CATEGORIAS e la criaria as categorias. Funciona assim?

Obrigado pela atenção abraços

**Comment by leobaiano** [comment]
`$cursos = new Odin_Taxonomy(
        'Categoria de Cursos', // Nome (Singular) da nova Taxonomia.
        'categoria', // Slug do Taxonomia.
        'post' // Nome do tipo de conteúdo que a taxonomia irá fazer parte.
    );`

Onde tem post você deve colocar o CPT que criou, dessa forma ai ele criou a taxonamy no Post mesmo, pode ir em Posts que deve tá aparecendo lá. No seu caso coloque cursos, que é o slug do CPT de cursos, no lugar de post.

**Comment by AlyssonIdeagi** [comment]
Pow vei não sei nem como agradecer :D Obrigado mesmo deu super certo. 
Vou ver agora como faço pra chamar na frente. Vlw @leobaiano Abraços

**Comment by leobaiano** [comment]
Bom saber que resolveu, vou fechar a issue, abração!
