### ISSUE TITLE
Listar categorias

### ISSUE THREAD

**Issue by AlyssonIdeagi** [wpbrasil/odin#248]
Pessoal to criando um SHORTCODE pra mostrar as CATEGORIAS cadastradas, mas não sei como chamar na frente =/ 

Já consegui criar a categoria no módulo através da ajuda do amigo @leobaiano.
Esse é o módulo: http://pastebin.com/1BwAar3L
Faltando apenas chamar na frente ;) Fico grato pela ajuda de todos. 

Meu sócio que era fera nisso saiu da empresa, ai sobrou pra mim rsrs ainda bem que aprendi algumas coisas antes dele sair. Vlw

**Comment by AlyssonIdeagi** [comment]
Consegui listar as categorias do módulo, falta apenas puxar o link correto que liste os cursos daquela determinada categoria. Ajuda?

Código que usei para lista: http://pastebin.com/H3evkrNt

**Comment by everaldomatias** [comment]
Ele está retornando algum erro, como comentou que falta 'pixar o link correto'?

Tenta com esse código: http://pastebin.com/BdZsAWHP
Testei aqui, com posts e a category padrão e funcionou perfeitamente.

**Comment by adammacias** [comment]
Você lembrou de setar o  `$type` do post como *cursos*?

**Comment by AlyssonIdeagi** [comment]
Sim sim @adammacias. Ele mostra a categoria mas não retorna nenhum link @everaldomatias 
Eu queria que quando clicasse na categoria o mesmo direcionasse para outra página listando os cursos daquela categoria. Obrigado pela atenção ;)

Como fica o link no html: <a href="" title="Category Name">Gestão</a>

**Comment by everaldomatias** [comment]
@AlyssonIdeagi em "Gestão" você tentou mandar algum link de exemplo? Ele está retornando para essa mesma página no Github.

**Comment by AlyssonIdeagi** [comment]
Exatamente isso @everaldomatias , aqui no meu local acontece a mesma coisa, como ta sem nenhum caminho o link retorna para a mesma página!

**Comment by everaldomatias** [comment]
Cola aqui, diretamente, o HTML gerado por esse trecho de código por favor?

**Comment by AlyssonIdeagi** [comment]
Agora :D

<ul class="category_list">   														
<li><a href="" title="Category Name">Beleza</a></li>						
<li><a href="" title="Category Name">Gestão</a></li>
</ul>

**Comment by everaldomatias** [comment]
Iche, acho que o Github tá interpretando seu HTML, é isso, rsrs.

**Comment by AlyssonIdeagi** [comment]
kkkk ta sim, vou mandar no pastebin

http://pastebin.com/3UPWc9it

**Comment by everaldomatias** [comment]
Ótimo.

Com o trecho de código que mandei, não funcionou?

Tente mudar os argumentos, apenas para testar com os posts, faça assim: 

$args = array(
        'type'                     => 'post',
        'child_of'                 => 0,
        'parent'                   => '',
        'orderby'                  => 'name',
        'order'                    => 'ASC',
        'taxonomy'                 => 'category',
        'pad_counts'               => false
);

E certifique-se de ter pelo menos uma categoria cadastrada nos posts.

Veja se isso funciona e volta ai..

**Comment by AlyssonIdeagi** [comment]
Mesmo jeito =/ Ele mostra as categorias cadastradas, mas não retorna nenhum link.

**Comment by everaldomatias** [comment]
Usando esse código: http://pastebin.com/BdZsAWHP

Na linha 14 coloque isso:

echo $category->term_id;

E entre a linha 15 e 16, coloque isso:

echo $category_link;

E me diga o que ele retorna.

**Comment by leobaiano** [comment]
@allysonsouza você quer pegar o link dos termos de uma taxonomia, mas está usando a função que retorna o link das categorias padrão do tipo post, por isso não está funcionando.

No href substitua a função `get_category_link();` pela função `get_term_link();` que deve resolver. Observe que o parametro passado é diferente, ao invés de passar o ID você vai passar o termo completo, veja exemplo na documentação.

http://codex.wordpress.org/Function_Reference/get_term_link

**Comment by AlyssonIdeagi** [comment]
@everaldomatias retornou os ID das categorias.


4
Beleza
2
Gestão

Vou testar isso que você falou @leobaiano vlw

**Comment by everaldomatias** [comment]
Exato, segue o exemplo do @leobaiano mesmo, é mais coerente.

**Comment by AlyssonIdeagi** [comment]
É isso mesmo @leobaiano! Só que deixa eu te aperriar mais um pouco rsrs
Pelo o que eu entendi, o arquivo que ele mostra logo após é o taxonomy.php né isso?
Teria como quando eu clicasse na categoria ele me mostrar uma listagem (que pode até ser criada em uma page-categoria.php)? 

Eu usava assim antigamente para listar os cursos sem categoria.
http://pastebin.com/0C3H0jke

**Comment by AlyssonIdeagi** [comment]
Obrigado pela ajuda @everaldomatias ;)

**Comment by everaldomatias** [comment]
@AlyssonIdeagi disponha.

Sobre essa listagem, deixa eu ver se entendi, você quer que ao clicar em 'Gestão', ele exiba uma listagem dos posts dessa categoria? Apenas o título e um link para ver o post, é isso?

Se for isso você pode duplicar o taxonomy.php e renomear para taxonomy-{$type}.php (substitua $type pelo nome do CPT) e edite esse arquivo como deseja.

**Comment by AlyssonIdeagi** [comment]
Vou tentar isso @everaldomatias vlw.

**Comment by leobaiano** [comment]
@allysonsouza você fazia errado antes.... Para mostrar os posts das categorias é só criar um arquivo category.php e usar o loop padrão, você além de criar uma página usou `query_posts();` para modificar o loop padrão e mostrar os posts da categoria... faz isso não cara, nunca use `query_posts();` e sempre que possível opte pelo padrão do WP.

Para mostrar os posts da taxonomia é só criar o taxonomy.php, se quiser ser mais especifico cria o taxonomy-slug.php, no seu caso ficaria taxonomy-categoria.php e se quiser ser mais especifico ainda você ainda pode criar o taxonomy-slug_da_taxonomia-slug_do_termo.php um exemplo do seu caso seria o arquivo taxonomy-categoria-beleza.php que seria o template para a página com a lista de posts do termo beleza.

Para saber mais sobre a hierarquia de arquivos veja a documentação em: http://codex.wordpress.org/pt-br:Hierarquia_de_Modelos_WordPress

Agora se ligue, aqui é o repositório do Odin, é para dúvidas do Odin, se quiser tirar dúvidas de WordPress, como essa, use um dos canais do GUWP (http://guwp.org) (grupo facebook, lista de discussão por e-mail, g+).

**Comment by AlyssonIdeagi** [comment]
Mas todos os meus módulos, shortcodes e afins foram criados através do ODIN. Por isso vim pedir ajuda a vocês. Mas vou analisar aqui. Vlw @leobaiano obrigado pela atenção

**Comment by AlyssonIdeagi** [comment]
Só me tira mais uma dúvida, o taxonomy é aberto em que página? Por que pelo o que eu vi aqui, ele é jogado em alguma outra página né isso? Ou estou errado? Abraços

**Comment by leobaiano** [comment]
@everaldomatias onde você viu esse template taxonomy-CPT.php? Isso não existe... é taxonomy-slug_taxonomy.php ou taxonomy-slug_taxonomy-slug_termo.php ou só taxonomy.php... Os CPT tem a nomeclatura archive, no caso para listar os posts de um CPT você pode criar o archive.php ou o archive-slug_do_cpt.php.

É legal que queira ajudar e a comunidade precisa disso, mas tenha cuidado para não ensinar errado cara, além de atrapalhar o @AlyssonIdeagi você pode atrapalhar outras pessoas que achem esse tópico através de uma busca.

**Comment by leobaiano** [comment]
@AlyssonIdeagi quando você pergunta em que página ele é aberto quer saber qual a URL ou qual arquivo ele utiliza como template?

**Comment by AlyssonIdeagi** [comment]
Seria o arquivo @leobaiano. Mas acho que consegui o que eu queria :+1: Obrigado pela ajuda de todos, é difícil achar pessoas como vocês que ajudam sem pro algum. Vlw mesmo ;)

**Comment by everaldomatias** [comment]
Pois é @leobaiano, escrevi errado, @AlyssonIdeagi o correto é taxonomy-slug_taxonomy.php

**Comment by AlyssonIdeagi** [comment]
Tranquilo @everaldomatias . Obrigado pela ajuda de todos :D
