### ISSUE TITLE
Menu não aparece na página de categoria!

### ISSUE THREAD

**Issue by luhciano** [wpbrasil/odin#249]
Olá pessoal, o meu menu não está aparecendo na página de categoria! alguém saberia me dizer porque?

Meu codigo do header onde lista o menu:

	<section class="container">
		<div class="row">
			<nav class="navbar navbar-default menuTop" id="nav" role="navigation">
			
            <?php
            wp_nav_menu( array(
                'menu'              => 'category-menu',
                'theme_location'    => 'category-menu',
                'depth'             => 2,
                'container'         => 'div',
                'container_class'   => 'collapse navbar-collapse ',
        		'container_id'      => 'bs-example-navbar-collapse-1',
                'menu_class'        => 'nav navbar-nav',
                'fallback_cb'       => 'Odin_Bootstrap_Nav_Walker::fallback',
                'walker'            => new Odin_Bootstrap_Nav_Walker() )
            );
        ?>
</nav>
		</div>
	</section>

e meu codigo do functions onde registra o menu:

require_once ('class-bootstrap-nav.php');
add_action( 'init', 'tediado_register_my_menus' );
	
	function tediado_register_my_menus() {
  register_nav_menus(
    array(
      'footer-menu' => __( 'Footer Menu' ),
      'category-menu' => __( 'Category Menu' )
    )
  );
}

alguém me da um help?

**Comment by adammacias** [comment]
É só na página de categoria? 

Você já verificou se está imprimido o HTML? As vezes está e é alguma coisa no CSS que faz com que o menu fique oculto...

**Comment by luhciano** [comment]
é so na página de category .. e não está imprimindo HTML não aparece nada! @adammacias

**Comment by everaldomatias** [comment]
Em outras páginas ele roda normal?

Veja de usar underline no ID dos menus, assim: category_menu e também tente deixar o argumento 'menu' em branco.

**Comment by claudiosmweb** [comment]
E é chamado esse menu na página de categoria?
Alias, não me parece ser um issue com o Odin e sim simplesmente PHP ou HTML.
Fechando.

**Comment by luhciano** [comment]
@claudiosmweb é chamado sim na página de categoria, alies em todas as páginas, mais na de categoria não mostra! na página normal mostra, nos pots mostras, mais em categoria não!

**Comment by RafaelFunchal** [comment]
@ernandesferreira , ajudará bastante se você mandar os códigos que está usando para criar o menu e como está sendo inserido no template chamado na página category.

**Comment by ernandesferreira** [comment]
@RafaelFunchal como estou usando o odin, eu não costumo mexer na chamada original, o menu está sendo chamado no header...

<div id="main-navigation" class="navbar navbar-default">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-navigation">
						<span class="sr-only"><?php _e( 'Toggle navigation', 'odin' ); ?></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						
					</div>
					<nav class="collapse navbar-collapse navbar-main-navigation" role="navigation">
						<?php
							wp_nav_menu(
								array(
									'theme_location' => 'main-menu',
									'depth'          => 2,
									'container'      => true,
									'menu_class'     => 'nav navbar-nav',
									'fallback_cb'    => 'Odin_Bootstrap_Nav_Walker::fallback',
									'walker'         => new Odin_Bootstrap_Nav_Walker()
								)
							);
						?>
					</nav>

e na page category está sendo chamado com o get_header() , pois é o menu principal que não esta aparecendo.

**Comment by RafaelFunchal** [comment]
> pois é o menu principal que não esta aparecendo.

@ernandesferreira, isso significa que seu problema é outro.

Por favor, crie um outro issue para não misturar os assuntos.

**Comment by ernandesferreira** [comment]
@RafaelFunchal resolvi aqui.. acontece que uma função que eu peguei do @leobaiano estava causando isso.. a função é essa 

add_filter(‘pre_get_posts’, ‘add_post_type_in_taxonomies_list’);
function add_post_type_in_taxonomies_list( $lista ) {
if( is_category() || is_tag()) {
$post_type = get_query_var( ‘post_type’ );

if ($post_type)
$post_type = $post_type;
else
$post_type = array( ‘post’,’treinamento’ );
$lista->set( ‘post_type’, $post_type );
return $lista;
}
}

Sendo que não percebi que no segundo if estava faltando as chaves.

**Comment by RafaelFunchal** [comment]
É sempre bom dar uma conferida em código copiado mesmo :-)
