### ISSUE TITLE
ID Main duplicado em page.php e single.php

### ISSUE THREAD

**Issue by brunoguimaraes** [wpbrasil/odin#250]
Olá galera,

percebi que no header.php temos uma div com ID "main" na linha 83, e nos templates de paginas internas page.php, single.php, archive.php entre outros temos elementos <main> com IDs "main".

Isso tem algum motivo especifico é algo que deveria ser corrigido?

**Comment by claudiosmweb** [comment]
Hey galera: https://github.com/wpbrasil/odin/search?p=1&q=id%3D%22main%22&utf8=%E2%9C%93
Agradeço quem pode ajudar.

**Comment by leobaiano** [comment]
Posso fazer isso, mas o que vocês acham melhor:

1 - Mudar o ID no header.php
2 - Mudar o ID main em todos os outros arquivos
3 - Simplesmente remover o ID dos outros arquivos já que a tag HTML <main> já da a semantica necessária para o bloco

???

**Comment by claudiosmweb** [comment]
Na verdade acredito que o melhor é trocar os de dentro mesmo, por `main-content` ou algo assim.
