### ISSUE TITLE
Votação para agilizar merge de pull requests

### ISSUE THREAD

**Issue by fdaciuk** [wpbrasil/odin#253]
Fala galera! Queria sugerir algo pra que possamos agilizar os pull requests aqui, visto que alguns ficam bastante tempo aguardando que alguém aprove.

No [cerebro](https://github.com/cerebrobr/cerebro/issues/16), nós estamos fazendo da seguinte forma:

* Pessoa envia um pull request;
* Algum colaborador do projeto analisa o código, se é válido ou não, e vota: **+1** ou **-1**.
* Se tiver 2 votos positivos (todos os **+1** somados com os **-1**), pode ser feito o merge do _pull request_.

A ideia para votação negativa é a seguinte:
Ao analisar o código, se tiver alguma coisa fora dos padrões usados no **Odin**, a pessoa que viu o problema comenta na linha do código com **-1** e explica o motivo do voto.

No final, essa pessoa pode dar o voto de **+1**, visto que, ao resolver o problema, o **-1** é eliminado.

O que acham?

cc. @wpbrasil/developers @wpbrasil/owners

**Comment by nandomoreiraweb** [comment]
+1

**Comment by nandomoreiraweb** [comment]
:+1:

**Comment by adammacias** [comment]
:+1: haha aprovado. Mas tipo, dois não é pouco? Quer dizer, duas pessoas aprovam em 5 min e nem dá chance de outras pessoas darem opinião =D Poderia ter um tempo minimo para o merge. Que tal? Tipo 1 ou 2 dias, se ninguém contestar, já era, mete bala :gun:

**Comment by claudiosmweb** [comment]
Vocês são muito viados xD
Só questão de bom senso e ai OK dar merge, não precisa esperar por mim ou por alguém.

**Comment by fdaciuk** [comment]
Mas acho que não é nem questão de dar tempo @adammacias.. se tiver 2 ou 3 conferências já tá legal xD

Mas o problema é bem esse @claudiosmweb.. o negócio fica muitas vezes parado porque a galera tem medo de dar merge no projeto até você vir aqui e fazer isso :stuck_out_tongue_winking_eye: 

Também acho zuado dar merge direto.. pode acabar passando algo que dê problema depois e ninguém viu, porque o cara que fez o PR já dá merge sozinho.

Enfim, a ideia seria agilizar, mas manter o negócio funcionando xD

**Comment by espellcaste** [comment]
Não participo muito, mas vocês não tem um prazo para adicionar funcionalidades? Como o WP, BP  e bbPress tem?

**Comment by adammacias** [comment]
@fdaciuk mas o negócio funciona aqui haha, os PR que estão pendente a mais tempo o próprio cara quem fez que deixou de lado.

**Comment by fdaciuk** [comment]
Sim, o PR é feito por quem enviou. É isso que eu tô dizendo: o PR deveria ser feito sempre por outra pessoa, :smile:

**Comment by valeriosouza** [comment]
Acho que podia criar um outro nível só com essa funcionalidade. Um grupo de 4 pessoas para fazer mercê.

**Comment by leobaiano** [comment]
Acho ruim que a mesma pessoa que fez o pr faça o merge na master, talvez nem precise de votação só que alguém dê uma olhada antes de dar merge pra garantir que o autor não se passou em algo. Sem muita frescura, até porque qualquer coisa só voltar um commit né.

**Comment by fdaciuk** [comment]
Exato, pode ser também @leobaiano! A ideia de votar é só pra garantir que alguém viu que a alteração realmente não vai quebrar nada.. quem vota coloca o seu na reta, haha xD

**Comment by rafaelfunchal** [comment]
:+1:

**Comment by adammacias** [comment]
Pessoal, então ficou decidido +2 o PR fica liberado! Podemos fechar esse tópico?
