### ISSUE TITLE
Adicionar Sourcemaps

### ISSUE THREAD

**Issue by adammacias** [wpbrasil/odin#256]
Eu li o artigo [Sourcemaps - Debugando JS e CSS minificados](http://blog.da2k.com.br/2015/02/21/sourcemaps-debugando-js-e-css-minificados/) do @fdaciuk , por sinal muito bom, e achei que ficaria legal adicionar isso no Odin :smile: testei aqui e deu certo o debug, inclusive o [grunt-contrib-uglify](https://github.com/gruntjs/grunt-contrib-uglify#sourcemap) já tem esse recurso, basta ativar via `Gruntfile.js`.

Com isso podemos deixar o arquivo `main.min.js` já carregando por *default* e comentar o resto, pois acredito que a parte tensa na hora do desenvolvimento era justamente esse debug, com sourcemaps esse problema é resolvido! :laughing: 

 O que acham?

**Comment by allysonsouza** [comment]
Curti, não conhecia Sourcemaps!

**Comment by fdaciuk** [comment]
Acho uma boa.. até porque ajuda a debugar :)
+1

**Comment by adammacias** [comment]
Bacana, fiz um PR.

**Comment by claudiosmweb** [comment]
Na verdade no WordPress não seria tão boa ideia fazer isso.

Seria melhor trocar para:

```php
$suffix = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : '.min';
wp_enqueue_script( 'odin-main', $template_url . '/assets/js/main' . $suffix . '.js', array(), null, true );
```

Desta forma enquanto esta desenvolvendo você consegue configurar corretamente o seu ambiente com o modo de debug do WordPress.

**Comment by fdaciuk** [comment]
A solução do @claudiosmweb é ainda melhor mesmo.. assim não tem o custo de gerar os sourcemaps :)

**Comment by adammacias** [comment]
Acredito que o *sourcemap* é mais útil para o pessoal que trabalha com **Grunt** mas como sabemos que é a minoria, esse modo do @claudiosmweb se adequá melhor mesmo! :+1: Deem uma olhada no PR agora por favor =)
