### ISSUE TITLE
Chamada de função

### ISSUE THREAD

**Issue by tiagosousaweb** [wpbrasil/odin#257]
Olá pessoal, não estou conseguindo implementar (chamar) a função que captura o texto digitado pelo usuário no meu tema.
Para entender melhor: http://prntscr.com/68et1p

**Comment by leobaiano** [comment]
Faltou dar echo para imprimir o valor.

**Comment by tiagosousaweb** [comment]
Ok. Acho que isso é mais sobre php mesmo do que o próprio framework neh. Valeuzão ae. 
Se tiver como me mostrar aí como fica, agradeço, não manjo muito de php.

**Comment by leobaiano** [comment]
`echo $var`

Sendo que `$var` é o nome da variável cujo valor você deseja imprimir.

**Comment by tiagosousaweb** [comment]
Veleu...
