### ISSUE TITLE
Página de showcase

### ISSUE THREAD

**Issue by jrstylle** [wpbrasil/odin#261]
Seria interessante o site do odin ter uma página com os sites que já foram desenvolvidos com ele.

**Comment by allysonsouza** [comment]
+1

**Comment by jrstylle** [comment]
Acredito que com exemplos de sites desenvolvidos com o odin, e as pessoas, principalmente as menos experientes teriam uma maior noção do que o odin é capaz de fazer, assim iria aumentar a adesão do framework e claro, isso ajudaria no desenvolvimento do ferramenta.

**Comment by fdaciuk** [comment]
Tinhamos um lugar pra isso no site antigo, mas acho que não chegou a ser publicado nenhum. A ideia é ótima! Talvez podemos usar o Mailchimp para receber os links, ou até por aqui mesmo, criando issues :)
:+1:

**Comment by allysonsouza** [comment]
Não sei se seria ruim, mas talvez incluir uma listagem no Readme, ou então algum item da wiki.
Ou como o @fdaciuk disse, com issues, podíamos criar uma nova label: "madewithodin", "referências", algo do tipo.

**Comment by everaldomatias** [comment]
+1

Acho a ideia animal, só acho meio sensível ser apenas por link's, pois isso vai gerar a demanda de sempre validar quais links ainda continuam sendo em Odin ou mesmo deixem de existir.

Poderia ser algo com thumbs como primeira instância caso o link se quebre como comentei acima.

**Comment by allysonsouza** [comment]
Sendo em issues a própria pessoa consegue facilmente adicionar os prints no comentário. Só não fica aquele showcase em vários thumbs, pro pessoal ver em uma tacada só, isso acho que o ideal seria no site...

**Comment by everaldomatias** [comment]
É isso @allysonsouza legal.

**Comment by adammacias** [comment]
Acho que já recebemos alguns cases quando o site ainda era o outro.

Acredito que seria melhor separar em dois repositórios: **Odin** para o *theme* e **Odin Expo** para os *showcase*, se não em alguns meses teria mais *issues* de cases do que outra coisa.

Referencia: Podemos forkar o http://beautifulopen.com/ e fazer com *Jekyll* mesmo.

:neckbeard:

**Comment by rafaelfunchal** [comment]
Concordo com a ideia do @adammacias. Um repositório diferente para o showcase seria o ideal

**Comment by allysonsouza** [comment]
Não dá para incluir uma sessão, antes ou depois dos colaboradores, com o showcase no http://wpod.in/? E ai o pessoal da PR nesse branch, já adicionando o seu projeto na página?

**Comment by adammacias** [comment]
@allysonsouza acho que seria interessante como você disse, mas uma sessão apenas com uns 4 *thumbnails* dos cases em "destaque" e um botão enviando para o outro repositório **Odin Expo** :D Os quatro cases em destaque dá para gente abrir um *issue* aqui para "votação" dos melhores e atualizar uma vez por mês... Já os PR de novos cases poderiam ser enviado pro **Odin Expo**.

**Comment by allysonsouza** [comment]
Não sei @adammacias, era para ser algo simples e acho que estamos complicando no final das contas... Parece muita volta para algo que podia ser um .txt com links.

Essas votações vão ficar exigindo "esforço" do pessoal, além das atualizações, e etc., qual a preocupação em ter todo esse filtro na seleção?

Talvez fosse melhor criar o "Odin Expo" e só manter no readme mesmo, ai quem quiser inserir coloca 1 thumb (em um tamanho padrão) + link + nome do site + desenvolvedor/empresa em ordem alfabética (nome do site). Similar aos documentos da WordPress Brasil no FB.

**Comment by adammacias** [comment]
Beleza, a votação foi só para o destaques, mas foi só uma sugestão.

@allysonsouza Podemos fazer então o **Odin Expo** como você disse, mas ainda acho que seria legal ter algo visual usando Jekyll igual o http://beautifulopen.com/ =) 

@rafaelfunchal pode criar um repositório chamado "Odin Expo" aí por favor? Não tenho permissão para isso. Assim já fecha essa *issue* :)

**Comment by rafaelfunchal** [comment]
Repositório criado, galera! https://github.com/wpbrasil/odin-expo

Vamos levar esse papo pra lá :-)

**Comment by claudiosmweb** [comment]
Precisamos disso não jovens, só criar na Wiki como uma porrada de projeto já faz xD

**Comment by claudiosmweb** [comment]
Alias, da para fazer também no gh-pages aqui.
Exemplo desse http://beautifulopen.com/, precisamos de um json com nome do site, descrição, foto e URL.
E ai esta tudo pronto, só fazer um parser e criar usando Jekyll ou qualquer outra coisa.

**Comment by adammacias** [comment]
Pronto pessoal, o que acham? http://adammacias.github.io/odin-expo/
@rafaelfunchal abusando novamente da sua hospitalidade, cria o *branch gh-pages* lá no **odin-expo** para que eu consiga dar um PR, e já seta ele como *branch* padrão *please*. :dancers:

**Comment by allysonsouza** [comment]
@adammacias eu não manjo das pages do github, mas e isso que o @claudiosmweb disse: "Alias, da para fazer também no gh-pages aqui." - Precisamos mesmo de outro repositório?

**Comment by rafaelfunchal** [comment]
Acho que fica mais organizado com outro repositório

**Comment by claudiosmweb** [comment]
Por que outro repo só para isso?
Da para colocar tudo no mesmo.
Trocar o template do site que é feito em HTML puro por Jekyll também.

**Comment by rafaelfunchal** [comment]
Eu sei, mas repo diferente evitaria dor de cabeça com galera mandando pro branch errado. Só questão de organização mesmo.

**Comment by adammacias** [comment]
Eu compartilho da mesma opinião do @rafaelfunchal xD iria ficar desorganizado, não a questão do site, mas sim dos PRs e Issues.

Funchal, nós podemos então fazer um *test drive* aqui, se ficar ruim a gente migra para outro, se não deixa quieto.

**Comment by rafaelfunchal** [comment]
Por mim beleza.

**Comment by AlecBeltrami** [comment]
Abaixo o case desenvolvido com o Odin, Site encontrado no http://cssreel.com/.

http://www.redbullbrasil.com.br/

**Comment by claudiosmweb** [comment]
@adammacias agora que o Red Bull do Brasil esta usando Odin, realmente vale apena ter um showcase, nem que estático na nossa página inicial mesmo.
Tem a moral de fazer?

**Comment by adammacias** [comment]
@claudiosmweb foi mal, esqueci de te avisar, fiz o [showcase do Odin](https://github.com/wpbrasil/odin-expo/pull/2), acho que já podemos essa issue.
