### ISSUE TITLE
Odin Custom Post Status

### ISSUE THREAD

**Issue by randsonjs** [wpbrasil/odin#262]
Pessoal,

recentemente fiz uma aplicação em wordpress. Ela usa os status do post para fazer filtros. Precisei olhar na documentação e fazer uso da função `register_post_status()`.

Talvez seria ideal deixar como uma classe para o Odin. Eu fiz um esboço de uma classe [aqui](https://gist.github.com/randsonjs/b16834e69ffebb4169e7). Ainda estou terminando. Mas adianto que sem a classe funciona tudo perfeitamente. Faço uso dos filtros ok. Tudo perfeito *-*

Queria saber a opinião de vocês para deixar mais uma classe disponivel para a galera que usa o Odin. No caso, a criação de Custom Post Status.

E ai, o que acham?

**Comment by allysonsouza** [comment]
Legal, mas eu acho que é um recurso mais específico, que é muito bom que exista, mas não seja algo a ser adicionado no core para a maioria dos projetos não utilizar. (ainda que seja uma classe, com 120 linhas apenas, 3KB | e ainda que tenham outras coisas que ninguém usa em todo projeto, etc...)

**Comment by randsonjs** [comment]
Isso é uma questão relevante e irrelevante ao mesmo tempo @allysonsouza. 

No próprio `functions.php` do odin tem isso:

```php
require_once get_template_directory() . '/core/classes/class-bootstrap-nav.php';
require_once get_template_directory() . '/core/classes/class-shortcodes.php';
require_once get_template_directory() . '/core/classes/class-thumbnail-resizer.php';
// require_once get_template_directory() . '/core/classes/class-theme-options.php';
// require_once get_template_directory() . '/core/classes/class-options-helper.php';
// require_once get_template_directory() . '/core/classes/class-post-type.php';
// require_once get_template_directory() . '/core/classes/class-taxonomy.php';
// require_once get_template_directory() . '/core/classes/class-metabox.php';
// require_once get_template_directory() . '/core/classes/abstracts/abstract-front-end-form.php';
// require_once get_template_directory() . '/core/classes/class-contact-form.php';
// require_once get_template_directory() . '/core/classes/class-post-form.php';
// require_once get_template_directory() . '/core/classes/class-user-meta.php';
```

Onde tem classes que não serão usadas em "todos os projetos". Temos frameworks também que a maioria dos projetos não usam ele completamente.

Eu acharia o máximo o Odin disponibilizar essa classe para utilizar. Assim como tem a classe `user-meta.php`. 

A própria classe `user-meta.php` é exemplo. Nem todos os projetos usam ela, mas está disponivel para o projeto que precisar.

**Comment by allysonsouza** [comment]
"e ainda que tenham outras coisas que ninguém usa em todo projeto, etc..." - foi minha opinião, o projeto é open source, tá aqui a issue para os demais comentarem! : )

**Comment by randsonjs** [comment]
Tranquilo hehe

Vamos esperar a galera pra ver que acham! :)

**Comment by matheusgimenez** [comment]
Acho útil e como o @randsonjs falou mesmo, colocando comentado não vai pesar na hora de rodar.

+1

**Comment by fdaciuk** [comment]
Acho válido @randsonjs :)
Essa sua classe já funciona?

**Comment by randsonjs** [comment]
Essa que está no gist não. Mas ela finalizada já está sendo usada em produção.

Vou terminar ela e envio como Pull Request!

**Comment by adammacias** [comment]
+1 
Só que também precisamos criar a documentação de como utiliza-la. :)

**Comment by claudiosmweb** [comment]
Fechado em favor de #266
