### ISSUE TITLE
Título Imagem Galeria de Fotos

### ISSUE THREAD

**Issue by AlyssonIdeagi** [wpbrasil/odin#267]
Boa tarde a todos, como faço pra puxar o TÍTULO de uma imagem?

Esse é o código que uso para chamar a imagem:

<?php 
    $args = array('post_type' => 'consultoria','posts_per_page' => 1,'order' => ASC);
    query_posts($args);
    if (have_posts()) :
      ?>
    <?php
    // Start the Loop.
    while ( have_posts() ) : the_post();
    global $post, $wpdb, $nggdb; 
    $galeria_de_fotos   = get_post_meta($post->ID, 'galeria_de_fotos', true);
    ?>
    <ul>
      <?php foreach ( explode( ',', $galeria_de_fotos ) as $image_id ){?>
      <?php $imageUrl = wp_get_attachment_image_src($image_id, 'full' ); ?>
      <li class="background1">
        <a href="<?php echo $imageUrl[0]; ?>" class="fancybox-button" rel="fancybox-button">
          <?php $resizer = Odin_Thumbnail_Resizer::get_instance();
          $image = $resizer->process($imageUrl[0], 185, 185, true, true ); ?>
          <?php $alt = get_image_tag($alt); ?>
          <?php echo '<img class="wp-image-thumb img-responsive imagem'.$i.' ' . sanitize_html_class( $class ) . '" src="' .$image. '" width="' .esc_attr( $width ) . '" height="' .esc_attr( $height ) . '" title="?"; ?>
        </a>
      </li>
      <?php } ?>
    </ul>

**Comment by AlyssonIdeagi** [comment]
<?php foreach ( explode( ',', $galeria_de_fotos ) as $image_id ){?>
      <?php $imageUrl = wp_get_attachment_image_src($image_id, 'full' ); ?>

          <?php $resizer = Odin_Thumbnail_Resizer::get_instance();
          $image = $resizer->process($imageUrl[0], 185, 185, true, true ); ?>
          <?php $alt = get_image_tag($alt); ?>
          <?php echo '<img class="wp-image-thumb img-responsive imagem'.$i.' ' . sanitize_html_class( $class ) . '" src="' .$image. '" width="' .esc_attr( $width ) . '" height="' .esc_attr( $height ) . '" alt="'$alt'" />'; ?>

      <?php } ?>

**Comment by allysonsouza** [comment]
Dá uma olhada nessa função do WordPress: http://codex.wordpress.org/Function_Reference/wp_prepare_attachment_for_js

Senão tem essa função, postada nesta discussão aqui, que deve servir: https://wordpress.org/ideas/topic/functions-to-get-an-attachments-caption-title-alt-description

```
function wp_get_attachment( $attachment_id ) {
	$attachment = get_post( $attachment_id );
	return array(
		'alt' => get_post_meta( $attachment->ID, '_wp_attachment_image_alt', true ),
		'caption' => $attachment->post_excerpt,
		'description' => $attachment->post_content,
		'href' => get_permalink( $attachment->ID ),
		'src' => $attachment->guid,
		'title' => $attachment->post_title
	);
}
```

**Comment by AlyssonIdeagi** [comment]
Mas isso se aplica no ODIN? Não teria alguma função já do odin pra isso não? Tipo, dentro dessa função que usei para chamar e redimensionar a imagem eu poderia chamar o titulo da mesma não?

Obrigado pela ajuda allysonsouza

**Comment by allysonsouza** [comment]
Não, nessa classe Odin_Thumbnail_Resizer ela se restringe ao que o seu nome diz, redimensionar imagens. A partir o ID que você possuí tem que utilizar os recursos do WordPress mesmo para acessar o título da imagem.

De nada :v:

**Comment by rafaelfunchal** [comment]
Sobre usar query_posts().

> Note: This function isn't meant to be used by plugins or themes. As explained later, there are better, more performant options to alter the main query. query_posts() is overly simplistic and problematic way to modify main query of a page by replacing it with new instance of the query. It is inefficient (re-runs SQL queries) and will outright fail in some circumstances (especially often when dealing with posts pagination). Any modern WP code should use more reliable methods, like making use of pre_get_posts hook, for this purpose.

http://codex.wordpress.org/Function_Reference/query_posts

**Comment by AlyssonIdeagi** [comment]
Por que o amigo fechou? Ainda não consegui resolver meu problema.

**Comment by AlyssonIdeagi** [comment]
Consegui resolver usando isso:

<?php $title_image = get_the_title($attach_id) ?>

**Comment by AlyssonIdeagi** [comment]
Obrigado allysonsouza pela ajuda abraços

**Comment by rafaelfunchal** [comment]
@AlyssonIdeagi fechei por que isso não é um problema do Odin.

Como o @allysonsouza disse anteriormente:
> A partir o ID que você possuí tem que utilizar os **recursos do WordPress** mesmo para acessar o título da imagem.

**Comment by allysonsouza** [comment]
@rafaelfunchal está certo, era uma dúvida de WordPress geral. E pode crer, get_the_title() serve já que attachment é um post type, vacilo meu propor soluções mirabolantes : P

**Comment by AlyssonIdeagi** [comment]
Certo @rafaelfunchal desculpe. Pois é @allysonsouza mas obrigado pela atenção. Abraços
