### ISSUE TITLE
Demo do Odin fora do ar por tempo indeterminado

### ISSUE THREAD

**Issue by claudiosmweb** [wpbrasil/odin#268]
Eu matei o demo do Odin.
Quando rolar tempo eu coloco no ar de novo, mas sei lá se precisa mesmo de demo.

**Comment by adammacias** [comment]
Seu fanfarrão haha, quer que eu bote no meu servidor e tu só aponta o DNS?

PS. Também não sei se precisa mesmo de um demo. Um *screenshoot* resolveria o problema caso o usuário queira ver como é a aparência inicial do Odin.

**Comment by fdaciuk** [comment]
:+1:

**Comment by valdirljr** [comment]
Paga a hospedagem senão o UOL/Locaweb derruba mesmo rs

**Comment by adammacias** [comment]
Caso precise, tirei um *full print* :smile: 
![odin-framework---so-mais-um-site-wordpress](https://cloud.githubusercontent.com/assets/1139893/6702063/75292f34-cd04-11e4-99ec-8d68bfdd55e9.jpg)
