### ISSUE TITLE
odin_thumbnail() , adicionar tag title

### ISSUE THREAD

**Issue by valdirljr** [wpbrasil/odin#269]
Sinto que falta a tag title aí. 
O que acham ? 

Referência: https://github.com/wpbrasil/odin/wiki/Redimensionando-a-imagem-destacada-(thumbnail)

**Comment by rafaelfunchal** [comment]
`title` não é um atributo válido para a tag `img`.

Referência: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by fdaciuk** [comment]
Na verdade `title` é um atributo global, que pode ser usado em qualquer elemento:
http://w3c.github.io/html-reference/img.html
http://w3c.github.io/html-reference/global-attributes.html

:smile:

**Comment by claudiosmweb** [comment]
Mas se já tem `alt`, não tem muito motivos para ter `title` também.

**Comment by fdaciuk** [comment]
`title` só serve quando passa o mouse em cima.

**Comment by rafaelfunchal** [comment]
> Mas se já tem alt, não tem muito motivos para ter title também.

:+1:

**Comment by adammacias** [comment]
> Mas se já tem alt, não tem muito motivos para ter title também.

:+1:

**Comment by valdirljr** [comment]
Sei que title não terá efeito algum em SEO, visto que irá usar a tag alt para isto. 
Porém, para acessibilidade, ajuda visto que você pode colocar informações adicionais a imagem. 
Eu não ligaria para isto se não fosse algo que estivesse ali para ser preenchido, quando se edita uma imagem no WP: 
![title fw](https://cloud.githubusercontent.com/assets/558397/6651356/71bde3e2-ca1d-11e4-9cbc-b6982a873cb1.png)
http://moz.com/ugc/link-tilte-attribute-and-its-seo-benefit
http://www.wpromote.com/blog/seo/image-alt-vs-title-using-alt-title-attributes-in-image-tags

**Comment by valdirljr** [comment]
Sei que title não terá efeito algum em SEO, visto que irá usar a tag alt para isto. 
Porém, para acessibilidade, ajuda visto que você pode colocar informações adicionais a imagem. 
Eu não ligaria para isto se não fosse algo que estivesse ali para ser preenchido, quando se edita uma imagem no WP: 
![title fw](https://cloud.githubusercontent.com/assets/558397/6651356/71bde3e2-ca1d-11e4-9cbc-b6982a873cb1.png)
http://moz.com/ugc/link-tilte-attribute-and-its-seo-benefit
http://www.wpromote.com/blog/seo/image-alt-vs-title-using-alt-title-attributes-in-image-tags

**Comment by adammacias** [comment]
Ok @valdirljr vendo por esse lado, acho pode ser útil :smile: :+1:

**Comment by claudiosmweb** [comment]
Na real acessibilidade é com a tag alt mesmo.
Ela não serve apenas para SEO e sim para ser como uma alternativa para a imagem, descrevendo ela caso ela não seja carregada.

**Comment by valdirljr** [comment]
Concordo que a title não é usada para nada além de passar o mouse em cima e exibir o texto @claudiosmweb  , porém, ao chamar um thumb com link não exibe a tag title.
Posso exibir assim: 
<a href="<?php the_permalink(); ?>" title="<?php the_title_attribute(); ?>"><?php echo odin_thumbnail( 555, 312, ''.get_the_title().'', true, 'minha-classe' ); ?></a>

Porém, se for utilizar somente a thumb sem link não exibirá a tag title. Penso que se colocaram para utilizar este atributo no WP deveríamos utilizar...

**Comment by claudiosmweb** [comment]
Não existe `the_title_attribute()` para a imagem até então desta forma, precisa pegar do attchment.

**Comment by valdirljr** [comment]
http://codex.wordpress.org/Function_Reference/wp_get_attachment_metadata

**Comment by allysonsouza** [comment]
Na verdade, discutimos isso em outro tópico, e havia me esquecido que simplesmente `get_the_title()` serve para pegar o título de attachmentes.

**Comment by claudiosmweb** [comment]
@valdirljr mas nesse caso vai usar o post como title e não o title da imagem que você mostrou na imagem?

**Comment by adammacias** [comment]
Essa função **wp_get_attachment_metadata()** pega os dados do arquivo, exemplo: Quando uma pessoa, normalmente fotografo, altera as propriedades de um arquivo no Photoshop ou Lightroom, ele consegue colocar essas informações no arquivo em questão. Como exemplo "Titulo, Copyright, Câmera, Lente...". Só para constar, essas informações também pode ser editadas através do "Propriedades >> Detalhes" de um arquivo.

Eu acho válido usar isso :+1: Teve um job de um amigo que o fotografo editava tudo no Lightroom e  quando fazia o upload não precisava ficar adicionando os título, pois o WordPress já importa automaticamente o *title* de um arquivo através das *metadata" .
