### ISSUE TITLE
Número de páginas na paginação

### ISSUE THREAD

**Issue by valdirljr** [wpbrasil/odin#271]
Há alguma forma de alterar o numero de páginas exibidas na paginação? 
Pelo que vi, a função não aceita parâmetros e estou com um layout que o designer colocou 10 páginas para serem exibidas na paginação. Estou adorando os layouts deste cara!

**Comment by rafaelfunchal** [comment]
`odin_pagination()` aceita parâmetros sim.

Dê uma olhada na função: https://github.com/wpbrasil/odin/blob/master/core/helpers.php#L26
