### ISSUE TITLE
GruntJS demora para compilar SASS

### ISSUE THREAD

**Issue by 72fcosta** [wpbrasil/odin#272]
Olá mundo. Desenvolvia temas a partir de um kick start próprio. Senti falta de algo para adcionar metaboxes personalizadas em meu kick start. Buscando praticidade, na questão dos metaboxes entre outras, encontrei ontem o Odin e resolvi testar. No pacote de testes entrou GruntJS. Minha dúvida; Anteriormente eu compilava o Sass com o Scout e era bem rápido e agora usando o GruntJS demora 5 segundos cada alteração. É isso mesmo? Obrigado (em tempo: uso o Windows 8)

**Comment by vitorbritto** [comment]
@72fcosta olá! Então, seria interessante posicionar sua dúvida no grupo do WordPress Brasil no Facebook também, já que estamos tratando do Odin.

Como está a configuração do Sass no seu Gruntfile? Pode compartilhar o código conosco? =]

**Comment by 72fcosta** [comment]
Super coincidência. Estava em seu blog lendo sobre o LiveReload no Grunt, ao mudar a aba para ver se havia alguma resposta por aqui, olha quem apareceu. Me desculpe por postar em local errado. Achei que seria algo relacionado ao tema, pois tanto o Odin quanto o Grunt são novidades pra mim. Eu apenas dei um npm install no diretório src e não alterei nada
![capturar](https://cloud.githubusercontent.com/assets/11538191/6709793/de65a472-cd5a-11e4-9ef0-99e59c582905.JPG)
.

**Comment by gbrlsepulveda** [comment]
@72fcosta no Odin é utilizado compass, é uma biblioteca um pouco pesada. Se não estiver utilizando nada do Compass, sugiro mudar o compilador para o lib-sass ou node-sass

**Comment by 72fcosta** [comment]
@gbrlsepulveda e @vitorbritto, obrigado! Vou iniciar a briga com o Grunt para mudar o compilador. Abraços.

**Comment by vitorbritto** [comment]
@72fcosta não está em local errado. Entretanto, o pessoal pode dar uma força por lá também.

Pode enviar um print do config.rb também?

Uma alternativa seria esta que o @gbrlsepulveda mencionou acima. É importante verificar quais arquivos estão definidos para compilar e tentar não forçar o _overwrite_ dos arquivos. No objeto `options` coloca a propriedade **force** com valor boleano definido em _false_.

```
options: {
    force: false,
    ...
}

Obrigado. =]

**Comment by 72fcosta** [comment]
@vitorbritto Se eu migrar para outro compilador, mais tarde o Compass pode me fazer falta para algum outro recurso do Odin?
![capturar](https://cloud.githubusercontent.com/assets/11538191/6711231/7b34e32c-cd64-11e4-93f6-cdc5a58bcab0.JPG)

**Comment by 72fcosta** [comment]
Migrei a compilação do style.scss do Odin do Grunt para o Gulp e continuo com problemas (1 erro "file not found" e a performance baixa "5s";
1) Erro na importação "@import "compass/css3";".  (Compass já está instalado.);
2) Comentei a linha acima para verificar a performance e não obtive nenhuma melhora (em torno de 5s).
Devo estar fazendo algo bem errado :(
Será que é pela quantidade de arquivos importados? Devo usar outra stylesheet para personalizar meu tema?

**Comment by 72fcosta** [comment]
Em busca de melhorar a performance da compilação eu migrei para o Gulp e continua em 5 segundos cada alteração.
Devo estar fazendo algo bem errado :(
Será que é pela quantidade de arquivos importados? Devo usar outra stylesheet para personalizar meu tema?

**Comment by fdaciuk** [comment]
@72fcosta não vai resolver muito usar o Gulp, pois o SASS é compilado pelo Ruby. Tente usar o lib-sass pra compilar :smile:

**Comment by 72fcosta** [comment]
@fdaciuk (da2k), eu já tinha tentado usar o lib-sass também indicado por @gbrlsepulveda, mas graça a minha completa inesperiência não consegui :(( Vou tentar de novo. Muito obrigado.

**Comment by fdaciuk** [comment]
Você tá usando o `gulp-sass`? Ele já usa o libsass.

**Comment by 72fcosta** [comment]
@claudiosmweb me desculpe acho que a minha questão não é para o fórum do Odin.

**Comment by claudiosmweb** [comment]
@72fcosta você esta procurando suporte para usar grunt e gulp, não como usar o Odin.

**Comment by 72fcosta** [comment]
@claudiosmweb ok
