### ISSUE TITLE
Remover dependencia ao Compass

### ISSUE THREAD

**Issue by claudiosmweb** [wpbrasil/odin#273]
Não precisamos de Compass uma vez que estamos usando o Bootstrap que já tem vários mixins.

Ref #272

**Comment by 72fcosta** [comment]
@claudiosmweb ótimo! Vou começar minha experiência com o Odin por aí então...estou tentando colocar o node-sass no lugar! Impressionado com a atenção dispensada por todos! Obrigado.

**Comment by 72fcosta** [comment]
Estou tentando a compilação Sass com o node-sass. Está retornando "file to import not found" na linha 7 (// Odin variables configuration.). Compass já instalado e já executado a instruções anexa. O erro continua aparecendo.
![capturar](https://cloud.githubusercontent.com/assets/11538191/6730592/ddd5dd48-ce1c-11e4-9c7a-15dec5910500.JPG)

**Comment by allysonsouza** [comment]
Pô, não entendi porquê remover o Compass, não dava para coexistir uma task de Sass, outra de Compass, e cada um que utilizasse o que coubesse em seu projeto, comentando ou não o import do compass no seu _config.scss?

**Comment by claudiosmweb** [comment]
Na verdade o certo é mudar para https://github.com/gruntjs/grunt-contrib-sass
Assim se quiser usar compass é só indicar `compass: true`.

**Comment by claudiosmweb** [comment]
Resolvido em #277
