### ISSUE TITLE
Erro ao acionar Menu Responsivo do Odin

### ISSUE THREAD

**Issue by Adrian1995** [wpbrasil/odin#278]
Pessoal, estou com um problema. Ao redimensionar o tamanho da tela, automaticamente a página faz o menu desaparecer e exibe um novo botão para fazer o menu aparecer em dropdown, porém ao clicar nesse botão que deveria exibir o menu em dropdow nada acontece. Acredito que seja um erro do próprio template, pois efetuei uma instalação do zero e o problema já ocorre.

**Comment by allysonsouza** [comment]
@Adrian1995, um erro do tema não deve ser, pois diversas pessoas já o utilizaram e ninguém teve problema com isso ainda, eu inclusive. Você tem mais informações sobre este erro? Verificou o console do navegador para ver se há algum alerta?

**Comment by ivanildodias** [comment]
Chequei aqui também e realmente não tá funcionando o toggle. Deve ser algo errado com a chamado do collapse. Nada aparece no console. Mas notei que se eu acrescentar a classe "in" no ".navbar-main-navigation" o menu e o form de pesquisa aparecem. Tem algo errado no evento de click do botão.

**Comment by andersonsimproarte** [comment]
Também estou com o mesmo problema, e nenhum plugin de popup funciona corretamente.

**Comment by leobaiano** [comment]
Vocês tem certeza que estão usando a versão atual do tema? Acabei de clonar o repositório para ver o erro e corrigir, mas acontece que aqui não tem erro nenhum no menu, vejam os prints.

![captura de tela 2015-04-20 as 10 24 28](https://cloud.githubusercontent.com/assets/957257/7230840/b6796708-e747-11e4-8e14-524806f75366.png)
![captura de tela 2015-04-20 as 10 24 50](https://cloud.githubusercontent.com/assets/957257/7230839/b67821e0-e747-11e4-9926-479575e95d7f.png)

Vocês estão usando o Odin sem nenhuma modificação, criaram um tema filho e fizeram algumas mudanças ou alteraram direto nos arquivos do Odin?

Podem baixar novamente o odin e testar?

Isso também pode ser algum conflito com plugin, vocês poderiam testar desabilitar todos os plugins para ver se mesmo assim continua com erro?

**Comment by andersonsimproarte** [comment]
Obrigado Leo, Eu não criei tema filho não, mas não alterei nada na pasta core. Vou baixar novamente e testar.

O problema com o menu eu resolvi de outra forma, acabei instalando um outro menu. segue link. http://taticadigital.com.br

Meu problema agora é que não consigo fazer os plugins de popup funcionar.

**Comment by andersonsimproarte** [comment]
Acabei de baixar o zip do tema e reinstalei em servidor local, o toggle continua sem funcionar aqui. 
![image](https://cloud.githubusercontent.com/assets/8260050/7231207/6b2221fc-e74a-11e4-87c0-fbfb7dc92294.png)

**Comment by leobaiano** [comment]
@andersonsimproarte vou fazer uns testes aqui para tentar reproduzir o erro, porque aqui pra mim o erro não ocorre.

**Comment by andersonsimproarte** [comment]
@leobaiano, se você quiser, eu posso subir e você dá uma olhada, mas a minha instalação tá limpinha, não mudei nada e não funcionou o popup nem o menu, acredito que seja alguma coisa simples, mas eu não encontro de jeito nenhum.

**Comment by rafaelfunchal** [comment]
Checaram ai se está dando 404 no `/assets/js/main.min.js` ?

**Comment by andersonsimproarte** [comment]
Rafael, eu chequei aqui e não deu nenhum erro de 404, mas eu não tenho esse arquivo minificado, eu tenho /assets/js/main.js

**Comment by leobaiano** [comment]
@rafaelfunchal acabou com o mistério! Essa versão está usando uma task no grunt para minificar e unir todo JS em um unico arquivo. Você precisa rodar essa task para gerar o JS ou coloca a linha abaixo no seu wp-config.php para chamar os arquivos em modo debug:

```define('SCRIPT_DEBUG', true);```

**Comment by rafaelfunchal** [comment]
Isso mesmo @leobaiano :+1:

**Comment by andersonsimproarte** [comment]
Galera, o menu funcionou direitinho, mas eu ainda estou com o problema nos plugins de popup.

**Comment by rafaelfunchal** [comment]
@andersonsimproarte qual erro informado no console do inspetor?

**Comment by andersonsimproarte** [comment]
@rafaelfunchal não apresenta nenhum erro, o popup não carrega no odin, quando eu troco de tema ele funciona certinho.

**Comment by leobaiano** [comment]
Qual o nome do plugin @andersonsimproarte ?

**Comment by andersonsimproarte** [comment]
Oi @leobaiano eu estou testando o Simple Popup manager e o Ninja Popup

**Comment by rafaelfunchal** [comment]
Acabei de testar com o [Welcome Popup](https://wordpress.org/plugins/welcome-popup/) e funciona de boa.

Não tenho como testar com o Ninja Popup por que ele é Premium :P

**Comment by leobaiano** [comment]
Vou testar o simple pop up aqui para ver se reproduzo o erro.

**Comment by andersonsimproarte** [comment]
@rafaehlers funcionou de boa mesmo, eu queria o ninja poque é pra usar em uma lista do aweber, e ele tem outras funções legais rs.

Eu não sei se existe regra pra isso aqui, mas eu não vejo problema em compartilhar com quem está me ajudando, qualquer coisa eu tiro depois.

SEGUE LINK DO NINJA POPUP -> https://www.dropbox.com/s/stvukm5klnt3ura/ninja%20popup.zip?dl=0

**Comment by leobaiano** [comment]
Simple pop up in action.

![captura de tela 2015-04-20 as 12 06 48](https://cloud.githubusercontent.com/assets/957257/7233121/cae894c6-e755-11e4-8b51-8d9c90ed599e.png)

Você disse que estava com uma instalação zerada, sem plugin e tal, correto? Tem certeza que o problema não são suas configurações ai no plugin? Tem um checkbox que coloca ele em modo debug e ignora cookie, habilita isso ai pra ver se não abre? Vai ver seu computador está com cookie e não mostra mais o popup.

**Comment by leobaiano** [comment]
@andersonsimproarte eu acho que sua licença não permite distribuição do plugin, então você não poderia compartilhar com ninguém os arquivos.

**Comment by claudiosmweb** [comment]
Para galera, erro ai só se for de JavaScript com algo que foi adicionado a mais.
Isso não é "Menu Responsivo do Odin", é menu "Responsivo do Bootstrap", se não sabe usar Bootstrap, é simples, basta aprender ou não usar.
