### ISSUE TITLE
Adicionar Metabox em Páginas

### ISSUE THREAD

**Issue by ThiagoRezende** [wpbrasil/odin#279]
Pessoal, gostaria de saber se é possível criar metabox em páginas (template) usando a classe Odin_Metabox? Pois não encontrei na documentação, se for possível, favor apresentar um exemplo. Obrigado.

**Comment by allysonsouza** [comment]
@ThiagoRezende a classe metabox cria meta boxes para post types, seja eles os padrões criados pelo WordPress (post, page, attachment) ou não.

Então, ao criar sua metabox, basta utilizar o slug do post type páginas, que é page. Exemplo:

```
$videos_metabox = new Odin_Metabox(
    'videos', // Slug/ID do Metabox (obrigatório)
    'Videos Configurações', // Nome do Metabox  (obrigatório)
    'page', // Slug do Post Type, sendo possível enviar apenas um valor ou um array com vários (opcional)
    'normal', // Contexto (opções: normal, advanced, ou side) (opcional)
    'high' // Prioridade (opções: high, core, default ou low) (opcional)
);
```

**Comment by ThiagoRezende** [comment]
@allysonsouza obrigado!
