### ISSUE TITLE
Adicionar metabox de forma dinâmica através de botão

### ISSUE THREAD

**Issue by ThiagoRezende** [wpbrasil/odin#280]
Boa tarde, pessoal.

Meu conhecimento em PHP é de básico a intermediário, e eu precisava adiconar metaboxes num custom post de forma dinâmica, ou seja, ao adicionar um post preciso de um botão ou algo similar que ao clicar nele adicione uma metabox, essas metaboxes teriam sempre os mesmos campos.

Alguém sabe me dizer como posso fazer? 

Desde já agradeço.

**Comment by claudiosmweb** [comment]
Ainda não temos suporte para isso, o @fdaciuk e eu vamos adicionar em alguma versão futura.
