### ISSUE TITLE
Odin Theme Options

### ISSUE THREAD

**Issue by vinigarcia87** [wpbrasil/odin#281]
Olá,
Estou usando a classe de Theme Options "stand alone" em um theme que estou criando.
Tenho duas duvidas:

		$settings->set_fields(
			array(
				'odin_general_fields_section' => array( // Slug/ID of the section (Required)
					'tab'   => 'odin_general', // Tab ID/Slug (Required)

Tab é sempre required?
Eu nao posso criar uma pagina de options usando varias sections e nenhuma tab?
Se tem como, como eu faço isso?

A outra duvida, é com relação ao fato de que eu uso a classe "stand alone". O metodo scripts inclui um javascript e um css do Odin. Qual a necessidade desses scripts? Como faço para retira-los ou substitui-los?

Obrigado!

**Comment by allysonsouza** [comment]
@vinigarcia87 quanto as tabs, utilizei pouco esse recurso do Odin, mas acredito que elas sejam necessárias da forma que a classe está estruturada, mas você pode tentar dividir a sua página de opções com um elemento html, utilizando o campo html: https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options#html

Quanto ao css é estilo, nada que vá fazer algo parar de funcionar (pelo menos não deveria) e o js é importante se estiver utilizando o campo de upload de arquivos/imagens, pois é ele que faz a chamada à interface de mídia.

**Comment by claudiosmweb** [comment]
Sim é obrigatório indicar uma tab, já que ele esta preparado para dividir o conteúdo em várias abas.
JS e CSS são principalmente para os campos de upload, se quer usar em outro lugar já é custom code e custom code não tem suporte aqui!
