### ISSUE TITLE
Popup no Odin

### ISSUE THREAD

**Issue by andersonsimproarte** [wpbrasil/odin#282]
Galera, Bom dia! Estou com alguns problemas no Odin Framework. O Menu responsivo não funciona quando aparece o botão toggle, e nenhum plugin de popup funciona com esse tema, já testei o Ninjja Popup e o Simple popup manager.

Preciso da ajuda de vocês.

Obrigado!

**Comment by claudiosmweb** [comment]
Tema é para desenvolvimento.
Qualquer plugin pode funcionar com ele e o menu é apenas Bootstrap, basta você verificar o CSS e JavaScript e alterar como você preferir.

Este plugin funciona bem: https://wordpress.org/plugins/ultimate-modal/

Agora se você esta testando plugin ruim, ai é outra história.
