### ISSUE TITLE
CTP não aparece na listagem de Post Types para adicionar ao menu

### ISSUE THREAD

**Issue by ThiagoRezende** [wpbrasil/odin#284]
Pessoal,
Não consigo trazer os posts types (link para archives) nos menus do WP, isso começou quando comecei a usar o ODIN, tentei via função no functions e também com plugins e nada.

Na listagem de de posts types na página Aparência > Menus do admin fica somente um loader e não carrega os posts types.

Alguem já teve este problema ou sabe a solução?

**Comment by allysonsouza** [comment]
Nunca tive esse problema, sempre apareceram normalmente.
Seus CPT's são públicos? Tenta passar na criação o argumento "show_in_nav_menus" => true e veja se eles então aparecem.

(Pode tentar postar um print deste loader que disse que está carregando também, nunca vi isso)

**Comment by ThiagoRezende** [comment]
@allysonsouza o problema era este mesmo, os CTP's estavam com "show_in_nav_menus" => false.
Não me atentei a isso, obrigado!

**Comment by allysonsouza** [comment]
De nada! :+1:
