### ISSUE TITLE
Problema com permalinks e custom post type

### ISSUE THREAD

**Issue by diogenesjup** [wpbrasil/odin#290]
Pessoal estou com um problema,
no odin eu criei um custom post type da seguinte maneira:

function odin_cursos_cpt() {
    $cursos = new Odin_Post_Type(
        'Cursos', // Nome (Singular) do Post Type.
        'cursos' // Slug do Post Type.
    );

    $cursos->set_labels(
        array(
            'menu_name' => __( 'Cursos', 'odin' )
        )
    );

    $cursos->set_arguments(
        array(
        	'public' => true,
            'has_archive' => true,
        	'query_var' => true,
        	'rewrite' => true,
            'supports' => array( 'title', 'editor', 'thumbnail' )
        )
    );
   
}

add_action( 'init', 'odin_cursos_cpt', 4 );

Entretanto na página da postagem que fiz, em vez de exibir o conteúdo no single.php ele vai para o 404.php o que pode estar errado? 

Acredito que seja alguma configuração do Odin, por que quando mudo o tema, o problema é resolvido

**Comment by rafaelfunchal** [comment]
Lembrou de salvar os Links Permanentes?

**Comment by diogenesjup** [comment]
Claro, foi a primeira coisa que verifiquei
quando eu altero para Padrão funciona normalmente, porém não fica com uma URL amigável 
dai altero para Nome do Post da 404, isso apenas no custom post type que criei,

**Comment by leobaiano** [comment]
Isso não parece ser problema no Odin. Tem alguma página ou qualquer outra coisa com o mesmo slug do CPT que você acabou de criar? Lembrando que o CPT tem o singular e plural, então se seu slug do CPT for produto e existir uma página chamada produtos vai dar conflito e pode gerar esse erro 404.

**Comment by diogenesjup** [comment]
@leobaiano eu tenho uma página com o slug "cursos-energias" isso pode ser a causa? por que como tem o "-energias" não deveria dar conflito com "cursos" de toda forma vou testar

**Comment by diogenesjup** [comment]
Fiquei na esperança de ser isso, mais não deu certo.
registrei um novo com o slug "cursoteste" e mesmo assim continua dando 404

**Comment by cirino** [comment]
Testa cteste, vai saber
Em 27/05/2015 12:26, "Diogenes Oliveira Junior" <notifications@github.com>
escreveu:

**Comment by cirino** [comment]
Tenta fazer um cpt simples, só para testar. Ver se Ta gravando mesmo.
Em 27/05/2015 12:27, "Dagmar Cirino" <dagmar.mv@gmail.com> escreveu:

**Comment by diogenesjup** [comment]
boa, resolvi o problema,
criei um simples chamado cteste e rolou, 
mais meio estranho esse negócio de ter parte do nome de um outro slug e ai não rolar.

**Comment by cirino** [comment]
Hehehehehe, minha ideia funcionou. Huhuhu. Então o problema é com seu bd.
Da uma olhada no MySQL, esse nome pode estar gravado nele, em uma chamada
Antiga.
Em 27/05/2015 12:44, "Diogenes Oliveira Junior" <notifications@github.com>
escreveu:

**Comment by rafaelfunchal** [comment]
Até mesmo slugs de posts na lixeira podem gerar conflito.

Legal que encontrou o erro, @diogenesjup .

**Comment by cirino** [comment]
Olá,

Gostaria que você fizesse parte da minha rede do LinkedIn para compartilhar atualizações e manter contato.

- Dagmar

Confirme que você conhece Dagmar: https://www.linkedin.com/e/v2?e=4cazec-iava82gt-4h&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=r_7I-Rjq&amp;invitationID=6015531189203410944


Você recebeu um convite de conexão. O LinkedIn utiliza seu endereço de e-mail para fazer sugestões a nossos usuários em recursos como Pessoas que talvez você conheça. Clique aqui para cancelar a inscrição: https://www.linkedin.com/e/v2?e=4cazec-iava82gt-4h&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQEsIfiN4iLnywAAAU3t11q5oWuGKqWpQUnLgXHj1GhmfYzUJnbeb7VfEYUXHZ0iJgn78TCf1sA79Apkbnvm0qFrJSoMToMjOiMocHdVPpkXe2DU9XG7H1oSfq5ZMpTwQbnKagOR7pW8e6SZzKH-PnSw3MrIYeQsLiPCBda8G5_XBXgMILykIeZRoc1CI15RQl69&amp;eid=4cazec-iava82gt-4h Saiba por que incluímos isso neste link: https://www.linkedin.com/e/v2?e=4cazec-iava82gt-4h&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, EUA

**Comment by rafaelfunchal** [comment]
Não!
