### ISSUE TITLE
thumb resizer e plupload

### ISSUE THREAD

**Issue by zergiocosta** [wpbrasil/odin#291]
Seguinte, galerë...  Estou utilizando o Odin pela primeira vez em um site e, obviamente, algumas dúvidas aparecem. Enfim...

A dúvida é a seguinte: Dentre outros, estou utilizando dois módulos, em especial, para este caso específico.
Subindo várias imagens pelo campo `plupload`. Só que, obviamente, as imagens vem em tamanhos diferentes.
Vi que no `resizer` do odin, eh utilizado o `aqua resizer`...
O que eu quero saber é se tem como recortar as imagens que subiram pelo `plupload` atraves desse `resizer` que já vem com o odin, pra facilitar o trabalho. =D

**Comment by leobaiano** [comment]
@zergiocosta uma das vantagens de usar o `aqua resizer` ao invés do WP é que ele faz o crop na hora que a imagem é chamada e não na hora do upload como o WordPress faz. Sendo assim basta chamar ele que as imagens que já foram upadas serão cropadas no tamanho definido na chamada da função do Odin.

A documentação completa você pode ver aqui: [Redimensionando imagens](https://github.com/wpbrasil/odin/wiki/Redimensionando-a-imagem-destacada-(thumbnail))

**Comment by zergiocosta** [comment]
Isso, eu To ligado. Mas isso ai é relativo às post thumbnails. O que eu quero saber, é sobre as imagens que são subidas pelo campo "plupload", que é aquele campo de múltiplo upload de imagens, do odin...

**Comment by leobaiano** [comment]
Verdade @zergiocosta. Acho que você pode usar o método `odin_get_image_url();` dessa mesma classe.

Não está na wiki, mas é simples e está comentado dentro da classe.

`
/**
 * Get a image URL.
 *
 * @param  int     $id      Image ID.
 * @param  int     $width   Image width.
 * @param  int     $height  Image height.
 * @param  boolean $crop    Image crop.
 * @param  boolean $upscale Force the resize.
 *
 * @return string
 */
function odin_get_image_url( $id, $width, $height, $crop = true, $upscale = false ) {
	$resizer    = Odin_Thumbnail_Resizer::get_instance();
	$origin_url = wp_get_attachment_url( $id );
	$url        = $resizer->process( $origin_url, $width, $height, $crop, $upscale );
	return $url;
}
`

**Comment by zergiocosta** [comment]
hum... acho que funciona perfeitamente! o `foreach` do `image_plupload` já traz as IDs das imagens. Só passar o ID, junto com os outros parâmetros necessários, dentro desse método `odin_get_image_url()` e acho que está tudo certo! Valeu, @leobaiano !

**Comment by leobaiano** [comment]
Depois de testar volta aqui pra dar um feeback e fecha a issue na moral.

**Comment by zergiocosta** [comment]
sim, claro! assim que testar, volto aqui pra fazer isso! só esqueci de deixar isso claro, no último comment xD

**Comment by zergiocosta** [comment]
acabei de testar e funcionou perfeitamente, @leobaiano !

ficou assim:

```php
$images = get_post_meta( $post->ID, 'images', true ); // pega os ids das imagens
foreach ( explode( ',', $images ) as $image_id ) { // transforma a string com as ids em um array de ids e faz um loop com essas ids
     $imageUrl = odin_get_image_url( $image_id, 150, 150, true, false ); // a cada loop, passa o id da imagem pra pegar a url equivalente, no tamanho setado (150x150, no caso)
     print_r($imageUrl); // aqui, ele já printa as urls da imagens adicionadas no pluoload, a cada loop
}
```

valeu =D
