### ISSUE TITLE
Ajuda com Odin

### ISSUE THREAD

**Issue by guicamarotto** [wpbrasil/odin#292]
Olá pessoal! Boa tarde. Encontrei o Odin esses dias navegando pela net e queria entender mais como funciona, o que ele faz etc. tem algum tutorial, video aula, primeiros passos? Eu faço sites em wordpress mas tudo com tema pronto e plugins prontos, mas queria algo mais high level hehe

valeu!

**Comment by allysonsouza** [comment]
Olá @guicamarotto,

O Odin é um framework, um tema base que foi criado pela comunidade após o pessoal discutir e ver que ao desenvolver um tema nos projetos muita coisa era "refação", "snippet", "copy/paste".

Ele é um framework de WordPress, então, o que ele vai te oferecer? Funções e Classes para criação de Custom Post Types, criação de Taxonomies, criação de Meta Boxes, geração de Breadcrumbs, dentre muitas outras coisas, tudo de uma forma muito prática.

Ele vem preparado para ser utilizado com diversas tecnologias das mais utilizadas atualmente, como o Grunt e o Bootstrap, porém de forma não obrigatória.

Recomendo a você baixar ele, instalar em um projeto de testes e dar uma olhada na Wiki, fazendo as coisas que os exemplos mostram: https://github.com/wpbrasil/odin/wiki

**Comment by guicamarotto** [comment]
show cara muito obrigado!

Em 1 de junho de 2015 17:55, Allyson Alves de Souza <
notifications@github.com> escreveu:

**Comment by allysonsouza** [comment]
De nada, precisando estamos ai!
