### ISSUE TITLE
Odin + Woocommerce

### ISSUE THREAD

**Issue by fnovais** [wpbrasil/odin#293]
Estou utilizando o Odin Framework junto com Woocommerce. O padrão do Woocommerce é que os produtos sejam exibidos na página de posts recentes (arquivo). Nesta página, não consigo exibir a sidebar. Se eu troco para um outro tema (forefront, por exemplo), a sidebar aparece instantâneamente. Procurei em tudo que é canto da internet, mas não encontro nada a respeito.

**Comment by claudiosmweb** [comment]
Só trocar o template da página...
Tem um template deles com sidebar.
Só olhar o que esta fazendo e tudo vai dar certo!

Edite a página e olhe os atributos de pagina, lá tem a opção do template.
