### ISSUE TITLE
Chamar função JS na página de cadastro de post de um CPT 

### ISSUE THREAD

**Issue by ThiagoRezende** [wpbrasil/odin#294]
Pessoal, preciso inserir uma função ao cadastrar um post de um CTP, por exemplo um alert no momento em que o administrator publique um post, algo assim:

jQuery('seletor_do_form').on('submit', function(){});

A questão é, alguem sabe me dizer como chamo essa função no momento que irei cadastrar o post, no caso seria no "post-new.php?post_type=slugdoCTP", sendo a função específica para um determinado custom post.

Agradeço desde já.

**Comment by claudiosmweb** [comment]
Como você faria isso se não estivesse usando o Odin?

**Comment by rafaelfunchal** [comment]
Mas dá pra carregar scripts no Admin do WordPress sem usar o Odin, @claudiosmweb ?

**Comment by ThiagoRezende** [comment]
@claudiosmweb Na verdade meu conhecimento em PHP é intermediário, pesquisei na web e não encontrei algo que resolva..

**Comment by claudiosmweb** [comment]
@ThiagoRezende e porque perguntando aqui então?
Melhor seria um grupo sobre WordPress do que aqui.
Se fosse pergunta que envolve exclusivamente este tema aqui, ai beleza.

**Comment by ThiagoRezende** [comment]
OK. pode fechar. Obrigado.
