### ISSUE TITLE
Sidebar em site Odin + Woocommerce

### ISSUE THREAD

**Issue by fnovais** [wpbrasil/odin#295]
Olá. 
Estou construindo um site com Odin + Woocommerce, porém, a sidebar de categorias não aparece na página de produtos, mesmo que eu altere o tipo de template no Admin. Quando troco para outro tema, como o Storefront, por exemplo, a sidebar aparece normalmente. Não consigo encontrar solução.
Caso queira testar, a URL é 
http://pilhadecoisashomologacao.com.br/ 
e tem um usuário para testar: 
User: teste
Senha: teste123

**Comment by claudiosmweb** [comment]
Tente remover esta linha de código https://github.com/wpbrasil/odin/blob/master/inc/woocommerce/hooks.php#L30

Agora que estou vendo que o @adammacias colocou ela.
@adammacias alguma razão para isso ?

**Comment by fnovais** [comment]
Agora a sidebar apareceu, mas ela fica abaixo de todo o conteúdo, pois a #primary está pegando col-md-12 do bootstrap, e como fica com 100%, joga a sidebar para baixo. Tenho de ajustar isto no meu CSS, ou o ajuste é no template?

**Comment by adammacias** [comment]
Wow, eu estava nesse arquivo agora @claudiosmweb haha.
Coloquei para deixar mais fácil pro pessoal remover, mas acabei esquecendo de deixar comentado, vou consertar isso agora. Valeu pelo toque. :+1: 

@fnovais seleciona o modela do página com sidebar (with sidebar) que deve corrigir.

**Comment by fnovais** [comment]
@claudiosmweb  e @adammacias. Obrigado pela ajuda, mas o problema ainda não foi solucionado. A sidebar continua aparecendo abaixo dos produtos. Atualizei na URL que passei acima, e mesmo com o modelo "with sidebar" habilitado, não houve alteração.

**Comment by adammacias** [comment]
@fnovais Experimenta trocar a função `odin_classes_page_full()` por `odin_classes_page_sidebar_aside()` na linha https://github.com/wpbrasil/odin/blob/master/inc/woocommerce/functions.php#L17

**Comment by fnovais** [comment]
@adammacias, ainda não deu certo. Agora, ambas, sidebar e primary ficaram com 4 colunas cada.

**Comment by adammacias** [comment]
Eu havia colocado `odin_classes_page_sidebar_aside()`e em seguida editei para `odin_classes_page_sidebar()`você chegou a colocar qual dessar? :laughing:

**Comment by fnovais** [comment]
@adammacias, com a classe odin_classes_page_sidebar() funcionou. Tenho 2 dúvidas, se você puder responder, e se estiverem no escopo desta thread. Com esta alteração, o grid ficou com 4 cols para sidebar e 8 cols para a primary. Existe alguma maneira já prevista de eu alterar para um grid e 3 e 9 cols?

A outra dúivda é: o que exatamente eu não posso editar no framework? Criei um tema filho para evitar mexer nos templates principais, hooks, funções e templatetags, mas vocês me orientaram a fazer várias alterações nestes arquivos. Não corro o risco de perder, com alguma atualização?

**Comment by adammacias** [comment]
Sim, são essas função responsáveis pelo tamanho da coluna principal e a lateral [template-tags.php#L23-L49](https://github.com/wpbrasil/odin/blob/master/inc/template-tags.php#L23-L49)

Poder editar, pode tudo rs, mas não recomendo mexer em qualquer coisa que estiver no diretório **core**, pois as mudanças mais significativas são feitas aí. De resto, foi feito para você editar conforme gosto do cliente.

**Comment by fnovais** [comment]
Sensacional. Muito obrigado pela ajuda @adammacias e @claudiosmweb.

**Comment by AllanD1** [comment]
eu não estou conseguindo muda os Templates mudo pra um sem sidebar ele não muda
