### ISSUE TITLE
Customize API e opções do Odin

### ISSUE THREAD

**Issue by matheusgimenez** [wpbrasil/odin#301]
Só trazendo um assunto um pouco chato pra cá, não sei se todos viram:

http://wptavern.com/wordpress-org-now-requires-theme-authors-to-use-the-customizer-to-build-theme-options

Tradução e resumo de uma linha: agora os temas do repo do WP precisam estar usando a customize API e não a settings API (usada pelo Odin).

Pensei que talvez fosse interessante fazermos algo pra tentarmos adaptar. Duas soluções que pensei foram: Criar uma classe para facilitar o uso da Customize API ou trazer uma pronta para dentro do Odin, no caso indicaria o Kirki:
http://kirki.org/

**Comment by valeriosouza** [comment]
Esse assunto, como ficou?

**Comment by allysonsouza** [comment]
Achei bem legal essa Kirki @matheusgimenez. Acho que talvez incorporá-la, ou mesmo recomendá-la já que ela funciona como um plugin, a princípio, seja melhor do que pensar em desenvolver uma classe própria para isso. (Há menos que alguém esteja com tempo sobrando ai :stuck_out_tongue_winking_eye: )

**Comment by matheusgimenez** [comment]
@allysonsouza agora ele é um plugin, antes não era, hehe.. por isso sugeri.. Mas por aqui eu ainda continuo usando como um include. Mas talvez não seja uma boa prática isso, hehe
Talvez seja interessante pensar a abordagem de criar uma classe.. seria demorado.. mas creio que é uma coisa importante. Eu poderia tentar ajudar com isso (mas sem pressa).

Mas acho que esse é um assunto importante, já que virou um padrao dos temas.. então continuemos o papo. :)

**Comment by claudiosmweb** [comment]
Fechando por causa de: https://github.com/wpbrasil/odin/issues/328#issuecomment-138654298
