### ISSUE TITLE
Theme options editor field

### ISSUE THREAD

**Issue by allysonsouza** [wpbrasil/odin#302]
Olá pessoal, não sou muito conhecedor da Settings API, então vim perguntar. Simplesmente criei uma página de opções do tema, com um campo "editor", como descrito na wiki. Porém na exibição do campo ele desconsidera todo o HTML inserido no editor. É preciso algum passo além do que está lá descrito para a exibição de campos do editor com o HTML?

**Comment by AdsonCicilioti** [comment]
Sim @allysonsouza , por padrão o WP não mantém as tags HTML no Editor. Eu também tive essa experiência duas soluções:
1) Usar um campo textarea.
ou
2) Usar um pequeno snippet para habilitar manter as tags, segue:

```
function override_mce_options($initArray) {
	$opts = '*[*]';
	$initArray['paste_word_valid_elements'] = $opts;
	$initArray['valid_elements'] = $opts;
	$initArray['extended_valid_elements'] = $opts;
	return $initArray;
}
add_filter('tiny_mce_before_init', 'override_mce_options');
```
coloquei no final do arquivo functions aqui e funcionou de boa

**Comment by AdsonCicilioti** [comment]
Ah, esqueci de perguntar:
Ele está retornando pelo menos texto simples?

Não sei se entendi bem. xD

**Comment by allysonsouza** [comment]
Olá @AdsonCicilioti , valeu pela resposta. Sim, o conteúdo esta sendo retornado. Acabei resolvendo da seguinte forma, exibindo meu conteúdo com a função wpautop() https://codex.wordpress.org/Function_Reference/wpautop

Mas valeu :+1:

**Comment by AdsonCicilioti** [comment]
Sim. a option `'wpautop' => false` habilita a exibição das tags padrões do editor.
O Snippet que passei acima habilita todas as tags html.

É Nózes! (;))
