### ISSUE TITLE
O arquivo /assets/js/main.min.js Não existe. Na pasta contém o main.js

### ISSUE THREAD

**Issue by DaviMenezes** [wpbrasil/odin#304]
Está causando erro no carregamento do arquivo. Se alguém puder colocar o arquivo que falta... eu pagaria uma cerveja

**Comment by rafaelfunchal** [comment]
Está usando o que para compilar seus JavaScripts?

Dê uma olhada nesse IF que entenderá o que está sendo feito:
https://github.com/wpbrasil/odin/blob/master/functions.php#L222-L235

**Comment by adammacias** [comment]
@rafaelfunchal + @wpbrasil/developers o que você acham mantermos o `main.min.js` no Odin, ele não está sendo enviado por causa do [.gitignore](https://github.com/wpbrasil/odin/blob/master/.gitignore#L36). Afinal de contas, não é todos que vão saber aproveitar o ótimo recurso dos automatizadores de tarefas. xD

**Comment by rafaelfunchal** [comment]
@adammacias, uma das funcionalidades do Odin é já vir com as tasks já configuradas e, além disso, tem até página na nossa Wiki explicando como usar:

https://github.com/wpbrasil/odin/wiki/Usando-o-GruntJS

É só dar uma lida :-)

**Comment by adammacias** [comment]
Sim @rafaelfunchal , esta muito bem explicado, as tasks estão tambem super simples de entender e tals :) Mas ainda continuo achando que não vai ser todos que vão conseguir instalar e configurar as coisas para usar o Grunt. :flushed: 

Se compararmos isso com o CSS "vanilla", é quase o mesmo esquema,  o [css/style.css](https://github.com/wpbrasil/odin/blob/master/assets/css/style.css) vem compilado e minificado com Odin pronto para o uso.

**Comment by fdaciuk** [comment]
Já que tem as libs incluídas, acho que faz sentido manter o JS minificado também, pra quem quiser usar o Odin "como está".

**Comment by vitorbritto** [comment]
Geralmente, os arquivos compilados e prontos para o ambiente de produção são colocados em uma pasta/diretório de nome `dist` para fins de organização e facilidade no uso/acesso.

Devo admitir que estou afastado do projeto há algum tempo, mas caso seja necessário, posso criar um scaffolding em Shell Script, NodeJS ou até mesmo um generator com o Yeoman. :neckbeard:

**Comment by AdsonCicilioti** [comment]
Concordo com @fdaciuk . Eu mesmo quando fui testar o Odin pela primeira vez estranhei a falta do Js. Só daí parti para a checagem do Gruntfile.
