### ISSUE TITLE
Implementar Continuous Delivery no Odin usando Docker

### ISSUE THREAD

**Issue by joao-parana** [wpbrasil/odin#306]
Minha sugestão é implementar  **Continuous Delivery** no projeto Odin usando Docker. 

O pessoal do [Roots](https://roots.io)  criou o [Trellis](https://roots.io/trellis/) para automatizar a construção e implantação de sites WordPress usando o _Ansible_ e o _Vagrant_.

Minha proposta é fazer algo mais leve usando o **Docker** e seu Ecosistema.

Esta issue serve ao proposito de discussão sobre esta proposta.

**Comment by fdaciuk** [comment]
Acho massa a ideia @joao-parana! Já tem alguma base para essa implementação? Nâo sei se seria o ideal estar dentro do Odin, mas talvez um projeto à parte, funcionando como um service.

**Comment by joao-parana** [comment]
Sim @fdaciuk, já fiz umas provas de conceito e pretendo amadurecer um pouco mais. Seria importante saber dos colaboradores do projeto Odin quais os principais problemas enfrentados neste gerenciamento de ciclo de vida de projeto Wordpress, para que possamos desenhar uma solução eficiente e segura. Por exemplo a min incomoda o fato da configuração estar no arquivo `wp-config.php` na raiz do site. Seria melhor se pudéssemos segregar para um diretório específico de configuração. Eu não conheço o Wordpress o suficiente para implementar esta modificação. Gostaria de sugestões de como fazer isso, via plugin por exemplo, mas não sei se é possível desta forma. Além disso o nosso objetivo deverá ser o aumento de produtividade para os usuários do Tema e desta forma a opinião do grupo é fundamental para termos uma arquitetura robusta.

**Comment by fdaciuk** [comment]
Na real, o `wp-config.php` não tem a ver diretamente com o tema. Ele faz parte da instalação do WP. E você pode colocá-lo até um nível antes da instalação do WP, que ele vai ser encontrado norlmalmente. Imagine que seu diretório público está em `/var/www/public_html`. O `wp-config.php` pode ficar em `/var/www` que o WP encontra ele, e mantém ele seguro, longe do diretório público.

Mas o que eu acho que o container poderia facilitar, seria já ter uma pré-instalação do WP, com BD configurado e o arquivo `wp-config.php` poderia ser sobrescrito por configurações passadas por argumento no comando de `run` do docker.

Deixando tudo isso pronto, daria só para apontar para o diretório onde ficaria o tema e sair codando. Acho que já ia facilitar bastante ;)

**Comment by adammacias** [comment]
Sou leigo nesse assunto, Docker, mas o [wp-cli](http://wp-cli.org/) já não faz essas coisas?

**Comment by fdaciuk** [comment]
Não exatamente @adammacias.. o Docker cria um ambiente virtual (mais ou menos como o vagrant, mas mais rápido e mais integrado com o sistema). 

O wp-cli pode inclusive estar dentro de um container Docker ;)

**Comment by joao-parana** [comment]
oi  @fdaciuk eu concordo contigo em genro número e grau nesta questão do `wp-config.php`  não ter a ver com o tema. Mas lembre-se que o contêiner Docker deve facilitar o deploy do Wordpress para prover a melhoria na produtividade, então desejariamos passar as configurações no momento de colocar o contêiner para rodar como você citou. Por isso citei o problema do `wp-config.php`. A propósito gostaria de saber como posso colocar o wp-config.php fora e fazer com que o Wordpress acesse corretamente. Onde tenho de alterar ?

Faltou dizer que na minha prova de conceito já passo os parâmetros em tempo de execução e graças ao uso do comando `sed`, `cat` e outros, altero o arquivo `wp-config.php` de acordo com os parâmetros passados, além de criar o banco de dados. Mas acho que tem espaço para melhorar e por isso gostaria de ouvir a opinião da comunidade.

**Comment by fdaciuk** [comment]
Massa @joao-parana! Sobre o wp-config.php, é só colocar ele um nível antes da instalação do WP que ele reconhece, não precisa configurar nada ;)

**Comment by joao-parana** [comment]
oi @fdaciuk, estou procurando uma solução mas abrangente para este problema da localização do `wp-config.php`, algo que funcione também no serviço de Hospedagem onde dentro do diretório home aparece a lista de todos os sites hospedados e neste caso mover um diretório para cima não funcionaria pois afetaria outros sites existentes. [Neste post](https://www.ostraining.com/blog/wordpress/wordpress-config/) o autor apresenta outras alternativas: 

1. colocar num subdiretório
2. usar instrução include do PHP

Seria bom adotarmos uma solução que pudesse funcionar com multisites, em ambiente de desenvolvimento, em ambiente de homologação e produção e que pudessemos facilmente promover de um ambiente para outro. 

Gostaria de saber sua opinião sobre os prós e contra de cada abordagem, considerando segurança, produtividade e eficiência, simplicidade, etc.

**Comment by fdaciuk** [comment]
Nesse caso, acho que o mais simples seria poder passar o caminho do wp-config.php na hora de rodar o Docker. O que acha? Deixa por default no diretório da instalação do WP, e deixa a opção de passar o caminho ;)

**Comment by iszwnc** [comment]
Como anda esta *issue*? Eu abri uma *issue* que menciona esta aqui, gostaria de discutir a ideia, e coloca-la o mais rápido possível em prática.

**Comment by joao-parana** [comment]
oi @iszwnc lamentavelmente tive de parar este estudo devido a dimensão que o projeto no qual trabalho tomou nos últimos meses. O escopo foi ampliado e não estou tendo tempo livre para tocar a solução deste problema.

**Comment by iszwnc** [comment]
E então @fdaciuk e @joao-parana? Tenho carta branca pra começar? Quando puderem gostaria de debater não só isso mas também o assunto principal da issue #410 com o @fdaciuk

**Comment by fdaciuk** [comment]
Fala @iszwnc! Estou meio afastado do projeto no momento, mas envie um pull request com a sua proposta, que fica mais fácil da galera discutir e ver o que faz sentido =)

**Comment by adammacias** [comment]
Pessoal, registrei a [organização wpbrasil](https://hub.docker.com/u/wpbrasil/dashboard/) no hub oficial do Docker para nossa comunidade. Vou adicionar vocês lá :dancers:

**Comment by fdaciuk** [comment]
@adammacias olhei essa foto e achei que vc tava cabeludo :joy: :joy:

**Comment by adammacias** [comment]
Acho que está cada vez mais interessante utilizar o Docker, não sei se isso é interessante fazer aqui (Odin), mas talvez sim em outro repositório a parte, onde o Odin possa vir como tema e já com as dependências necessárias para rodar o Odin. Vamos levar essa discussão para a versão 3 \o/

**Comment by adammacias** [comment]
Implementar testes unitários #410
