### ISSUE TITLE
Classe de metabox para tela de edição de termos de uma taxonomia

### ISSUE THREAD

**Issue by matheusgimenez** [wpbrasil/odin#311]
Galera, tô afim de implementar uma classe de metabox para categorias usando como base a classe de metabox mesmo.

Gostaria de saber a opinião de vcs, antes de sair soltando pull request sem avisar, hehe.

**Comment by AdsonCicilioti** [comment]
Pra adicionar fields nas telas de criação de categorias?

**Comment by matheusgimenez** [comment]
Sim, na tela de criação/edição de taxonomias (corrigi o titulo agora). Algo como o ACF faz.

**Comment by matheusgimenez** [comment]
Gostaria de ter um OK (ou pelo menos um não) até o fds para poder fazer a tal classe.

Abraços.

**Comment by allysonsouza** [comment]
O chato:"Tela edição de termos de uma taxonomia"

Eu acho que seria interessante, já em alguns projetos instalei ACF apenas para adicionar um único campo adicional na criação de termos de uma taxonomia.

**Comment by matheusgimenez** [comment]
@allysonsouza Sim, já passei muito por isso.

Só não entendi a primeira parte da sua mensagem :(

**Comment by allysonsouza** [comment]
É porquê se for pegar ao pé da letra não existe página de edição de taxonomia, a taxonomia tá criada, o que editamos são apenas termos :P

**Comment by matheusgimenez** [comment]
Ahh sim, hehe. Nem atentei muito a isso.. vou trocar o titulo, sorry hehe

**Comment by LuwkasLima** [comment]
Manda bala @matheusgimenez!
