### ISSUE TITLE
Erro upload de arquivo Odin Contact Form

### ISSUE THREAD

**Issue by AdsonCicilioti** [wpbrasil/odin#317]
Olá pessoal!

Copiei o código de exemplo na documentação da Class Contact Form, e a única modificação foi mudar a opção `required` do field para `false`, para que não seja obrigatório o envio de arquivos em meu form, mas mesmo assim é retornado o alert `Arquivo No file was uploaded..`
![shot-er-file](https://cloud.githubusercontent.com/assets/6278398/8757822/203c9be0-2cb4-11e5-871b-8b96c50d14bf.JPG)

Dei uma olhada no código mas não consegui achar algo que poderia comprometer essa função.

Se alguém puder ajudar será nice!

**Comment by romuloctba** [comment]
Testa aí https://github.com/wpbrasil/odin/pull/321

(alteração: https://github.com/wpbrasil/odin/commit/a02aad8eccbe9a775c206fbc001e2df55b8a4a45 )

**Comment by rudwolf** [comment]
To confuso, isto está aberto ainda ou já foi resolvido, se eu puder gostaria de ajudar se ainda for preciso.

**Comment by AdsonCicilioti** [comment]
Então @rudwolf da um sak no #321 onde o Claudio Sanchez ficou de verificar um fix para o problema. Se quiser vale fazer um teste aí.. Mas ainda não tá rolando.

**Comment by adammacias** [comment]
Temos que testar isso aí, faz tanto que o issue "morreu" que não sabemos se de fato o problema foi solucionado hehe.

**Comment by AdsonCicilioti** [comment]
O problema está no uso do media_handle_upload com outros campos no mesmo form. Ele não reconhece outros campos a não ser que eles sirvam para abastecer o title, alt da imagem/mídia, pois foi feito apenas para fazer upload de mídia.
Na linha [680 do abstracts](https://github.com/wpbrasil/odin/blob/master/core/classes/abstracts/abstract-front-end-form.php#L680) temos uma condicional que checa se há erro no upload e o mesmo está retornando positivo e apresenta o erro printado na issue, mesmo se o input file estiver sem o required.

Tentei add uma condicional para checar se o required é true, assim, se positivo, teremos duas camadas de validação no input file XD. o problema é que se falso não terá nenhuma validação.
```
if ( is_wp_error( $attachment_id ) ) {
	$error = apply_filters( 'odin_front_end_form_upload_error_' . $this->id, sprintf( '%s %s.', '<strong>' . $this->get_field_label( $id ) . '</strong>', $attachment_id->get_error_message() ) );
	$this->set_errors( $error );
} else {
	$attachments[ $id ] = array(
		'file' => get_attached_file( $attachment_id ),
		'url'  => wp_get_attachment_url( $attachment_id )
	);
}
```
Outra solução mais segura porém meio tosca seria excluir o erro *No file was uploaded.* da condicional:
```
if ( is_wp_error( $attachment_id ) && $attachment_id->get_error_message() !== 'No file was uploaded.' ) ) {
	$error = apply_filters( 'odin_front_end_form_upload_error_' . $this->id, sprintf( '%s %s.', '<strong>' . $this->get_field_label( $id ) . '</strong>', $attachment_id->get_error_message() ) );
	$this->set_errors( $error );
} else {
   ...
}
```

Bom, testei as duas formas e obtive sucesso, os emails chegam com e sem anexo,
Assim o usuário consegue enviar o formulário com o file input vazio para os casos onde este precise ser opcional ( 'required' => false ).

Resta saber se exite maneira melhor de fazer isso... Só consegui ir até aqui.

**Comment by AdsonCicilioti** [comment]
Acho que achei uma forma melhor e mais genérica, checando o peso do arquivo em bytes. Tentei checar se existe arquivo com empty() mas não rolou.. Ao printar com count() sempre retorna 1 mesmo com o input vazio, então fui pro `size` mesmo.
Então adicionei `&& $_FILES[ $id ][ 'size' ] > 0 `. assim só haverá a validação do WP_error se existir peso em bytes. Acho que já dá pra preparar um PR.

Feliz ano Novo pra todos!
