### ISSUE TITLE
Documentação para class-term-meta

### ISSUE THREAD

**Issue by adammacias** [wpbrasil/odin#320]
ref #318

**Comment by adammacias** [comment]
@matheusgimenez tem a moral fazer essa para nossa [wiki](https://github.com/wpbrasil/odin/wiki) já que tu que [adicionou Metabox para tela de edição de terms](https://github.com/wpbrasil/odin/pull/318)?   :smiley:

**Comment by matheusgimenez** [comment]
Eu pretendo fazer.. só tô esperando vagar um tempo aqui que eu tiver com animo de fazer. Provavelmente vai ser no fim de semana. Mas deixa comigo! :+1:

**Comment by adammacias** [comment]
Tranquilo man, se eu conseguir faço antes, mas ta osso aqui por hora :+1: :smile:

**Comment by matheusgimenez** [comment]
Se puderem deem uma revisada: 
https://github.com/wpbrasil/odin/wiki/Classe-Odin_User_Meta

Usei como base a documentação do Metabox

**Comment by matheusgimenez** [comment]
Ops.. coloquei o link errado no comentário acima, hehe

https://github.com/wpbrasil/odin/wiki/Classe-Odin_Term_Meta

**Comment by matheusgimenez** [comment]
@adammacias Fecha esse issue aqui, hehe.. ou falta alguma coisa ainda na documentação?

**Comment by adammacias** [comment]
:yum: :+1:
