### ISSUE TITLE
Modificar o rótulo do button no odin_contact_form

### ISSUE THREAD

**Issue by gustavaum** [wpbrasil/odin#326]
Olá pessoal,

Dei uma lida na documentação e não achei um caminho em que eu possa alterar o rótulo do botão usando o odin_contact_form.
É possível eu alterar esse rótulo de "enviar" para uma mensagem que eu queira?

(desculpa se não for elegante postar esse tipo de dúvida aqui =S )
obrigado desde já

**Comment by adammacias** [comment]
@gustavaum não tem suporte para isso ainda, você pode tentar fazer isso na hora de renderizar seu formulário

```php
echo str_replace( "enviar", "confirmar", odin_contact_form()->render() );
```

\- ou - 

Você mudar no arquivo fonte [abstract-front-end-form.php#L282](https://github.com/wpbrasil/odin/blob/e2b279a4823dc7d1cbb979ad2f5958e80615cf0e/core/classes/abstracts/abstract-front-end-form.php#L282) que eu **não recomendo**, pois faz parte do core do Odin.

**Comment by AdsonCicilioti** [comment]
@gustavaum acho que rola criar como `attr` no shortcode. Mas teremos que mexer no core @adammacias, deixando o texto padrão (enviar) com a possibilidade de modificá-lo por shortcode, tipo assim: `[contact_form label="Confirmar"]`

**Comment by gustavaum** [comment]
Obrigado pela ajuda =D

Odin salvando vidas hehehe

**Comment by adammacias** [comment]
Sim @AdsonCicilioti , seria interessente, abre uma issue para isso. ;D

@gustavaum fechando a issue então! :)
