### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by vinigarcia87** [wpbrasil/odin#329]
Como o odin resolve o problema dos autoprefixers?
Eu sou novo no grunt e nao consegui indentificar no gruntfile como o Odin aplica os prefixers no bootstrap.
Alguem poderia me explicar exatamente como isso funciona? :)
Obrigado!

**Comment by AdsonCicilioti** [comment]
@vinigarcia87, ficou em desuso, pelo menos no odin, pois o odin já usa o bootstrap (Sass) mais atual que em seus mixins já possui os prefixos necessários para suportar os Browsers mais usados.

É bem verdade que ele suporta os browsers mais modernos, mas você ainda encontra, como por exemplo no mixin `opacity`que suporta transparencia para o IE8.

Você pode dar uma checada no arquivo `_vendor-prefixes.scss, que possui diversos mixins modernos todos com os prefixos necessários para rodar na maioria dos browsers (modernos e ie9+).

Bom acredito que por essa razão não foi incluído o **autoprefixer** no grunt do Odin.

Mas nada que impeça de você fazer no seu projeto pessoal, uma vez que você possa vir a trabalhar com CSS flex (etc).

**Comment by adammacias** [comment]
O pacote que usamos para renderizar o CSS, [faz o uso **compass**](https://github.com/gruntjs/grunt-contrib-sass#compass), você pode usa-la configurando o seu `Gruntfile.js`.

**Comment by claudiosmweb** [comment]
*autoprefixer*?
Estamos em 2010 de novo?

**Comment by vinigarcia87** [comment]
Agradeço muito a resposta galera!
Nao sei se voltamos a 2010... mas como eu disse, sou novo nesse assunto e gostaria de entender pq o Odin nao usa o autoprefixer.
vlw!

**Comment by claudiosmweb** [comment]
@vinigarcia87 porque ninguém usa mais autoprefixer, isso é coisa de idoso.

**Comment by claudiosmweb** [comment]
Alias, escrever CSS com mil prefixos hoje em dia é provar que não manja ABSOLUTAMENTE PORRA NENHUMA de CSS.

**Comment by vinigarcia87** [comment]
ah muito obrigado por deixar claro, parceiro

**Comment by romuloctba** [comment]
praticamente um alazão de delicadeza
