### ISSUE TITLE
Odin_Metabox - possível bug 'image_plupload'

### ISSUE THREAD

**Issue by luizrw** [wpbrasil/odin#333]
Usando a classe Odin_Metabox criei um campo do tipo 'image_plupload'. Pra recuperar usei um foreach simples, como diz a documentação:

https://github.com/wpbrasil/odin/wiki/Classe-Odin_Metabox#image_plupload

"No seu tema é necessário converter essa informação para um array e assim utilizar as funções mostradas no campo image.
Veja um exemplo de como utilizar:"

```php
foreach ( explode( ',', $gallery ) as $image_id ) {
    // Sua mágica aqui!
}
```
Recupero os valores normais. Mas se, por exemplo, eu tenho duas imagens nesse campo e excluo uma delas, no front-end 'recupera' uma imagem vazia.

Na documentação diz que estes campos salvam os ids das imagens, separando cada um por virgula. Notei no banco de dados que ao salvar a primeira imagem a vírgula não é adicionada, salvando a segunda já é adicionada normalmente, mas ao excluir uma das imagens a vírgula continua no banco. Talvez por essa vírgula ao tentar recuperar as imagens imprima uma imagem vazia.

**Comment by pauloiankoski** [comment]
Enviei correção para este problema há pouco. https://github.com/wpbrasil/odin/blob/master/core/assets/js/admin.js
