### ISSUE TITLE
Pergunta bem novato , Como usar wordpress como web site? não quero blog e sim web site

### ISSUE THREAD

**Issue by joaovitorpf** [wpbrasil/odin#336]
olá pessoal , sou bem novato mas vamos la conheci esse framework  pela internet e gostaria de saber como usar ele como site igual vi na parte de cases  muitos que nem parecem wordpress , gostaria de saber como usar como web site é so apenas usar como html sem usar os comandos php que o wordpress usa para aparecer certas coisas . 

Entao minha pergunta é simples como usar wordpress como site.

**Comment by valeriosouza** [comment]
Rapaz

**Comment by fdaciuk** [comment]
Rapaz²

**Comment by nandomoreirame** [comment]
Rapaz³

**Comment by joaovitorpf** [comment]
?

**Comment by celsofabri** [comment]
Não entendir

**Comment by fdaciuk** [comment]
@joaovitorpf a forma como você vai utilizar o WordPress independe se você vai utilizar um framework ou não. Você precisa conhecer WordPress, HTML, CSS e JS. Com isso, você faz o que você quiser com WordPress!

Use esse canal para dúvidas específicas sobre o Odin! Para dúvidas sobre WordPress, use o [fórum oficial](https://br.forums.wordpress.org/) ou o [grupo no Facebook](https://www.facebook.com/groups/wordpress.brasil/) :)

**Comment by romuloctba** [comment]
Desculpa comentar Issue fechado, mas acho que nosso amigo poderia gostar
deste material:
http://pt.slideshare.net/rafaelfunchal/fazendo-milagres-com-wordpress

2015-08-16 16:27 GMT-03:00 Fernando Daciuk <notifications@github.com>:
