### ISSUE TITLE
Suporte para ícone (Favicon)

### ISSUE THREAD

**Issue by adammacias** [wpbrasil/odin#337]
Pessoal, como a alguns de vocês já sabem, a [versão 4.3](https://wordpress.org/news/2015/08/billie/) do WordPress permite o usuário fazer upload de um ícone para o tema. Acho que com isso, cria-se o seguinte dilema:

1. [Deletar o ícone padrão do Odin](https://github.com/wpbrasil/odin/blob/master/header.php#L17) e deixar o trabalho para WordPress.
2. Criar uma verificação: Caso não exista nenhum ícone customizado, força o tema a continuar com o ícone padrão do Odin.

![WordPress 4.3](http://s.w.org/images/core/4.3/site-icon-customizer.png)

O que vocês acham melhor? :smile:

**Comment by matheusgimenez** [comment]
Por mim vai via condicional mesmo.

**Comment by everaldomatias** [comment]
Voto no item [2] também.

**Comment by rafaelfunchal** [comment]
Opção 2 também

**Comment by matheusilario** [comment]
Opção 2

**Comment by matheusgimenez** [comment]
Fiz um PR já se forem usar a opção dois. 

Abraços

**Comment by adammacias** [comment]
Valeu pessoal
