### ISSUE TITLE
Carrossel de imagens 'image_plupload' no odin

### ISSUE THREAD

**Issue by daviddesigner** [wpbrasil/odin#340]
Pessoal, estou começando a desenvolver temas utilizando o odin. Criei algumas opções de tema e dentre elas tenho um campo "image_plupload" que pretendo utilizar as imagens em um carrossel no tema. 

Estou tentando exibir as imagens 
<?php           
            foreach ( explode( ',', $gallery ) as $image_id ) {
             $clientes = get_option( 'clientes' );
            echo '<ul>';
            echo '<li>';  
            echo $txt_header['logo_cliente'];
            echo '</li>';
            echo '</ul>';
                }            
            ?> 
mas não aparece nada, alguem pode me ajudar?

Muito grato,

**Comment by adammacias** [comment]
Use [markdown](https://guides.github.com/features/mastering-markdown/#examples) quando for mostrar pedaços de códigos.

Olha a diferença:

```php
<?php           
 foreach ( explode( ',', $gallery ) as $image_id ) {
   $clientes = get_option( 'clientes' );
      echo '<ul>';
      echo '<li>';  
      echo $txt_header['logo_cliente'];
      echo '</li>';
      echo '</ul>';
  }            
?> 
```

O que acontece nesse exemplo que você deve ter visto [aqui](https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options#image_plupload), é que a cada loop você consegue pegar o **IDs** das imagens através de `$image_id`.

**Comment by daviddesigner** [comment]
Olá adammacias, grato pela resposta. Na realidade não estou entendendo muito bem... eu preciso que cada imagem fique assim:
![tela-git](https://cloud.githubusercontent.com/assets/2729185/9383276/384167d2-471e-11e5-9783-61196cab254e.jpg)

seria possível?

Ps: Não consegui colocar o peço do código usando o markdown :(

grato

**Comment by vilaboim** [comment]
David, você vai precisar chamar o [campo](https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options#utilizando-os-campos), fazer o [foreach](https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options#image_plupload), e dentro dele chamar as [imagens](https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options#image).

**Comment by matheusilario** [comment]
Boa tarde David, utilizei da seguinte forma:
```
<?php
			$gallery =get_post_meta( $post->ID,'galeria', true );
			foreach ( explode( ',', $gallery ) as $image_id ) {
				$thumbnail = wp_get_attachment_image_src( $image_id, 'thumbnail' ); // returns an array
				$full = wp_get_attachment_image_src( $image_id, 'large' ); // returns an array
				if( $full ) {?>
					<a href="<?php echo $full[0]; ?>" rel="lightbox[gallery]">
						<div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 image-galery">
							<img src="<?php echo $thumbnail[0]; ?>" alt="<?php the_title();?>" class="img-thumbnail img-responsive">
						</div>
					</a>
				<?php }
			} ?>
```
