### ISSUE TITLE
Implementar Field de Mapas para as classes de Options, Metabox e etc

### ISSUE THREAD

**Issue by matheusgimenez** [wpbrasil/odin#341]
O que acham de adicionar fields para maps, nas classes de metabox?

Penso em fazer de uma forma que possamos usar o google maps ou o open street maps.

Enfim, opinem :)

**Comment by adammacias** [comment]
É uma boa, pensei até que já tivesse rs.

**Comment by allysonsouza** [comment]
Acho que é interessante. Antes não tínhamos classe para meta boxes em termos, ai eu instalava o ACF :P, esse também é um field que ele possui que pode ser útil em alguns projetos. :+1:

**Comment by AdsonCicilioti** [comment]
Vale inclusive um Campo para incluir Estilos para os Mapas (do Google) com código Json, como no Snazzy Maps - https://snazzymaps.com

**Comment by luizbills** [comment]
:+1:
