### ISSUE TITLE
Duplicação do conteúdo ao ativar o plugin NextGen Gallery

### ISSUE THREAD

**Issue by Rahmon** [wpbrasil/odin#342]
Testei outros plugins que tem o mesmo propósito do NextGen Gallery, mas apenas este apresentou o problema.

![odin-bug](https://cloud.githubusercontent.com/assets/6010232/9468340/85fc7e10-4b17-11e5-81cd-9975c8f4e378.png)

**Comment by adammacias** [comment]
@Rahmon explica melhor sua dúvida por favor.

Chutando uma solução sem saber seu problema, acho que seu tema deve estar chamando mais de uma vez o `get_header()`.

**Comment by rafaelfunchal** [comment]
Instalei o NextGen Gallery em localhost com Odin sem alterações (master) e não consegui replicar o erro.

**Comment by Rahmon** [comment]
@adammacias eu também imaginei que o tema estivesse chamando duas vezes uma mesma função. Mas o que me deixou intrigado foi o fato de isso acontecer apenas quando eu ativo o plugin NextGen Gallery.

@rafaelfunchal vou verificar se tem algum outro plugin ativado. Se não, vou fazer uma nova instalação e ver se o problema continua.

Obrigado pelas contribuições.

**Comment by adammacias** [comment]
Ok! Vou fechar o tópico então, pois acredito que não seja incompatibilidade com o Odin, já que o @rafaelfunchal deu o feedback positivo :smile:
