### ISSUE TITLE
Dúvida Odin_pagination

### ISSUE THREAD

**Issue by wandersondantas** [wpbrasil/odin#344]
Pessoal, bom dia, gostei muito de utilizar o odin como framework, porém algumas dúvidas surgiram, quando implemento o odin_pagination, ele aparece os mesmos posts nas duas páginas, será que alguém pode me ajudar?

**Comment by adammacias** [comment]
Como você está implementando @wandersondantas ?

**Comment by rafaelfunchal** [comment]
Parece que está alterando o loop principal em algum momento.

Poderia verificar isso, @wandersondantas ?

**Comment by wandersondantas** [comment]
Meu código está assim:

<?php $query = new WP_Query(  array( 'post_type' => 'dicas', 'showposts' => 4) ); ?>
    
                <?php
                    // Start the Loop.
                    while ( $query->have_posts() ) : $query->the_post();
                ?>
                    
                    <div class="col-xs-12 col-sm-12 col-md-12 lista-dicas">
                    	<div class="row">
                            <div class="data-dicas col-md-1 col-sm-2 col-xs-6">
                                <div class="dia"><span><?php the_time('d'); ?></span></div>
                                <div class="mes"><span><?php the_date('M'); ?></span></div>
                            </div>
                            <?php if(has_post_thumbnail( )): ?>
                            <div class="img-dicas col-md-2 col-sm-2 col-xs-6">
                                <?php the_post_thumbnail(); ?>
                            </div>
                            <div class="content-dicas col-md-9 col-sm-8 col-xs-12">
                            	<h3><?php the_title(); ?></h3>
                                <?php echo content(50); ?>
                            </div>
                            <?php elseif(!has_post_thumbnail( )): ?>
                            <div class="content-dicas no-thumb col-md-11 col-sm-10 col-xs-6">
                            	<h3><?php the_title(); ?></h3>
                                <?php echo content(50); ?>
                            </div>
                            <?php endif; ?>
                        </div>
                        
                    </div>
                    
                <?php
                    endwhile;
                ?>
                
                <?php echo odin_pagination( 2, 1, false, $query ); ?>

**Comment by leobaiano** [comment]
Comece trocando `showposts` por `posts_per_page`.

Em qual arquivo você está fazendo isso ai? Para listar os posts de um post type você utiliza o arquivo `archive.php` ou `archive-slug.php` para ser mais especifico. No seu caso o normal seria criar o `archive-dicas.php` e eu recomendaria o uso de `pre_get_posts` para alterar a quantidade de posts que serão exibidos.

Outra coisa, da uma olhada na função `[odin_pagination()](https://gist.github.com/claudiosmweb/6402041)`, o terceiro parâmetro recebe `true` ou `false` e não o objeto `WP_Query()` como você fez.

Resumindo, primeiro troca o `showposts` e testa. Depois deixa o loop padrão, sem `WP_Query()` e testa. Por ultimo, se funcionar tenta usar `pre_get_posts` para alterar a quantidade de posts que serão exibidos.

**Comment by rafaelfunchal** [comment]
Mais alguns detalhes:

- Você não precisa acessar diretamente essa função. Dê uma olhada nesse [exemplo do archive.php](https://github.com/wpbrasil/odin/blob/master/archive.php#L46) onde usamos a `odin_paging_nav()`.
- Perceba também que a função precisa estar dentro do `if`, caso contrário ela não receberá a query.

**Comment by wandersondantas** [comment]
Eu utilizei o arquivo page-{slug}.php, mas até agora não resolvi, demorei a responder pois tinha dado uma pausa no projeto, vou tentar mudar para o archive.php e vê se resolve.

**Comment by rafaelfunchal** [comment]
Como a paginação funciona corretamente quando aplicada antes de fechar o if do loop ([veja o exemplo](https://github.com/wpbrasil/odin/blob/master/archive.php#L46)), estou fechando esse issue.
