### ISSUE TITLE
Criar método na classe Odin_Options_Helper para verificar se a opção foi setada

### ISSUE THREAD

**Issue by Rahmon** [wpbrasil/odin#345]
O que vocês acham de criar um método na classe Odin_Options_Helper para verificar se uma opção foi setada? 

Tenho usado a função `__toString()` para isso:
```php
if ( $option_text->__toString() )
{
...
}
```

Mas será que não vale a pena criar um método específico?

**Comment by claudiosmweb** [comment]
Não realmente necessário.
