### ISSUE TITLE
problema function field_image_plupload, ao re-ordenar as imagens, é criado um item vazio

### ISSUE THREAD

**Issue by brunowindrop** [wpbrasil/odin#347]
Ao re-ordenar as imagens tanto no metabox quanto no options_theme pelo pupload ele cria um item vazio. Fazia de tudo e não consigia mais tirar o item vazio. Resolvi da seguinte forma, :
(não sei se é gambiarra e acho tenso mecher na pasta core. Se realmente for um problema, acho que fica fácil arrumar uma soução oficial)
no arquivo: core/classes/class-metabox.php
protected function field_image_plupload( $id, $current ) {
		$valor = "";

			if (strlen($current) > 0) {
				$quantidade = strlen($current) - 1;

				if ($current[$quantidade] == ",") {

					$explosion = explode(",", $current);
					for ($i = 0; $i < count($explosion)-1; $i++) {

						if (strlen($explosion[$i]) > 0) {

							if ($i < (count($explosion)-2) ) {
								$valor .= $explosion[$i] . ",";
							} else {								
								$valor .= $explosion[$i];
							}
						}

					}
					$current = $valor;
				}

			}

**Comment by claudiosmweb** [comment]
Não consegui reproduzir o que você esta falando.

**Comment by brunowindrop** [comment]
Cria uma galeria utilizando o pupload e em seguida reordena as imagens da galeria criada, vai na exibição e inspeciona a galeria, vai ser criada uma imagem vazia automaticamente. Se preferir, ponho em um site de teste ou dou print pra melhor análise.

**Comment by pauloiankoski** [comment]
@brunowindrop eu já corrigi esta falha há 4 meses. Verifica se você está utilizando a versão mais atual do Odin. ;)

**Comment by AdsonCicilioti** [comment]
@pauloiankoski referencia seu fix aqui. ;)
