### ISSUE TITLE
Adicionar schema BlogPosting e role="article"

### ISSUE THREAD

**Issue by nandomoreirame** [wpbrasil/odin#348]
Olá galera!

Poderíamos deixar como padrão alguns atributos schema na tag article e em outras tags importantes para um site.

Podemos adicionar role="article" também, o que acham?

**Comment by brunopulis** [comment]
@nandomoreirame A role="article" não precisa de ser incluida mais, por padrão os leitores de tela conseguem interpretar que a tag <article> já se referencia a um <article>. Deve ser utilizado somente em casos especificos. 

Segue um link explicando um pouco :) 

http://html5doctor.com/using-aria-in-html/
