### ISSUE TITLE
Função de atualização para o tema

### ISSUE THREAD

**Issue by WPires** [wpbrasil/odin#350]
Olá,

gostaria de saber como eu posso criar uma função de atualização para o um tema utilizando o Odin.

A ideia é que essa função busque em um servidor externo a versão mais recente do tema e caso necessário baixe as novas versões dos arquivos e substitua pelos atuais de forma automática.
Se tiverem links de artigos aonde eu consiga saber como fazer isto, já é o suficiente.

Se este não for o lugar certo para fazer este tipo de pedido, me desculpem.

Att. Washington.

**Comment by rafaelfunchal** [comment]
Isso não tem nada relacionado com Odin, @WPires, mas sim com WordPress em geral.

Você pode pesquisar isso de um modo geral.

**Comment by WPires** [comment]
Entendo, obrigado.
