### ISSUE TITLE
Parâmetros das shortcodes

### ISSUE THREAD

**Issue by tiagofabre** [wpbrasil/odin#352]
Alguns parâmetros das shortcodes "Group button" e "Progress" não estão funcionando OU eu não entendi como inserir. Gostaria de saber se isso é bug ou se eu que inseri errado ( dependendo da resposta vou precisar corrigir o menu de shortcodes)

Segue os exemplos
![group](https://cloud.githubusercontent.com/assets/1669523/10084252/d172cf7e-62d8-11e5-83df-160f0a66a4c5.png)
![progress](https://cloud.githubusercontent.com/assets/1669523/10084063/c8ec75c2-62d7-11e5-9a45-d6a2e1673af9.PNG)

**Comment by claudiosmweb** [comment]
Na real você entendeu errado.
Por exemplo na barra de progresso, é o próprio bootstrap que [ede para o valor ser de 0 a 100%.
