### ISSUE TITLE
Lista de Taxonomia criada

### ISSUE THREAD

**Issue by wandersondantas** [wpbrasil/odin#353]
Boa tarde pessoal.

Como faço pra exibir no meu tema, uma lista de uma taxonomia que criei para um post personalizado??

**Comment by allysonsouza** [comment]
O que é uma "lista de uma taxonomia"? Seria a lista de termos de uma taxonomia? Se for, você faria da mesma forma que faria sem o Odin. https://codex.wordpress.org/Function_Reference/get_terms

**Comment by wandersondantas** [comment]
Isso mesmo @allysonsouza , ainda estou me acostumando com os termos, consegui resolver, agora eu queria uma outra ajuda.

Essa página de produtos: http://wandersondantas.com/clientes/kilder/produtos/ , é um custom post, o que eu queria fazer era, poder adicionar uma categoria nova e aparecer na lista (já consegui), a bronca é, ao clicar em cada categoria, só aparecer os produtos daquela categoria e, se possível, sem precisar carregar outra página

**Comment by claudiosmweb** [comment]
Faça do mesmo jeito que você faria com o WordPress normalmente.
