### ISSUE TITLE
Breadcrumb sub-categoria maior que o segundo nível

### ISSUE THREAD

**Issue by guilima** [wpbrasil/odin#359]
Na página template de uma sub-categoria maior que o segundo nível ex.:
* Notícias
 * Ensino Fundamental
   * **Fundamental 7ª série**

Acontece o seguinte bug:
![Imagem breadcrumb bug](http://i.imgur.com/5Vo98GL.png)
Tanto a categoria 'Notícia' e 'Ensino Fundamental' estão ficando contidos no mesmo bloco `<li></li>` uma vez que a função `get_category_parents()` chama todas as categorias pais incluindo as categorias ancestrais. [(helpers.php linha 340)](https://github.com/wpbrasil/odin/blob/master/core/helpers.php)

Arrumei o problema com css porém semânticamente o código em html se mantém errado. Como não consegui pensar em uma solução melhor resolvi abrir a issue e aguardar outras ideias.

**Comment by AdsonCicilioti** [comment]
Testa aí @guilima #360 

Aqui foi de boa! :D

**Comment by guilima** [comment]
Perfeito @AdsonCicilioti agora as categorias estão aparecendo corretamente no breadcrumb. 
Valeu pela solução.
