### ISSUE TITLE
[Solicitação de revisão] Adicionando ícones para os Post Types no wp-admin

### ISSUE THREAD

**Issue by romuloctba** [wpbrasil/odin#363]
Achei que seria relevante essa informação na WIKI, então editei.

Peço que avaliem e me digam se acham que está ok.

https://github.com/wpbrasil/odin/wiki/Classe-Odin_Post_Type#adicionando-%C3%ADcones-para-o-post-type-no-wp-admin

**Comment by fdaciuk** [comment]
LGTM :+1:

**Comment by romuloctba** [comment]
blz vou fechar. Se alguém visualizar aqui e quiser indicar alguma alteração ou fazer alguma obs, sinta-se a vontade para reabrir a issue.

^^ :octocat:
