### ISSUE TITLE
Checkbox com default 1 retorna undefined index

### ISSUE THREAD

**Issue by romuloctba** [wpbrasil/odin#364]
Se criarmos uma checkbox com default 1, embora ela apareça checada nas theme options, ao solicitar ela pelo php, recebemos `undefined index`, já que ela não é definida.

Para solicitar corretamente no front precisamos usar um fallback com `isset()`, ou salvar a checkbox desmarcada, e depois marcando novamente ela.

**Comment by romuloctba** [comment]
```
$configs = get_option('minha_section');
$texto_instagram = $configs['texto_instagram']; //funciona pq é um texto
$exibe_instagram  = $configs['exibe_instagram']; // retorna undefined index, pq o default dela é 1
$exibe_instagram  = isset($configs['exibe_instagram']) ? $configs['exibe_instagram'] : false; // assim vai de boas
```

**Comment by romuloctba** [comment]
é que não achei a linha ainda pra poder editar no `class-metabox.php`, mas pretendo fazer.. por isso abri a issue. caso alguem faça antes, td bem, por enqnto to usando o isset().

**Comment by fdaciuk** [comment]
@romuloctba já tem um bug aberto pra isso em https://github.com/wpbrasil/odin/issues/124.

Tem algumas ideias de solução lá, mas ainda não foi testado.

**Comment by romuloctba** [comment]
ih carai, foi mal
