### ISSUE TITLE
Links de exemplo quebrados

### ISSUE THREAD

**Issue by killuawax** [wpbrasil/odin#368]
Os links de exemplo dos shortcodes estão todos quebrados.
Abaixo os link:
https://claudiosmweb.com/shortcodes/buttons/
https://claudiosmweb.com/shortcodes/button-groups/
https://claudiosmweb.com/shortcodes/alerts/
https://claudiosmweb.com/shortcodes/labels/
https://claudiosmweb.com/shortcodes/badges/
https://claudiosmweb.com/shortcodes/icons/
https://claudiosmweb.com/shortcodes/wells/
https://claudiosmweb.com/shortcodes/tables/
https://claudiosmweb.com/shortcodes/grids/
https://claudiosmweb.com/shortcodes/progress-bar/
https://claudiosmweb.com/shortcodes/panels/
https://claudiosmweb.com/shortcodes/tabs/
https://claudiosmweb.com/shortcodes/accordions-collapses/
https://claudiosmweb.com/shortcodes/tooltips/
https://claudiosmweb.com/shortcodes/maps/
https://claudiosmweb.com/shortcodes/qr-codes/

**Comment by claudiosmweb** [comment]
Pronto, removi todos os links.
