### ISSUE TITLE
Item estranho na documentação

### ISSUE THREAD

**Issue by matheusgimenez** [wpbrasil/odin#369]
Hoje estava fuçando a documentação e vi que tem um item meio WTF lá no meio:

https://github.com/wpbrasil/odin/wiki/ATPS-da-disciplina-Compiladores---Prof%C2%BA-Michel.

**Comment by claudiosmweb** [comment]
Isso que da liberar para a galera poder editar a wiki xD

**Comment by allysonsouza** [comment]
hahaha, que brisa isso xD
