### ISSUE TITLE
Area de Cliente 

### ISSUE THREAD

**Issue by AllanD1** [wpbrasil/odin#375]
Sou novo por aqui ja fiz coisas simples usando Odin gostei muito, porem hoje preciso de uma Area de cliente para um petshop e preciso relacionar esse clientes com seus animais mas não sei como relacionar os dois como WP se alguém souber de algo que possa me ajudar fico grato :+1:

**Comment by claudiosmweb** [comment]
Faz no Odin da mesma forma que faz isso no WordPress.
Sua dúvida não é especifica desse tema e sim pedindo para lhe ensinar como trabalhar...
