### ISSUE TITLE
Formulário dinâmico

### ISSUE THREAD

**Issue by matheusilario** [wpbrasil/odin#376]
Boa noite galera, estou desenvolvendo um projeto que terá vários autores. Gostaria de exibir um formulário na single para que as pessoas enviem mensagem diretamente para o autor de cada post. Tem alguma forma de fazer isso com a classe de formulário do Odin?

**Comment by matheuscl** [comment]
Bom dia, ve se [esse gist](https://gist.github.com/matheuscl/f5d96cd7642c0e389318) resolve seu problema.

**Comment by matheusilario** [comment]
Obrigado Matheus, ainda não tive tempo de testar mas acredito que funcione sim. Eu estava tentando no método render().
