### ISSUE TITLE
Odin base path/uri

### ISSUE THREAD

**Issue by matheuscl** [wpbrasil/odin#378]
Acredito que como eu algumas pessoas utilizam apenas o "core" do Odin (core/inc/assets, não utilizo arquivos do tema), e perguntei no [slack](http://slack-wpbrasil.herokuapp.com/) se era válido fazer algo como `odin_directory_uri()` pois ficar dando `replace_all` na pasta é insuportável, e como tive um feedback positivo(famoso sinal verde) assim que eu pensar em alguma solução bacana eu já atualizo a issue aqui =)

**Comment by fdaciuk** [comment]
@matheuscl, não entendi porque você precisa fica dando `replace_all`. Se você fizer o require dos arquivos do Odin no seu functions, não precisa mexer em nada dos caminhos que estão setados nele ;)

**Comment by matheuscl** [comment]
Deixa eu me explicar melhor, eu coloco os arquivos dentro de uma pasta do meu tema com o nome `odin` para não misturar o tema com o framework e por exemplo no admin quando alguma utiliza algum css/js, como [aqui](https://github.com/wpbrasil/odin/blob/master/core/classes/class-theme-options.php#L62]), da pasta `assets` ele fica com o caminho absoluto do tema sem o `/odin` e da 404, obviamente, entendeu o problema?

**Comment by fdaciuk** [comment]
Entendi. Não seria mais fácil deixar direto a pasta core no seu tema? Você usa algo a mais no diretório `odin`?

Tô dizendo pois eu também uso dessa forma: deixo o `core` na raiz do tema e tudo funciona de boa xD

**Comment by matheuscl** [comment]
Eu acho que fica meio desorganizado, e eu uso as pastas `assets` e `inc` para arquivos do tema mesmo, eu pensei nisso pq realmente gosto de separar as duas coisas, mas é questão de gosto/frescura você acha que não viável?

**Comment by fdaciuk** [comment]
Acho que faz sentido deixar os caminhos do `odin` maleáveis sim, só queria entender como é a estrutura que você usa.. No caso, como o `core` seria um _3rd party_ no seu tema, o ideal seria não criar nada dentro desse diretório, pois se precisar atualizar, vai ter que fizer fazendo backup das coisas manualmente.

É como você usar a estrutura do WP, o `wp-admin` por exemplo, para salvar seus arquivos de configuração do painel. Quando for atualizar o WP, provavelmente vai perder o trabalho que você fez.

**Comment by matheuscl** [comment]
Atualmente um tema meu tem basicamente a estrutura apresentada abaixo, o que fode é eu já usar a pasta `inc`, se não fosse por ela poderia deixar tranquilo o `core` no root do tema.
```
├── assets
│   ├── css
│   ├── fonts
│   ├── img
│   └── js
│       └── vendor
├── content
├── inc
│   ├── shortcodes
│   ├── widgets
│   ├── helpers
├── languages
└── odin
    ├── core
    │   ├── assets
    │   │   ├── css
    │   │   ├── images
    │   │   └── js
    │   └── classes
    │       ├── abstracts
    │       └── widgets
    └── inc
        ├── assets
        │   ├── css
        │   └── images
        └── woocommerce
```

**Comment by fdaciuk** [comment]
Bom, então você não tá usando só a pasta `core`, está usando a `inc` também, que faz parte do tema. Aí não tem muito o que fazer xD

**Comment by matheuscl** [comment]
Sim, isso mesmo como eu citei quando abri a issue ali:
> "core" do Odin (core/inc/assets, não utilizo arquivos do tema)
Eu errei colocando a `assets` ali só, essa eu não uso, mas a pasta `inc` tem coisas importantes (hooks, `odin_head_cleanup()`) os quais uso bastante, e pra mim tirar isso só pra poder colocar a `core` no base path do tema seria meio inviável, talvez se a `inc` fosse embutida a pasta `core` na v3 de alguma maneira seria maneiro e mataria esse problema, não sei ao certo agora =)

**Comment by adammacias** [comment]
Acho que devemos sim pensar em melhorar a estrutura do Odin, mas tenho uma opinião diferente para a organização, vamos levar esse tópico para a a versão 3 do Odin! Ok? :v: anexo: #328
