### ISSUE TITLE
Class para auxiliar a adição de opções no Personalize

### ISSUE THREAD

**Issue by davidsantanacosta** [wpbrasil/odin#381]
Eu senti necessidade de adicionar opções no personalize e vi que o odin não tinha suporte, então criei algo. E essa é minha sugestão para adicionarem ou usarem para melhorar o odin. O que vocês acham desta ideia?

[admin/customize.php](http://pastebin.com/Lp2iEeAQ)
[core/class/class-theme-customize.php](http://pastebin.com/YLhAX4ts)

![personalizar1](https://cloud.githubusercontent.com/assets/3098556/12699137/76ed64ee-c78f-11e5-9021-f8bc0aeacf5d.png)
![personalizar2](https://cloud.githubusercontent.com/assets/3098556/12699138/76eeb56a-c78f-11e5-8938-6f4d86e6ffc8.png)

**Comment by allysonsouza** [comment]
https://github.com/wpbrasil/odin/issues/328#issuecomment-138654298
