### ISSUE TITLE
Problena na edição do header.php

### ISSUE THREAD

**Issue by rafaolivei** [wpbrasil/odin#383]
Quando faço uma edição na header, ela só funciona na home, nas demais áreas do tema ela some, apenas o menu permanece.

**Comment by matheuscl** [comment]
Tem certeza que o problema é com o Odin?

**Comment by rafaolivei** [comment]
olha eu sou novato em wordpress, mas já testei no meu servidor local e em minha hospedagem com o wordpress atualizado, o problema persiste, e também não to usando plugin, só pra garantir que não aja conflito.
Bom e quanto a ter certeza que o problema é com o odin, eu não tenho :)
Já pesquisei bastante no google mas não achei nem um problema similar a o meu.

**Comment by matheuscl** [comment]
Da uma conferida pra ver se você não está usando a função `is_home()` em algum lugar errado.

**Comment by rafaolivei** [comment]
Vlw funciono :)
