### ISSUE TITLE
Item do Menu sem link

### ISSUE THREAD

**Issue by Adrian1995** [wpbrasil/odin#384]
Boa tarde,
Gostaria de saber se isso é um erro ou é comum, criei um menu com submenus (Drop down), porém, o item que dá origem aos sub-menus está com o href="#", segue imagem abaixo.

![erro](https://cloud.githubusercontent.com/assets/9981093/13034933/b38d2eac-d329-11e5-96b9-4ff4f97ff029.png)

**Comment by adammacias** [comment]
É nativo do Bootstrap usar [dropdown no navbar](http://getbootstrap.com/components/#navbar) assim.

Acredito que eles optaram por não ter um link aí e nem aplicaram o efeito "hover" ou invés do "clique" para melhorar a acessibilidade em mobiles e navegação via teclado.

Caso seu projeto necessite alterar isso, o arquivo que você deve modificar é o [class-bootstrap-nav.php](https://github.com/wpbrasil/odin/blob/master/core/classes/class-bootstrap-nav.php)
