### ISSUE TITLE
Campos adicionais de usuários no formulário de registro

### ISSUE THREAD

**Issue by allysonsouza** [wpbrasil/odin#385]
Estava olhando a clase Odin_User_Meta, e pensei que podíamos implementar, de alguma forma, a opção de exibição dos campos adicionais no formulário de registro ou não, reutilizando o código de exibição dos campos no painel.

Ou talvez, uma classe nova, mas ai o usuário teria que trabalhar de alguma forma com os mesmos id's... Pode ficar porco, sei lá. O que acham?

**Comment by adammacias** [comment]
Ci pá uma nova classe seria mais interessante. Daí daria para criar multi forms se preciso, exemplo: um usuário tipo *professor* que teria mais campos do que um *aluno*.

**Comment by allysonsouza** [comment]
Fechando esta issue aqui, movida para o Odin Toolkit: https://github.com/wpbrasil/odin-toolkit/issues/5
