### ISSUE TITLE
Problemas com Odin_Theme_Options

### ISSUE THREAD

**Issue by lipehalford** [wpbrasil/odin#387]
Olá pessoal! Sou novo no odin e não estou conseguindo fazer a aparecer a página _Opções do tema_
Segui o tuto certinho e creio que o problema seja na chamada da classe:

`$odin_general_opts = new Odin_Options_Helper( 'odin_general', 'your_id_name' );`

Instanciei ela no **class-options.php** passando o id_name dessa forma

`$odin_general_opts = new Odin_Options_Helper( 'odin_general', 'odin-settings' );`

da mesma forma que em **class-theme-options.php**

```php
function odin_theme_settings_example() {
		$settings = new Odin_Theme_Options ( 'odin-settings', // Slug/ID of the Settings Page (Required)
'Theme Settings', // Settings page name (Required)
'manage_options' ) // Page capability (Optional) [default is manage_options]
;
```
 Como disse segui o tuto ao pé da letra; desculpem pela noobice e obrigado pela ajuda.
[classes.zip](https://github.com/wpbrasil/odin/files/171060/classes.zip)

**Comment by matheuscl** [comment]
Pra começar que você está redeclarando a classe `Odin_Theme_Options`, segundo que aquele `hook(init)` está sendo chamado dentro da classe, pra funcionar é só mudar o nome da classe e tirar o `init` de dentro da classe, veja como fiz  `add_action ( 'init', array( 'My_Custom_Theme_Options', 'odin_theme_settings_example' ), 1 );`, funcionou perfeito aqui.

**Comment by lipehalford** [comment]
@matheuscl  quando mudei o nome da classe , deu Uncaught Error. Tentei mudar a instancia do objeto

`$settings = new Odin_Theme_Options ( 'odin-settings', // Slug/ID of the Settings Page (Required)`

 e deu de novo uncaught error; sendo que das 2 formas coloquei o hook fora da classe... o que ainda estou fazendo de errado? Manda sua classe pra dar uma olhada por favor
[class-theme-options.zip](https://github.com/wpbrasil/odin/files/177092/class-theme-options.zip)

**Comment by matheuscl** [comment]
Evite ficar mandando `.zip` só pra mostrar código, pra isso temos o [pastebin](http://pastebin.com/) e o [gist](https://gist.github.com/), o código está [aqui](https://gist.github.com/matheuscl/7269714c63b06141d59f), só copiar e colar pra ver se vai funcionar.

**Comment by lipehalford** [comment]
@matheuscl Cara não funcionou...já havia mudado o nome desse mesmo jeito ai e deu uncaught...[class-theme-options.php]https://gist.github.com/lipehalford/93de4ab842a362d2626d) 
[functions.php](https://gist.github.com/lipehalford/8c9e501d009468c7ced0)
Creio que não seja a options...a declaração ta igual a sua, será que não é necessário adicionar mais algo?

**Comment by matheuscl** [comment]
Cara, você está mexendo no arquivo da classe do Odin?
Deixa a classe em arquivo separado e só xama as duas no `functions.php`, primeiro a do Odin depois a sua, e NÃO mexe na classe do Odin...

**Comment by lipehalford** [comment]
Valeu cara realmente era isso...eu imaginei que teria de implementar a classe nova no lugar da original, até porque para seguir o padrão do Odin...de qualquer forma muito obrigado! =)
