### ISSUE TITLE
Não utilizar variáveis como text domain na internacionalização das strings

### ISSUE THREAD

**Issue by leobaiano** [wpbrasil/odin#388]
Galera, o Nikolov abriu uma issue em um projeto meu falando que não é uma boa utilizar variáveis nas funções de tradução, como o Odin utiliza a mesma metodologia eu pensei abrir essa issue para sabe o que vocês acham do assunto.

Ele mandou o seguinte link como referência: https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/

**Comment by allysonsouza** [comment]
@leobaiano li e concordo com o artigo, mas não entendi, onde o Odin utiliza variável como text-domain?

**Comment by leobaiano** [comment]
Agora não lembro onde foi que eu vi, acho que em uma das classes do core, vou dar uma olhada e comento aqui.

**Comment by adammacias** [comment]
@leobaiano fiz uma busca aqui e não achei nada. :dancers:  Olha...

- [`__()`](https://github.com/wpbrasil/odin/search?utf8=%E2%9C%93&q=__%28&type=Code)
- [`_e()`](https://github.com/wpbrasil/odin/search?utf8=%E2%9C%93&q=_e%28&type=Code)

**Comment by RafaelFunchal** [comment]
@leobaiano está ficando maluco

**Comment by leobaiano** [comment]
Acho que confundi com o segundo parametro da `sprintf()` então.
