### ISSUE TITLE
Select Fields - <optgroup> e disabled

### ISSUE THREAD

**Issue by allysonsouza** [wpbrasil/odin#389]
Adicionando aqui para pensarmos em adicionar de um modo simples o suporte a campos desabilitados na geração de selects (seja para meta boxes ou opções do tema), e também para <optgroup>, para organização das opções em grupos.

**Comment by adammacias** [comment]
@allysonsouza o parametro `attributes` não consegue deixar o campo `disabled`? Já a opção `<optgroup>` é uma boa ter mesmo.

O que acha desta desta maneira:

```
array(
    ...
    'type' => 'select-group',
    'attributes' => array(
        'disabled' => 'disabled' // Desativa campo
    ), 
    'options' => array(
        'Carros' => array(
               'honda' => 'Honda',
               'civic' => 'Civic'
        ),
        'Frutas' => array(
               'banana' => 'Banana',
               'laranja' => 'Laranja'
        )
    ),
)
```

**Comment by allysonsouza** [comment]
@adammacias mas ai o `disabled`não estaria se referindo ao campo todo? Nem eu lembro bem o que falei, mas acho que falava em ter opções do select inativas individualmente.

**Comment by adammacias** [comment]
Saquei! eu nem sabia que dava para fazer isso aqui: [usar `disabled` no `optgroup`](http://www.w3schools.com/tags/att_optgroup_disabled.asp) hehe

Nesse caso:

```
array(
    ...
    'type' => 'select-group',
    'options' => array(
        array(
            'label' => 'Carros',
            'disabled' => 'disabled',
            'options'  => array(
               'honda'  => 'Honda',
               'civic'  => 'Civic'
            )
        ),
        array(
            'label' => 'Banana',
            'disabled' => 'disabled',
            'options'  => array(
               'banana'  => 'Banana',
               'laranja' => 'Laranja'
            )
        )
    )
)
```

**Comment by lenivene** [comment]
@adammacias Acho que seria melhor o `'disabled' => true` ?

**Comment by adammacias** [comment]
@lenivene sim! e agora que você disse isso, poderiamos usar `attributes`, como é [usado já atualmente](https://github.com/wpbrasil/odin/wiki/Classe-Odin_Metabox#select).
```
array(
    ...
    'type' => 'select-group',
    'options' => array(
        array(
            'label' => 'Carros',
            'attributes' => array( 'disabled' => true )
            'options'  => array(
               'honda'  => 'Honda',
               'civic'  => 'Civic'
            )
        ),
        array(
            'label' => 'Banana',
            'attributes' => array( 'disabled' => true )
            'options'  => array(
               'banana'  => 'Banana',
               'laranja' => 'Laranja'
            )
        )
    )
)
```

**Comment by allysonsouza** [comment]
Fechando está issue por aqui, movida para o Odin Toolkit: https://github.com/wpbrasil/odin/issues/389
