### ISSUE TITLE
Taxonomy Odin

### ISSUE THREAD

**Issue by AlyssonIdeagi** [wpbrasil/odin#393]
Boa tarde a todos :D,
seguinte pessoal, é possível utilizar CATEGORIAS para determinado modulo? 

Tipo, to usando o modulo de NOTICIA e VÍDEOS, onde as categorias para os dois são diferentes, mas não consigo chamar nos dois, só aparece em um =/ Agradeço a atenção abraços amigos

**Comment by allysonsouza** [comment]
@AlyssonIdeagi acho que faltou a descrição na sua issue, não?

**Comment by allysonsouza** [comment]
@AlyssonIdeagi de que módulos você fala? Está falando de utilizar uma mesma taxionomia para mais de um Custom Post Type, é isso?

**Comment by AlyssonIdeagi** [comment]
Exato @allysonsouza. Vou postar aqui o módulo: http://pastebin.com/F3GgHHy0

**Comment by allysonsouza** [comment]
@AlyssonIdeagi passa na criação da taxionomia, no terceiro parâmetro, um array com os tipos de conteúdo em que deseja que ela pertença, ao invés de uma única string.

    `$videos = new Odin_Taxonomy(
        'Categoria', // Nome (Singular) da nova Taxonomia.
        'categoria', // Slug do Taxonomia.
        array( 'videos', 'noticias', 'post' ) // Nome do tipo de conteúdo que a taxonomia irá fazer parte.
    );`

**Comment by AlyssonIdeagi** [comment]
@allysonsouza só que dessa forma que você está falando as categorias serão as mesmas para todos né isso?

**Comment by matheuscl** [comment]
Sim @AlyssonIdeagi.

**Comment by allysonsouza** [comment]
Exato. Compartilharão os mesmos termos.

Se você quer que seja independente para cada tipo de conteúdo, terá que trabalhar como o WooCommerce por exemplo, que tem a taxionomia 'product_cat' para categorias de produtos.

**Comment by AlyssonIdeagi** [comment]
Eu queria exatamente assim @allysonsouza, categorias separadas para cada módulo. Como eu consigo fazer igual ao woocommerce?

**Comment by matheuscl** [comment]
Se você quiser que eles tenham termos diferentes entre eles, você vai ter que repetir o código que utilizou para criar a taxonomia de videos, mudando apenas o nome do CPT, veja esse exemplo: http://pastebin.com/3NyjuRwA

**Comment by allysonsouza** [comment]
@AlyssonIdeagi criando várias, independentes, utilizando algum prefixo ou sufixo para diferenciar os seus slugs.

**Comment by AlyssonIdeagi** [comment]
Vou tentar, um momento.

**Comment by AlyssonIdeagi** [comment]
Fiz assim galera, deu certo o/ :D Obrigadooo

`function odin_noticias_taxonomy() {
    $noticias= new Odin_Taxonomy(
        'Categoria', // Nome (Singular) da nova Taxonomia.
        'categoria-noticias', // Slug do Taxonomia.
        'noticias' // Nome do tipo de conteúdo que a taxonomia irá fazer parte.
    );
}

add_action( 'init', 'odin_noticias_taxonomy', 1 );`

`function odin_videos_taxonomy() {
    $videos= new Odin_Taxonomy(
        'Categoria', // Nome (Singular) da nova Taxonomia.
        'categoria-videos', // Slug do Taxonomia.
        'videos' // Nome do tipo de conteúdo que a taxonomia irá fazer parte.
    );
}

add_action( 'init', 'odin_videos_taxonomy', 1 );`

**Comment by AlyssonIdeagi** [comment]
Só fiz mudar o nome do SLUG e já foi, funcionou o/

**Comment by matheuscl** [comment]
Boa.

**Comment by AlyssonIdeagi** [comment]
Pessoal agradeço a ajuda de vocês mas estou com alguns problemas em relação a mostrar post de acordo com a categoria, como eu mudei o nome dos slugs e tal, mas to tentando puxar e não consigo =/ 

Estou colocando 'category_name' => 'slug' mas não vai =/

> <?php
			$args = array('post_type' => 'anuncios', 'posts_per_page' => '2', 'orderby' => 'rand');
			query_posts($args);
			while (have_posts()) : the_post();
			global $post, $wpdb; 
			$imagem = get_post_meta( $post->ID,'imagem', true );
			$url = get_post_meta( $post->ID,'url', true );
			?>

**Comment by allysonsouza** [comment]
@AlyssonIdeagi vamos lá, temos alguns pontos sobre se problema de agora:

- A issue original foi resolvida, e foi fechada, não tem porquê comentar aqui novamente.
- O problema inicial tinha uma leve relação com o Odin, agora essa questão, é uma questão de WordPress que não tem nada a ver com o framework.
- Não use query_posts, é uma função depreciada há muitas versões do WordPress já, na própria página do codex tem esse alerta. https://codex.wordpress.org/Function_Reference/query_posts
- Suegestão: procure os fórums do WordPress ou grupos, mas a princípios pare de utilizer query_posts e dê uma pesquisada nas formas corretas de se fazer um loop que creio que seu problema já será resolvido.
