### ISSUE TITLE
Painel de controle e site em português, mas determinadas funcionalidades em Inglês

### ISSUE THREAD

**Issue by AlyssonIdeagi** [wpbrasil/odin#399]
Já troquei o Wordpress e continua do mesmo jeito =/
Os módulos que são do ODIN estão em inglês, exemplo: ADD NEW LOJA

**Comment by AlyssonIdeagi** [comment]
Os módulos que são do ODIN estão em inglês, exemplo: ADD NEW LOJA

**Comment by allysonsouza** [comment]
@AlyssonIdeagi pelo trecho que colocou acima, imagino que esteja falando de CPT's, ou Taxonomias.
Na criação do CPT, com o Odin, se você não definir as labels, creio que ele mantenha em inglês mesmo.

Seguindo o exemplo da wiki do Odin, criando um CPT 'video':

```
$video = new Odin_Post_Type(
    'Video', // Nome (Singular) do Post Type.
    'video' // Slug do Post Type.
);
```

Para que as labels do CPT fiquem traduzíveis ou já diretamente traduzidas, eu defino elas:

```
$video->set_labels(
    array(
        'menu_name' => __( 'Meus Vídeos', 'odin' ),
        'edit_item' => __('Editar Vídeo', 'odin' )
    )
);
```

Podendo utilizar todos os labels que usaria se estivesse registrando um custom post type com a função register_post_type: https://codex.wordpress.org/Function_Reference/register_post_type#Arguments

O mesmo vale para taxionomias. Espero que isso possa ajudar!

**Comment by AlyssonIdeagi** [comment]
> <?php
function odin_lojas_cpt() {
    $lojas = new Odin_Post_Type('Loja','lojas');
    $lojas->set_labels(
        array('menu_name' => __( 'Lojas', 'odin' ))
        );
    $lojas->set_arguments(
        array( 
            'supports' => array( 'title' ),
            'register_meta_box_cb'   => 'lojas_metabox'
            )
        );
}
add_action( 'init', 'odin_lojas_cpt', 1 );

function lojas_metabox() {

    $lojas = new Odin_Metabox(
        'lojas', // Slug/ID of the Metabox (Required)
        'Campos Extras', // Metabox name (Required)
        'lojas', // Slug of Post Type (Optional)
        'normal', // Context (options: normal, advanced, or side) (Optional)
        'high' // Priority (options: high, core, default or low) (Optional)
        );

    $lojas->set_fields(
        array(
            array(
                'id'          => 'endereco', // Required
                'label'       => __( 'Endereço', 'odin' ), // Required
                'type'        => 'textarea', // Required
                'attributes' => array( // Optional (html input elements)
                    'placeholder' => __( 'Endereço da Loja' )
                    ),
                'description' => __( 'Nome do dia do mês', 'odin' ), // Optional
                ),
            array(
                'id'          => 'cidade', // Required
                'label'       => __( 'Cidade', 'odin' ), // Required
                'type'        => 'text', // Required
                'attributes' => array( // Optional (html input elements)
                    'placeholder' => __( 'Cidade da Loja' )
                    ),
                'description' => __( 'Nome do dia do mês', 'odin' ), // Optional
                ),
            array(
                'id'          => 'imagem', // Required
                'label'       => __( 'Imagem Destaque', 'odin' ), // Required
                'type'        => 'image', // Required
                // 'default'    => '', // Optional (file url)
                'description' => __( 'Insira a imagem destaque da galeria', 'odin' ), // Optional
                ),
            array(
                'id'          => 'fotos', // Required
                'label'       => __( 'Fotos da Loja', 'odin' ), // Required
                'type'        => 'image_plupload', // Required
                // 'default'    => '', // Optional (file url)
                'description' => __( 'Insira fotos na galeria', 'odin' ), // Optional
                ),
            )
);
}
add_action( 'init', 'lojas_metabox', 1 );

?>

Creio que está correto =/ É por que não tenho como mandar imagem do painel

**Comment by AlyssonIdeagi** [comment]
![painel](https://cloud.githubusercontent.com/assets/11085286/15651269/e452069c-2654-11e6-8562-294890b5674f.jpg)

Consegui mandar a imagem de como ta no painel ;)

**Comment by allysonsouza** [comment]
@AlyssonIdeagi é exatamente o que respondi, dê uma olhada no codex, o tanto de label que tem para ser definida, e o tanto que você definiu:
```
$lojas->set_labels( array( 'menu_name' => __( 'Lojas', 'odin' ) ) );
```
No caso, apenas uma, **'menu_name'**.

**Comment by allysonsouza** [comment]
Por exemplo, para definir o texto do 'Add New' post type além do item de menu:

```
$lojas->set_labels( 
        array( 
            'menu_name' => __( 'Lojas', 'odin' ),
            'add_new' => __( 'Adicionar Nova Loja', 'odin' )
        )
);
```

**Comment by RafaelFunchal** [comment]
Isso tudo já está desctito no Wiki:


https://github.com/wpbrasil/odin/wiki/Classe-Odin_Post_Type#configurando-os-t%C3%ADtulos-labels
>São aceitos todos os $labels da função register_post_type().

https://github.com/wpbrasil/odin/wiki/Classe-Odin_Taxonomy#configurando-os-t%C3%ADtulos-labels
>São aceitos todos os $labels da função register_taxonomy().

**Comment by AlyssonIdeagi** [comment]
Não sei por que fecharam =/ Só mais um dúvida, por que nunca precisei adicionar isso entende? Sempre fiz dessa forma e funcionou, será que fiz algo ou teve alguma mudança?

**Comment by AlyssonIdeagi** [comment]
Estranho pois sempre utilizei fazer isso, mas obrigado amigo, desse jeito fica melhor mesmo rsrs :+1:

**Comment by RafaelFunchal** [comment]
Não é porque funciona que está certo. 

Já testou informando as labels que sugeriram?

**Comment by AlyssonIdeagi** [comment]
Testei sim man, fica muito melhor ;) Mas funcionava e funciona em alguns sites entende? Nunca precisei informar os nomes. Mas desse jeito é bem melhor e correto rsrs. Obrigado a todos
