### ISSUE TITLE
Editor não consegue salvar as opções de tema

### ISSUE THREAD

**Issue by emanoelevaristo** [wpbrasil/odin#402]
Um usuário com a **'Role: Editor'** não consegue salvar as opções de tema, apenas o **Admin**.
Como permitir que os editores também consigam salvar tais opções?
```php
function mySuperThemeSettings() {
    $settings = new Odin_Theme_Options(
        'myThemeSettings', // Slug/ID of the Settings Page (Required)
        'Opções do Tema', // Settings page name (Required)
        'manage_options' // Page capability (Optional) [default is manage_options]
    );
   [...]
}
add_action( 'init', 'mySuperThemeSettings', 1 );
```

**Comment by claudiosmweb** [comment]
Você colocou que apenas quem tem a capacidade de `manage_options` que pode usar, então não tem como funcionar para um editor.

**Comment by emanoelevaristo** [comment]
Mesmo colocando outra capacidade, como por exemplo, `publish_posts` um Editor não consegue salvar, apenas exibir.
