### ISSUE TITLE
Personalizando o Admin

### ISSUE THREAD

**Issue by carlosalbertocruz** [wpbrasil/odin#407]
Funções do admin não existem. 
Fatal error: Uncaught Error: Call to undefined function odin_admin_css() ...

**Comment by adammacias** [comment]
@carlosalbertocruz essa função foi [removida do Odin](https://github.com/wpbrasil/odin/commit/91dc39a13b34ae13c26ccb5648d71267831a712e#diff-7199c031b61520f8b9e71f95937913ad). Agora é possível adicionar estilos CSS no admin do WordPress através da folha de estilhos CSS em [`odin/inc/assets/css/custom-admin.css`](https://github.com/wpbrasil/odin/blob/master/inc/assets/css/custom-admin.css).

PS. Agora foi removido da WIKI tambem! :smiley_cat:

**Comment by carlosalbertocruz** [comment]
Opa, muito obrigado ^^
