### ISSUE TITLE
Exibir categoria cadastrada no post type

### ISSUE THREAD

**Issue by leonardop21** [wpbrasil/odin#408]
Olá, pessoal.

Criei um post type chamado produtos, porém, fiquei com dúvidas de como listar no post a qual categoria pertence o produto.

**Ex: Publicado em 07 de julho de 2016 às 10:30 na categoria Geladeiras, Pequena**

Vasculhei a internet a procura da solução, então me deparei com vários problemas parecidos e um deles me ajudou muito, porém, ele lista todas as categorias em todos os produtos, mesmo no produto estando marcado só uma categoria.

Ex: Tenho dois produtos, geladeira e fogão, a categoria geladeira tem várias subcategorias, então marco todas elas e a categoria da televisão tem somente uma. Quando acesso o produto televisão, ele lista a categoria das geladeiras também, por que isso acontece ?

Categoria: Geladeira, pequena, televisão...

Obs: Sou iniciante.

Segue o código utilizado.

http://pastebin.com/8e4d7Bn8

**Comment by matheusgimenez** [comment]
Essa é uma duvida de WP e não relacionada ao Odin.

Vou mostrar onde ta o erro e se tiver mais dúvidas posta no [fórum oficial](https://br.forums.wordpress.org/), ok?

A função que vc ta usando pra pegar as categorias não funciona para o que você precisa. No caso, a função get_categories pega todos termos de uma determinada taxonomia sem levar em conta os posts. Você precisa usar [wp_get_object_terms()](https://developer.wordpress.org/reference/functions/wp_get_object_terms/) ou [get_the_terms()](https://developer.wordpress.org/reference/functions/get_the_terms/).

Abraços

**Comment by leonardop21** [comment]
@matheusgimenez desculpa pelo equívoco Matheus, já  tinha lido os links que você citou acima, mesmo assim tive problemas, vou reler eles para ver se consigo resolver. Obrigado pela resposta.

**Comment by leonardop21** [comment]
@matheusgimenez Problema resolvido, obrigado pela ajuda. 

https://developer.wordpress.org/reference/functions/wp_list_categories/
