### ISSUE TITLE
Implementar testes unitários

### ISSUE THREAD

**Issue by iszwnc** [wpbrasil/odin#410]
Salve galera! Beleza? Eu estava dando uma olhada no projeto e ao meu ver o Odin amadureceu bastante e cresceu muito (em termos de contribuidores/contribuições). Por isso criei esta *issue*, pois acredito que nessas alturas do campeonato, **Unit Tests** já deveriam ter sido implementadas para o Odin gerenciar e integrar melhor futuros *PR*s.

> Obs: Eu estou disposto a escrever os testes e manda-los um por um via *Pull Request*, ok? Quem quiser ajudar é muito bem-vindo inclusive! :smile:

O que acham?

Outra coisa, andei fuçando em algumas *issues* antigas e encontrei esta aqui #306 que trata da implementação de **Continuous Delivery**, gostaria de saber se ainda acham interessante a ideia? Pois estou disposto a ajudar na implementação disso também.

O que acham de implementarmos **CI** ao invés de **CD**? Estou perguntando porque gostaria de saber o ponto de vista de todos.

> Eu pessoalmente acho que **Continuous Integration** já é suficiente para o Odin

**Comment by iszwnc** [comment]
Eu optei por não falar de **CI/CD** no título pois o propósito dessa *issue* não é essa, e sim implementarmos testes unitários. Porém gostaria de tratar disso aqui também, pois caso a ideia seja aprovada, futuras referências sobre **TDD/BDD** e **Unit Tests** possam ser tratadas aqui.

**Comment by adammacias** [comment]
@iszwnc pois já foi comentado o mesmo assunto em #306
