### ISSUE TITLE
Depreciar ou remover a classe Theme Options

### ISSUE THREAD

**Issue by matheusgimenez** [wpbrasil/odin#414]
Galera,

Visto que a versão 3 do Odin está saindo do forno precisamos pensar em remover a classe Theme Options.
Como já devem saber, a equipe de revisores do WP.org NÃO recomenda a utilização da Settings API em temas.

Minha opinião aqui é que devemos sim remover ou depreciar essa classe e indicar o uso do Customizer API.

**Comment by allysonsouza** [comment]
Estou fechando essa issue pois iremos fazer a separação dos itens de plugin territory para o [Odin Toolkit](https://github.com/wpbrasil/odin-toolkit/), sendo assim a Settings API ainda é utilizada para plugins, apenas precisamos renomear o recurso para algo diferente de Theme Options.
