### ISSUE TITLE
Documentar Coding Stantard

### ISSUE THREAD

**Issue by kvnol** [wpbrasil/odin#416]
Dando uma olhada no código, depois de tanto tempo longe desse projeto, vi que não seguimos um padrão no SASS e talvez o code-guide (http://diegoeis.github.io/code-guide/) do @mdo já fosse uma boa melhoria para nosso código.

**Comment by adammacias** [comment]
@kvnol Com certeza acho válido ter algo assim na parte de "Como contribuir" na documentação.

Talvez seja mais interessante sugerir o próprio [Coding Stantard do WordPress](https://codex.wordpress.org/WordPress_Coding_Standards), e não só do CSS, e sim de tudo que ele nos disponibiliza tambem (JS/HTML/PHP).
  
:bowtie:
