### ISSUE TITLE
Singular Name - Custom Post Type

### ISSUE THREAD

**Issue by matheusdelima** [wpbrasil/odin#431]
Olá, estou enfrentando um problema ao utilizar a Class **Odin_Post_Type**,
Quando eu preencho o campo **Singular Name** no construtor da Class, a visualização no dashboard do WordPress acrescenta um "s", pois é necessário para sinalizar a pluralidade.

Isto é ótimo em alguns casos, Todavia em outros não;
Segue exemplo:

- Palavras terminadas em **“ão”** fazem o plural usando **“ãos” ou “ões”**.

Tendo em vista atender regras de coesão da nossa lingua portuguesa como poderiamos resolver isto?

**Comment by adammacias** [comment]
@matheusdelima você pode setar a [Configuração do títulos ($labels)](https://github.com/wpbrasil/odin/wiki/Classe-Odin_Post_Type#configurando-os-t%C3%ADtulos-labels) manualmente :)
