### ISSUE TITLE
Filtros avançados de conteúdo

### ISSUE THREAD

**Issue by jonasrafael** [wpbrasil/odin#437]
Estou trabalhando com o Odin atualmente e vejo que todos os frameworks pecam em funcionalidades básicas de tratamento de conteúdo. Talvez seria legal o Odin ter algo nesse sentido, até seria um diferencial bem legal. Por enquanto tou usando a extensão abaixo (com pequenas correções, pois não funciona com a versão atual do wordpress).

Referência
http://proword.net/Vc_Post_Layout/advanced-custom-filters/

Eu já fiz algumas tentativas de fazer isso, porém estão todas com bugs. Ano que vem compartilho com vocês o que tenho, caso alguém queira produzir em conjunto. Chama aí!

**Comment by adammacias** [comment]
@jonasrafael não entendi o termo que você usou "tratamento de contéudo" e na página de referencia só avistei uma listagem com posts, com um filtro. hehe

**Comment by jonasrafael** [comment]
é exatamente essa listagem/com filtro que eu acho interessante

**Comment by adammacias** [comment]
Acho difícil o Odin ter isto como feature. Acredito que esse tipo de componente não é essencial para a maioria dos temas criados,  ou seja, a cada 20 temas criados vamos supor que 18 não teria necessidade de uso, com isso seria mais trabalho para remover do tema do que para inseri-lo de vez ou outra. 

Aqui esta um link com outros componentes de filtro e ordenação http://www.unheap.com/user-interface/filter-sort/

**Comment by valdirljr** [comment]
Este plugin faz aparentemente iso @jonasrafael 
https://br.wordpress.org/plugins/search-filter/
http://demo.designsandcode.com/sfpro-movie-reviews/
http://demo.designsandcode.com/sfpro-woo-mystile/product-search/
https://www.designsandcode.com/wordpress-plugins/search-filter-pro/

Porém parou no WP 4.6.1 
Provavelmente irá funcionar a maior parte das funcionalidades.

**Comment by jonasrafael** [comment]
Valeu, vo ver :)

**Comment by hugomedeiros** [comment]
Eu Tenho a versão Pro deste plugin e tem suporte para a versão atual do WP.

*HUGO MEDEIROS*
Designer de interface
+55(21) 97999-1664
Skype: hugo.hugomedeiros
http://www.hugomedeiros.com.br

2017-01-06 14:09 GMT-02:00 Jonas Rafael <notifications@github.com>:
