### ISSUE TITLE
Transferir um tema para o Odin

### ISSUE THREAD

**Issue by designfaustini** [wpbrasil/odin#439]
Tenho um site em um tema que foi comprado no themeforest, porém o tema não tem sido atualizado e eu gostei da estrutura/layout. 

Ouvi falar muito bem do Odin, minha dúvida é, consigo transferir a estrutura do meu tema pro Odin, simplesmente migrando o CSS? Ou preciso migrar os arquivos também?

**Comment by ribeiroevandro** [comment]
Acredito que irá precisar ter conhecimentos no WordPress para que isso aconteça de forma satisfatória. Um projeto tem várias particularidades, não é apenas copiar arquivos e a mágica acontece...

**Comment by JoseCage** [comment]
@designfaustini  Em todo caso eu sugeria apenas basear-se no layout/estrutura e fazer algo próprio e não copiar o **Html, CSS** por questões de direitos autorais já que é um tema pago (fora o caso de a licença do tema te permitir total alteração e uso do código fonte)..

**Comment by designfaustini** [comment]
@JoseCage eu comprei o tema e alterei algumas linhas para ficar dentro do que o cliente precisava, essas linhas modificadas/inseridas são de minha autoria, então eu posso migrá-las. Talvez seria meio caminho andado.

@ribeiroevandro Não estou procurando mágica, estou procurando não ter um retrabalho.

**Comment by JoseCage** [comment]
Percebi @designfaustini 

Nesse caso, conforme citava o @ribeiroevandro. Precisarias ter o minimo conhecimento da infra do WordPress de formas que possas criar as **features (funcionalidades)** do tema. Como por exemplo saber criar query's. E por outro lado (o que parece ja entender) é a parte do html,js que é a parte da estilização em si..

Não sei se a minha dica pode lhe servir, mas acho que é isso.

**Comment by ribeiroevandro** [comment]
Eu particularmente não gosto de mexer com theme premium... Quando o cliente bate o pé, coloco um adicional no valor... Por outro lado, o que costumo fazer é procurar layouts em PSD, apresento ao cliente, visto que não faço design e uma vez aprovado, compro e desenvolvo na mão... Tenho muito mais controle do que acontece.

**Comment by designfaustini** [comment]
Entendi, sua dica @JoseCage servirá sim. Tive problema com um tema específico, por não atualizarem ele, por isso quero sair dele. Não conheço o Odin, vou fazer o download dele, ler os docs e ir fuçando aqui. Obrigado.

**Comment by designfaustini** [comment]
O sticky menu já foi resolvido.

**Comment by JoseCage** [comment]
Opa @designfaustini que bom.. 👍

**Comment by designfaustini** [comment]
Achei que tinha resolvido o menu sticky (fixar o menu na rolagem), mas não funcionou. Outra coisa, o responsive simplesmente não tá encaixando. 

O tema movido para o odin é: http://nortearh.hospedagemdesites.ws/n/

Se alguém puder me ajudar, agradeço. É a primeira vez que pego o Odin.
