### ISSUE TITLE
Expo Odin offline

### ISSUE THREAD

**Issue by valdirljr** [wpbrasil/odin#440]
O Expo do Odin está offline.
http://expo.wpod.in/

Como ajudo nisso ?

**Comment by adammacias** [comment]
@claudiosanches parece ser problema com o DNS, tu pode dar uma olhada? ✌️

**Comment by adammacias** [comment]
ping @claudiosanches :)

**Comment by claudiosanches** [comment]
@adammacias esqueci disso xD
Acabei de arrumar.
