### ISSUE TITLE
Como chamar os valores dos arrays das opções de tema?

### ISSUE THREAD

**Issue by guisierra** [wpbrasil/odin#442]
Estou dando os primeiros passos nesse Framework maravilhoso. Criei um painel para adicionar CSS customizado através de radio buttons e input range, mas não consigo chama-los. Alguém poderia me ensinar uma forma de fazer isso?

**Comment by matheusgimenez** [comment]
Qual sua duvida exatamente? Ja viu o tutorial completo na wiki? https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options

Veja essa seção: https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options#utilizando-os-campos
Aqui fala como retornar os campos.

Abraços
