### ISSUE TITLE
Erro na instalação da Framework

### ISSUE THREAD

**Issue by brunolimadevelopment** [wpbrasil/odin#444]
quando vou instalar o Odin, aparece a msg:
Não foi possível criar o diretório wp-content/uploads/2017/02. O diretório pai possui permissão de escrita?

o que eu devo fazer?

**Comment by RafaelFunchal** [comment]
Poderia dizer quais passos está executando para instalar o tema?

**Comment by brunolimadevelopment** [comment]
Boa noite, Rafael!
obrigado pela atenção.

eu estava fazendo o upload direto no wordpress.
em "add new theme"..  
 ai aparecia a msg:
"Não foi possível criar o diretório wp-content/uploads/2017/02. O diretório pai possui permissão de escrita?"

depois eu tentei colocando a pasta do odin direto na pasta wp-contents -> themes.
ai deu certo.  ^^

agora eu achei pouco conteúdo para se aprofundar e aprender melhor sobre essa framework, até mesmo no youtube não achei tutoriais, caso você conheça alguma outra fonte que aborde mais a framework fora a documentação da mesma. deixa aqui no comentario. 


vlw! Rafa. abraços!

**Comment by Rahmon** [comment]
@brunolimadevelopment 

Esse erro aconteceu pq as permissões das pastas/arquivos da sua instalação estão incorreta. Leia mais sobre nessa página: [Permissões de Arquivos](https://codex.wordpress.org/pt-br:Blindando_o_WordPress#Permiss.C3.B5es_de_Arquivo).

**Comment by AdsonCicilioti** [comment]
O melhor local para documentações sobre o Odin é aqui mesmo meu caro.. confira nossa[ Wiki](https://github.com/wpbrasil/odin/wiki)

**Comment by brunolimadevelopment** [comment]
vlw!!! @AdsonCicilioti e @Rahmon 
vocês sabem dizer se a Framework ODIN vai ser descontinuada?
como eu disse não acho tutoriais no youtube de como utiliza-la. 
ainda não conhecia o ODIN, comecei a utilizar recentimente mas não gostei muito do workflow dele.

**Comment by AdsonCicilioti** [comment]
@brunolimadevelopment eu utilizo ele. É bem verdade que a gente tá meio parado com lançamentos, mas eu tenho usado ele bastante, e não está nos planos parar não. O @adammacias tem trabalhado quase que sozinho na [V3](https://github.com/wpbrasil/odin/tree/v3-dev).... Mas é assim mesmo.. Projeto open source avança quando a galera chega junto pra colaborar, mas cada um tem suas prioridades dae a galera dispersa um pouco...

Quanto ao Workflow, o Odin procura usar ferramentas populares e que visam facilitar e fornecer mais agilidade no Start de Desenvolvimento de um Tema WP. E tem uma pá de ferramenta nova e atualizada que falta ou poderia ser implementada no Odin... É nisso que estamos trabalhando para a V3 e pensando em possibilidades para V4.

Mas o Odin é um tema poderoso, mesmo na atual versão, com inúmeras possibilidades para moldá-lo ao seu Wokflow...

Qual tem sido o sua maior dificuldade com ele? Deixe-nos saber.

**Comment by brunolimadevelopment** [comment]
@AdsonCicilioti, eu ainda não o conhecia mas gostei bem da função dela em iniciar um theme no WP.
visualizei a documentação dele e gostei muito a equipe está de parabéns.
mas minha maior dificuldade como dito antes foi em achar exemplos no youtube e até mesmo no google.
os devs que conheço que já trabalha a um bom tempo com Wordpress falaram que não o conhecia.

cara eu gostaria muito de contribuir de alguma forma com essa ferramenta
como faço? pode me orientar ?

quanto a workflow "estrutura de pastas":
o workflow dele é muito extenso muitas pastas e tals...
eu sempre procuro ver workflows de alguns devs e procuro otimizar o maximo possivel.
pois a otimização de pasta e arquivos faz um diferencial nas requisições. vc sabe disso @AdsonCicilioti .

**Comment by AdsonCicilioti** [comment]
Cara desculpa.. Mas quando disse Workflow imaginei que fosse algo mais voltado para Fluxo de Trabalho, ou facilidade no trabalho... Agora resumir um fluxo de trabalho à somente estrutura de pastas e arquivos é um pensamento um pouco raso.
Cara quanto as requisições de arquivos .php na estrutura do tema pode até ser considerável mas a relação é custo benefício é maior, considerando que cada Classe do Odin substitui o uso de diversos plugins que fariam muito mais requisições e processamento PHP. Sem Falar que vc não precisa deixar todas as Classes ativas, bastando comentar a linha onde é requisitadas as Classes logo no início do arquivo functions.php do tema. Acho que sua preocupação com as requisições não considerou isso certo?

Fora isso as requisições do tema são mínimas com apenas 01 arquivo .css e 01 .js + alguns vendors com JQuery, migrate, etc.. 

Quanto à colegas devs que não conheciam o Odin, talvez isso se deve a falta de Divulgação e atividade colaborativa.. mas ele é fruto de uma das maiores comunidades WP do Brasil.. Com membros que participam inclusive do desenvolvimento do Core do WP e de Empresas com a Woo Themes.

Se quer colaborar, domine o git, faça um fork, faça sua melhorias e proponha mandando seu Pull Request.

**Comment by brunolimadevelopment** [comment]
https://github.com/SublimeUser/bestplugins

pra quem utiliza o sublime text.
