### ISSUE TITLE
Opções do Tema

### ISSUE THREAD

**Issue by tupimg** [wpbrasil/odin#445]
Criei o Opções do Tema, como explicado no Wiki. Mas sou bem leigo ainda e não entendi como aplicar essas opções direto no tema.
Por exemplo:
Criei um campo de imagem url com o id "logo_site"
Como eu faço para aparecer a url no tema? Alguém poderia me mostrar como ficaria na prática?

**Comment by vilaboim** [comment]
Você precisa passar o id da aba, e depois chamar o id do campo que precisa:
https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options#utilizando-os-campos

E se você criou um campo "image", precisa chamá-lo com uma das funções do link abaixo:
https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options#image
