### ISSUE TITLE
Add TGM Plugin Activation

### ISSUE THREAD

**Issue by allysonsouza** [wpbrasil/odin#448]
Add TGM Plugin Activation resources to theme, making possible to require or recommend plugins to be installed with the theme.

- [x] Inserir TGM via Composer
- [ ] Carregar traduções do TGM
- [ ] Criar documentação de como utilizar o TGM

**Comment by allysonsouza** [comment]
https://github.com/wpbrasil/odin/commit/4e87c324abbff4a97995e1a9628dbc0fb15c2d94

**Comment by claudiosanches** [comment]
Sinceramente eu não gosto disso, principalmente por enfiar um projeto inteiro goela abaixo de todo mundo, sem contar que agora incluído aqui dentro, qualquer commit que eles fizerem, vamos ter que manualmente incluir aqui também.
Seria um pouco melhor ter usado Git Submodule ou Composer para manter uma copia do TGM, mas copiar e colar ele aqui é simplesmente horrível demais.

**Comment by allysonsouza** [comment]
Vou estudar como fazer então, apenas fiz do modo que sabia no momento. Concordo que com submodule ou composer fica melhor, sem dúvidas. Vou adicionar uma taks para melhor isso nos To Do's do projeto.

**Comment by claudiosanches** [comment]
Sugerir ou dar um exemplo de como usar, ou incluir como opção, acho que seria da hora.
Mas se vai usar realmente o TGM, então seria legal manter um sync com algo que indica qual versão esta usando.

**Comment by allysonsouza** [comment]
Acho que é legal ter ele já no projeto, só tentar corrigir essa questão do sincronismo. Falando com o @adammacias ele tem notado também como é uma necessidade recorrente em alguns projetos que utilizam ACF, CMB2, Kirki, etc., e também pela remoção de recursos do tema que entram no plugin territory, deve ter visto que criamos o repositório Odin Toolkit para começar a mover isso, assim se alguém irá utilizar recursos do plugin territory dentro do tema, pode colocar ele como requisito via o TGM.

**Comment by claudiosanches** [comment]
Sim eu vi, estou para arrumar umas coisas lá xD
Concordo que TGM tem seu valor, apenas dizendo que não é a única opção ou que é valido para todos os projetos.

**Comment by allysonsouza** [comment]
Removi o TGM inserido diretamente no projeto e adicionei um breve `composer.json` para isso. Apenas mantive o arquivo `required-plugins.php` que é específico do tema, assim quem for utilizar TGM é só dar um `composer install` e descomentar no functions o require do `required-plugins.php`

**Comment by adammacias** [comment]
@allysonsouza como faz para o TGM carregar a tradução [PT_BR](https://github.com/TGMPA/TGM-Plugin-Activation/blob/develop/languages/tgmpa-pt_BR.po) nativa do plugin?

Por favor, crie um checklist na descrição desta issue para corrigir essa questão da tradução, e também para criarmos a documentação de como fazer o uso desta feature com ```composer install``` e etc.

Porque tirou o ```vendor``` do .gitignore? 😮

**Comment by allysonsouza** [comment]
@adammacias gostaria de saber também, talvez seja algum problema do TGM.

Checklist criado, e `vendor` será ignorado propriamente, tirei por cabaçada :)

**Comment by claudiosanches** [comment]
Alias, bom que tem o composer assim para instalar outras coisas no projeto.
