### ISSUE TITLE
Opções de tema

### ISSUE THREAD

**Issue by thiagoluisj** [wpbrasil/odin#449]
Olá, gostaria de saber em um campo select, como coloco um atributo dentro de um option?

Por exemplo, quero que uma das opções do meu select fique desabilita, utilizando o atributo disabled.

**Comment by allysonsouza** [comment]
Olá @thiagoluisj,

Infelizmente esse é um ponto que precisa ser aprimorado na criação de `selects` com o Odin. Com a futura separação do Odin em tema e plugin, separando melhor seus recursos, esta issue está agora no repositório do plugin Odin Toolkit: https://github.com/wpbrasil/odin/issues/389
