### ISSUE TITLE
Customizar css

### ISSUE THREAD

**Issue by leonardocarlos** [wpbrasil/odin#450]
É a primeira vez que uso o odin e já tentei algumas maneira e nao  estou conseguindo fazer alterações no css como faço, eu não uso o sass só pode ser usando ele?

**Comment by allysonsouza** [comment]
Olá @leonardocarlos,

Você não é obrigado a utilizar SASS, apesar de ser a melhor forma, você pode adicionar o seu CSS no arquivo `style.css` que está entro da pasta `assets`.

**Comment by leonardocarlos** [comment]
Tem que desabilitar alguma coisa pois adiciono e nada acontece.

**Comment by allysonsouza** [comment]
Na verdade não @leonardocarlos, é isso mesmo, tente dar um **ctrl + F5** para atualizar o seu navegador.

**Comment by leonardocarlos** [comment]
Wlw Funcionou lá no trabalho no mac (por isso que gosto dele. rsrsrs) meu pc de casa não rolou (windows)
