### ISSUE TITLE
Paginação nas categorias

### ISSUE THREAD

**Issue by lancedon** [wpbrasil/odin#451]
Pessoal,

Estou com o seguinte problema, na home do site a paginação do Odin funciona normalmente, porem ao entrar em uma categoria (ex: site/categoria_xxx), a paginação não funciona. (ao clicar na paginação da page not found, 404)

Alguém já passou por isso com o Odin?

Abs

**Comment by RafaelFunchal** [comment]
Olá, @lancedon :-)

Você fez alguma personalização nas queries dos arquivos `category.php` ou `archive.php`?

Se sim, deixe a query padrão como nos arquivos originais e veja se o erro continua.

**Comment by lancedon** [comment]
opa @RafaelFunchal, 
Primeiramente obrigado pela ajuda.
voltei todos os arquivos do Odin para o original, porem ainda não consegui resolver o problema.

No meu caso criei o wordpress dentro do site em uma pasta chamada blog, portanto tenho tenho algo assim: www.meusite.com/blog/

Me parece que tem alguma relação com o problema das subcategorias, ex: se crio uma subcategoria, ao entrar nela o Odin não lista todos os posts desta subcategoria, porem abre o 1 deles.

Vou continuar fazendo testes durante o dia, se descobrir algo posto aqui.  De qualquer forma, obrigado pela ajuda.

**Comment by lancedon** [comment]
Pessoal, encontrei o problema. 

Para desativar o category nos permalinks links nos acrescentamos um ponto " . "  no campo Category base. Esse ponto foi o grande problema. Ele remove o category quando utilizamos o permalinks, porem gera todo o problema, removemos ele e instalamos um plugin de nocategory e resolveu.

Obrigado pela ajuda.
