### ISSUE TITLE
Paginação em custom post type

### ISSUE THREAD

**Issue by crb8** [wpbrasil/odin#456]
Olá a todos. Por gentileza, gostaria de saber se tem como inserir paginação em custom post type.
Desde já agradeço!

**Comment by renanlara** [comment]
Opa tudo bem?
Tem sim cara, com a função odin_paging_nav().
Se você abrir o arquivo archive.php ela já estará lá como padrão para os post types.

**Comment by crb8** [comment]
Muito obrigado e tenha uma ótima semana...

Em 29 de maio de 2017 12:08, Renan Lara <notifications@github.com> escreveu:
