### ISSUE TITLE
Tema Filho para Odin

### ISSUE THREAD

**Issue by aynoei** [wpbrasil/odin#458]
A opção de tema filho é o ideal, uma vez que não altera em nada na base do tema pai permitindo atualizações sem comprometer o código personalizado.

Alguém já desenvolveu algum tema filho para o Odin?

**Comment by renanlara** [comment]
Cara, dá uma olhada nisso aqui #328

**Comment by mariovalney** [comment]
Então... Tema Filho é o ideal para manter o Tema Pai recebendo atualização, porém esse não é o caso do Odin.

O Odin é um tema base, então a ideia é realmente sobrescrever os arquivos dele (evitando o Core, claro). Afinal você está criando um tema novo.

**Comment by aynoei** [comment]
Muito obrigado. Entendi a explicação da finalidade do tema e concordo com a ideia. 
Estou usando nos meus projetos e gostei muito.
