### ISSUE TITLE
Alterar labels/nomes de post "default"

### ISSUE THREAD

**Issue by rafa-acioly** [wpbrasil/odin#459]
Na documentação eu consigo criar `custom post types` e creio que seria interessante se pudêssemos incluir algumas funções para também alterar os nomes do post  `"default"` que já é vem no `wordpress`, por exemplo, alterar de "posts" para "cardapio", "ver cardapio", "adicionar item" e etc.
As vezes é mais conveniente alterar estes campos e utiliza-lo do que criar um novo tipo de post.

**Comment by Rahmon** [comment]
Olá @rafa-acioly.

Não faz sentido isso que você quer, por mais que seja conveniente. Já que existe a possibilidade de criar um custom post type. Minha opinão é que Posts são Posts...xD

**Comment by mariovalney** [comment]
@Rahmon acho que ele quis dizer mudar o label ao criar um custom post type, ou seja, as frases "Adicionar novo post", etc...

É isso @rafa-acioly ?

**Comment by rafa-acioly** [comment]
@Rahmon Algumas vezes precisei criar apenas **um** custom post type e o `post` default ficava sem utilização, foi ai que decidi renomear os campos, labels e etc do post `defaut` para não precisar instalar plugins e etc.
A ideia principal é "reciclar" o post default quando ele vai ficar sem utilização.

No meu caso aconteceu o seguinte;
Meu cliente precisava publicar os pratos do restaurante dele e separa-los em 2 categorias, Delivery e não Delivery, a principio pensei em baixar o `CPT UI` e criar um post apenas com os campos, titulo, conteúdo e categoria mas deste modo o post default ficaria sem utilização, foi ai que decidi renomear os campos do post default para utiliza-lo com os nomes que meu cliente gostaria e então não precisei criar um custom post type para isso.

A intenção real é "reciclar" o post default quando ele ficar sem utilização.

**Comment by mariovalney** [comment]
Entendi sua intenção. 

Bem... particularmente eu não gosto dessa implementação. Prefiro criar CPTs e esconder o que for do post padrão... principalmente porque vai que o cliente do nada chega e diz: queria um blog também... aí eu só "reativo" os menus.

**Comment by rafa-acioly** [comment]
De fato não é tão trivial, mas agradeço por ter aceitado como sugestão!

**Comment by mariovalney** [comment]
Então acho que podemos fechar, né?
