### ISSUE TITLE
uso do Odin_Post_Form

### ISSUE THREAD

**Issue by igorgadelha** [wpbrasil/odin#460]
Boa dia,

Existe algum exemplo uso do Odin_Post_Form? Preciso criar um formulário no front-end para envio de um post_type específico, dei uma olhada na classe, na documentação, até pesquisei nas issues anteriores, mas não encontrei. Alguém que possa dar uma ajuda ou orientação?

**Comment by mariovalney** [comment]
Já temos documentação dela:
https://github.com/wpbrasil/odin/wiki/Classe-Odin_Post_Form
