### ISSUE TITLE
Tema pré existente

### ISSUE THREAD

**Issue by amanhecido** [wpbrasil/odin#462]
Antes de mais nada gostaria de parabenizar a todos os envolvidos pelo excelente framework. Estou realmente impressionado.

Por isso, gostaria de adotar o Odin em meus temas. Mas antes gostaria de sanar 2 dúvidas:
1 - Posso utilizar somente a pasta Core em meus temas pré-existentes ou preciso manter minimamente a estrutura por questões técnicas ou de licenciamento?
2 - Já utilizo o bootstrap 4 em alguns dos meus temas. Alguem sabe de alguma questão de incompatibilidade que possa ocorrer com o código gerado pelas classes do core?

Agredeço de antemão e me ponho à disposição para auxiliar no projeto.

**Comment by mariovalney** [comment]
1 - Sim, pode usar claro.

2 - Muito do front é você que monta.  Acho que as partes mais engessadas seriam "paginação" e as classes de menus... mas nada problemático ao meu ver.
