### ISSUE TITLE
Personalização dos Assets

### ISSUE THREAD

**Issue by rgenesis** [wpbrasil/odin#467]
Hey!

Gostaria de sugeri adicionar a documentação como o Odin enfileira os assets para total personalização do front. Por exemplo, se quiser adicionar apenas parte do bootstrap ou meu próprio CSS, etc. 

`function odin_stylesheet_uri( $uri, $dir ) {`
`	return $dir . '/assets/css/style.css'; `
`}`

Eu demorei umas 3h pra achar esse código a cima que está no functions.php. Gostaria de saber onde fica a `function` que envia os `.js` para o `wp_footer` e `wp_head`.

Obrigado antecipadamente!

**Comment by everaldomatias** [comment]
Os arquivos .js são adicionados a partir do functions.php também.
Observe entre as linhas 233 e 245 ( https://github.com/wpbrasil/odin/blob/master/functions.php#L233 )

**Comment by genesis-ws** [comment]
Valeu pela ajuda. Eu realmente preciso carregar o Bootstrap customizado, porque ele é além do meu projeto.
