### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by gui8515** [wpbrasil/odin#470]
oi queria saber se vou ter que editar muita coisa se eu colocar o Bootstrap 4?

sou novo com o wordpress ^^

**Comment by renanlara** [comment]
@gui8515, não vai. Eu estava pensando em fazer isso agora no final do ano.
Basicamente é trocar os arquivos do sass e js da pasta assets e pronto. Só precisa ver com calma em como o grunt vai se comportar com isso, se será necessário realizar alguma modificação nele ou não.

**Comment by dpiaia** [comment]
Esse cara aqui começou ja.. vale a pena dar uma olhada 
https://github.com/lmartim/odin

**Comment by crasolutions** [comment]
Bom dia a todos! Estou comecei a estudar o framework Odin e tenho uma dúvida.
O framework vai atualizar para a versão 4.1 do Bootstrap?

Posso usar outro framework CSS por exemplo Bulma sem ter que fazer muitas alterações?

Valeu!

**Comment by gspmonteiro** [comment]
Eu tbm estou com essa dúvida, pois o projeto poderia estar andando melhor com o bootstrap v4.0 ou v4.1, eu vi um outro projeto que pode ser usado como exemplo, eles não usam o grunt, mas o gulp para processar o Sass, só não sei se processa o js para minificá-lo. 

https://github.com/understrap/understrap

Eu adoro o Odin, não gostaria de ver ele abandonado :( !

**Comment by allysonsouza** [comment]
@gspmonteiro está para ser lançada a versão 3.0, que está em beta, onde o Bootstrap 4 é utilizado ;)
Precisamos de pessoas testando o projeto e dando seu feedback, você pode baixá-la aqui: https://github.com/wpbrasil/odin/tree/v3-beta
