### ISSUE TITLE
Tema + Odin

### ISSUE THREAD

**Issue by gui8515** [wpbrasil/odin#471]
Pesquisei um pouco mais aqui e vi um artigo falando que da pra colocar o Odin dentro de um tema

https://www.kinghost.com.br/blog/2016/08/underscore-e-odin-desenvolvimento-de-temas-wp-com-frameworks/ 

a duvida é da certo? 
Quais tags eu chamo pra construir o tema?

**Comment by RafaelFunchal** [comment]
O Odin já é um tema. 

Nesse link temos a documentação de como usá-lo:

https://github.com/wpbrasil/odin/wiki

**Comment by adammacias** [comment]
@gui8515 neste repositório vc pode adicionar as "ferramentas" do Odin via Plugin https://github.com/wpbrasil/odin-toolkit
