### ISSUE TITLE
Arquivo Para CSS Customizado - get_option() não funciona.

### ISSUE THREAD

**Issue by guisierra** [wpbrasil/odin#472]
Criei um arquivo chamado options.css.php onde ficará armazenada as informações das cores customizadas inseridas pelo usuário no painel "Opções do Tema".

## Caminho para o arquivo de .css customizado: ##

href='/assets/css/options.css.php' type='text/css' media='all'...

## Código do arquivo options.css.php ##

$general_options = get_option( 'odin_general' );
header('Content-Type: text/css');

body {
  background-color: echo $general_options['back_color_01'];
}

Diferente de todos os outros arquivos do Tema que retorna sem problema a função get_option() onde consigo chamar opções para qualquer página, nesse arquivo que criei não funciona, é apresentado o erro de função não definida.

Alguém sabe resolver isso?

Solução alternativa ou mais consistente será de grande validade, de coração, Obrigado

**Comment by renanlara** [comment]
Se estiver usando a class do Odin, veja isso: https://github.com/wpbrasil/odin/wiki/Classe-Odin_Theme_Options

**Comment by luizbills** [comment]
`get_option` é definida pelo wordpress, então você tem que dar include do arquivo(s) que é necessário para que ela funcione. Mas recomendo muito mais é você ouvir a ação `wp_head`

```php
add_action( 'wp_head', 'seuprefixo_add_css_in_head', 11 );

function seuprefixo_add_css_in_head () {
  $general_options = get_option( 'odin_general' );
  ?>
  <style>
    body {
      background-color: <?php echo $general_options['back_color_01']; ?>;
    }
  </style>
  <?
}
