### ISSUE TITLE
Um tema feito com framework Odin 

### ISSUE THREAD

**Issue by TiagoHeld** [wpbrasil/odin#478]
Onde se localiza a função para css externo eu já verifiquei na function e não ta lá a função

**Comment by renanlara** [comment]
O Odin vem com o Sass. Você pode criar novos arquivos .scss e fazer o seu CSS. Só não pode se esquecer de importar os arquivos `assets/sass/style.scss` para que o grunt possa compilar.
> Wiki [https://github.com/wpbrasil/odin/wiki/Usando-o-Sass](https://github.com/wpbrasil/odin/wiki/Usando-o-Sass)

**Comment by AdsonCicilioti** [comment]
@TiagoHeld 

O arquivo css do tema é carregado pela função [odin_stylesheet_uri()](https://github.com/wpbrasil/odin/blob/master/functions.php#L268) (clica aí!) que está no functions.php. Ele faz um filter no hook nativo do WP [stylesheet_uri](https://developer.wordpress.org/reference/hooks/stylesheet_uri/).

Lembrando que este aquivo `style.css` é compilado a partir do `style.scss` que está na pasta `assets/sass/`. A proposta do tema é que você gerencie as suas folhas de estilo próprias ou de terceiros, no caso do Odin, já vem com o Bootstrap... Mas agora é contigo!! Bom desenvolvimento!

**Comment by AdsonCicilioti** [comment]
@renanlara essa seria a informação complementar. Mas parece que ele precisava entender como o estilo era incorporado ao tema.

E sim, é com Sass que ele vai gerenciar os estilos do tema, e no final apenas um arquivo css compactado será carregado (isso não inclui arquivos css de plugins), o que deixa o Odin rápido e otimizado.

**Comment by renanlara** [comment]
De boa @AdsonCicilioti, quanto mais informação melhor. :D
