### ISSUE TITLE
Duvida de iniciante - custom post type e metabox

### ISSUE THREAD

**Issue by fabianomaximiano** [wpbrasil/odin#481]
Boa noite, tudo bem pessoal?

Estou com dificuldade para resolver uma questao simples pelo menos para voces, seguindo a documentaçao fui bem ate o ponto trazer para meu tema alguns campos que criei no tema.

https://gist.github.com/fabianomaximiano/96e0c578af1682500b2bbe3b0dbee7a6

Este é o codigo da single.php

<?php
/**
 * The Template for displaying all single posts.
 *
 * @package Odin
 * @since 2.2.0
 */

get_header(); ?>
        <?php the_title(); ?>
				<?php get_post_meta($post->id, 'titulo_evento', true); ?>
				<?php get_post_meta( $evento->ID,'descricao_evento', true ); ?>
		

<?php
get_footer();

Se fiz algo errado aqui por favor me perdoem, pois sou bem noobe no assunto, ainda estou aprendendo.
Abraços

**Comment by netojose** [comment]
@fabianomaximiano , dois detalhes:
1. no lugar de `$post->id`, use `get_the_ID()`
2. diferente da função `the_title()`essas funções get_xxx apenas retornam, mas não imprimem, então, você precisa usar `echo` antes para exibir o valor.

**Comment by netojose** [comment]
@fabianomaximiano , partindo do pressuposto de que você está dentro de um loop do Wordpress, você faria isso:

<?php the_title(); ?>
<?php echo get_post_meta(get_the_ID(), 'titulo_evento', true); ?>
<?php echo get_post_meta( get_the_ID(),'descricao_evento', true ); ?>
