### ISSUE TITLE
Adicionando CSS?

### ISSUE THREAD

**Issue by ocariocawebdesign** [wpbrasil/odin#482]
Como adiciono outro arquivo CSS pelo functions.php? Queria adicionar o fontawesome.css e o animate.css

Estou tentando a função: 
```
function odin_stylesheet_uri( $uri, $dir ) {
return $dir . '/assets/css/"arquivo".css';
}
```
Não estou tendo sucesso, alguém pode me dar uma direção?

**Comment by everaldomatias** [comment]
@crasolutions a forma correta de adicionar é com a função nativa do WP [wp_enqueue_style()](https://developer.wordpress.org/reference/functions/wp_enqueue_style/). Essa função que apontou acima é usada pelo Odin para localizar o stylesheet padrão do tema.

**Comment by renanlara** [comment]
@crasolutions, você pode usar os SASS trabalhar para você aí. Converta esses arquivos em .scss e faça a importação no /assets/style.scss. O legal que eles tbm serão minificados juntamente com o restante dos arquivos.

**Comment by allysonsouza** [comment]
Fechando esta issue por falta de interação.
