### ISSUE TITLE
Portal de Notícias

### ISSUE THREAD

**Issue by juniortavares** [wpbrasil/odin#485]
Olá a todos.
Eu gostaria de saber se usando o Odin eu consigo criar um Portal de Notícias.
Abraços a todos

**Comment by nandomoreirame** [comment]
Da sim, com WordPress da pra criar portais de notícias, blogs, lojas virtuais, sistemas qualquer coisa

**Comment by juniortavares** [comment]
Mais assim, eu já criei alguns porém usando temas prontos.
Tô querendo criar usando o Odin, inclusive tem um site diariodabahia.com.br que foi feito no Framework Roots... 
Será que dá pra criar algo semelhante no Odin?

**Comment by renanlara** [comment]
@juniortavares, dá para você criar o que quiser com o Odin.
Um tema ou o Odin não seria algo que te limitasse a desenvolver o que quisesse, basta você saber fazer.

**Comment by allysonsouza** [comment]
Nós criamos este portal de notícias com o Odin: http://jornaldotrem.com.br/

**Comment by adammacias** [comment]
Outra referencia de portal desenvolvido com Odin http://www.cmmacae.rj.gov.br/
