### ISSUE TITLE
Repositório de imagens e informações

### ISSUE THREAD

**Issue by daniloleite** [wpbrasil/odin#486]
Boa tarde!

Neste sábado fui no WordCamp SP e vi uma palestra sobre o Odin com Jakeliny Gracielly.
Sou leigo em programação, estou iniciando e escolhi o Wordpress para ter o meu primeiro contato com algo na área. Fiquei surpreso com as possibilidades do Odin.

Dúvida de iniciante: É possível criar um Custom Post Type, com campos para upload de imagens (galeria de fotos), categorias, Editor, taxonomias (em forma de checkbox), certo? Vi na documentação.
Mas, não entendi onde colo o exemplo http://wpod.in/v2/Classe-Odin_Metabox.html#instalacao 
Devo colar o código todo no arquivo functions.php ? Ou é necessário criar alguma outra página php?

Outra dúvida, como posso 'chamar' um carrocel custom Post types na home do meu site ?

Muito obrigado!

Danilo

**Comment by adammacias** [comment]
@daniloleite isso mesmo, o código deve ser inserido no `functions.php`, você pode tambem usar o código em outro arquivo PHP, mas deve fazer o include/require deste no `functions.php`.

Sobre o carousel é possível sim, use [`WP_Query`](https://codex.wordpress.org/Class_Reference/WP_Query) para montar uma query personalizada, daí é só setar o name do custom type post em [`post_type`](https://codex.wordpress.org/Class_Reference/WP_Query#Type_Parameters)

**Comment by daniloleite** [comment]
@adammacias  Muitíssimo obrigado!
Estou conseguindo e vou buscar sobre o WP_Query  ... 
Abraços
