### ISSUE TITLE
A documentação está desatualizada?

### ISSUE THREAD

**Issue by John-Henrique** [wpbrasil/odin#489]
Estava estudando a documentação e a primeira coisa que me deparei foi com uma 'incompatibilidade', no arquivo release não existe o diretório "core", mas na documentação cita a instrução 

`require_once get_template_directory() . '/core/classes/class-metabox.php';`

Com isso não dá pra usar, então, a documentação está desatualizada?

**Comment by adammacias** [comment]
@John-Henrique que versão vc está usando? a v2.x ainda tem https://github.com/wpbrasil/odin/blob/master/core/classes/class-metabox.php

Já a partir da versão da 3.x (beta) esse recurso foi movido para plugin.
