### ISSUE TITLE
Tema bloqueando CSS e JS de plugins

### ISSUE THREAD

**Issue by scirrus** [wpbrasil/odin#491]
Bom dia!
Preciso corrigir um problema numa instalação WP 5.1.1 com tema baseado em Odin 2.2.5.
Nenhum script ou estilo de plugin (como CF7) é carregado.
Não sei se a causa é incompatibilidade com o WP mais recente ou se o tema é que bloqueia o enfileiramento.
Alguém poderia por favor indicar como posso checar essas possibilidades?
Obrigado!

**Comment by lenivene** [comment]
> ... se o tema é que bloqueia o enfileiramento.

No momento que você diz isso dá entender que você está se referindo a o uso do theme odin ou realmente é algum feito baseado nele?

Se é um baseado nele, tem o `wp_head();` no `header.php`?

**Comment by leobaiano** [comment]
Complementando a resposta do @lenivene, para os scripts precisa ter o `wp_footer()`, o arquivo onde as funções (`wp_head()` e `wp_footer()`) se encontram não importa tanto, mas para carregar os arquivos CSS através da action `wp_head` que os plugins costumam utilizar a função precisa estar entre `<head>` e `</head>`.

**Comment by scirrus** [comment]
Obrigado!
