### ISSUE TITLE
Criar menu para Shortcodes

### ISSUE THREAD

**Issue by claudiosmweb** [wpbrasil/odin#92]
Precisamos criar um menu com opções para ajudar inserir esses shortcodes que temos agora.

Aqui tem um exemplo de como fazer isso: https://github.com/claudiosmweb/gist-github-shortcode

**Comment by tiagofabre** [comment]
E se ao invés de criar um menu para as shortcodes, fosse utilizado/desenvolvido um criador de shortcodes que gera esse menu com todos os campos necessários 'automagicamente'?

**Comment by rafaelfunchal** [comment]
Está falando algo como o [Shortcake](https://wordpress.org/plugins/shortcode-ui/), @tiagofabre ?

**Comment by tiagofabre** [comment]
Sim, exatamente isso @rafaelfunchal. 
Adicionar o shortcode e os tipos de parâmetros que ele recebe, depois disso toda a interface é gerada. Isso evita bastante retrabalho e facilita o desenvolvimento de futuras shortcodes por não ter que se preocupar com Plugins tinyMCE, pequenos detalhes e etc...

**Comment by claudiosmweb** [comment]
Nem, aqui a ideia era só ter menu para os shortcodes que já temos hoje.
É fácil pra caramba fazer isso: https://github.com/woothemes/woocommerce-shortcodes

**Comment by claudiosmweb** [comment]
Esse é o tipo de issue que qualquer um poderia fechar, mas que vou acabar fechando porque ficaram com medo de fazer.

**Comment by tiagofabre** [comment]
Concordo que adicionar as shortcodes existentes não é difícil. Mas o lance dessa ferramenta é a reutilização de código... Criar uma pagina não é difícil, mas mesmo assim existe um criador de páginas...

Talvez isso só devesse estar numa issue de sugestão...

Ah, pode deixar que eu fecho essa issue, faço o dropdown só dos existentes...

**Comment by tiagofabre** [comment]
segue o [pull request](https://github.com/wpbrasil/odin/pull/349)
